<a href="https://colab.research.google.com/github/faridaeldeshy-max/AURIX.V1/blob/main/AURIX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

In [1]:
# AURIX — Project Configuration

PROJECT_NAME = "AURIX"
RANDOM_SEED = 42

print(f"{PROJECT_NAME} configuration loaded.")

AURIX configuration loaded.

In [2]:
!git clone https://github.com/faridaeldeshy-max/AURIX.V1.git

Cloning into 'AURIX.V1'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 15 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (15/15), done.
Resolving deltas: 100% (1/1), done.

In [3]:
%cd /content/AURIX.V1

/content/AURIX.V1

In [4]:
!ls -la

total 24
drwxr-xr-x 3 root root 4096 Oct 20 20:37 .
drwxr-xr-x 1 root root 4096 Oct 20 20:37 ..
-rw-r--r-- 1 root root 1366 Oct 20 20:37 AURIX.ipynb
drwxr-xr-x 8 root root 4096 Oct 20 20:37 .git
-rw-r--r-- 1 root root  231 Oct 20 20:37 .gitignore
-rw-r--r-- 1 root root   10 Oct 20 20:37 README.md

In [5]:
!git remote -v

origin	https://github.com/faridaeldeshy-max/AURIX.V1.git (fetch)
origin	https://github.com/faridaeldeshy-max/AURIX.V1.git (push)

In [6]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [7]:
import sys
print("Python version:", sys.version)

Python version: 3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]

In [8]:
try:
    import torch
    print("PyTorch version:", torch.__version__)
    print("CUDA available:", torch.cuda.is_available())
except ImportError:
    print("PyTorch is not installed.")

PyTorch version: 2.11.0+cpu
CUDA available: False

In [9]:
!find . -maxdepth 2 -type f

./README.md
./AURIX.ipynb
./.gitignore
./.git/config
./.git/index
./.git/description
./.git/HEAD
./.git/packed-refs

In [10]:
!cat README.md

# AURIX.V1

In [11]:
!git log -1 --oneline

a453736 (HEAD -> main, origin/main, origin/HEAD) Update .gitignore

In [12]:
import numpy as np
import pandas as pd
import soundfile as sf
import sklearn

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("SoundFile:", sf.__version__)
print("Scikit-learn:", sklearn.__version__)

NumPy: 2.1.3
Pandas: 2.2.3
SoundFile: 0.14.0
Scikit-learn: 1.6.1

In [13]:
# AURIX — Core Configuration

from pathlib import Path
import random
import numpy as np

PROJECT_NAME = "AURIX"
RANDOM_SEED = 42

DATA_DIR = Path("/content/AURIX_data")
RESULTS_DIR = Path("/content/AURIX_results")

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

DATA_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"{PROJECT_NAME} configuration ready.")
print(f"Data directory: {DATA_DIR}")
print(f"Results directory: {RESULTS_DIR}")

AURIX configuration ready.
Data directory: /content/AURIX_data
Results directory: /content/AURIX_results

In [14]:
!df -h /content

Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   21G   88G  20% /

In [15]:
import requests

url = "https://zenodo.org/records/19336329/files/dev_bearingEmu.zip"

response = requests.head(url, allow_redirects=True, timeout=30)

print("HTTP status:", response.status_code)
print("File size (GB):", round(int(response.headers.get("content-length", 0)) / (1024**3), 2))
print("Final URL:", response.url)

HTTP status: 200
File size (GB): 0.57
Final URL: https://zenodo.org/records/19336329/files/dev_bearingEmu.zip

In [16]:
import requests
from tqdm.auto import tqdm

url = "https://zenodo.org/records/19336329/files/dev_bearingEmu.zip"
zip_path = DATA_DIR / "dev_bearingEmu.zip"

with requests.get(url, stream=True, timeout=60) as response:
    response.raise_for_status()
    total = int(response.headers.get("content-length", 0))

    with open(zip_path, "wb") as f, tqdm(
        total=total,
        unit="B",
        unit_scale=True,
        desc="Downloading AURIX dataset"
    ) as progress:
        for chunk in response.iter_content(chunk_size=1024 * 1024):
            if chunk:
                f.write(chunk)
                progress.update(len(chunk))

print("Download complete:", zip_path)
print("File size (GB):", round(zip_path.stat().st_size / (1024**3), 2))

Downloading AURIX dataset:   0%|          | 0.00/608M [00:00<?, ?B/s]

Download complete: /content/AURIX_data/dev_bearingEmu.zip
File size (GB): 0.57

In [17]:
import zipfile

zip_path = DATA_DIR / "dev_bearingEmu.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    files = z.namelist()
    print("Total items:", len(files))
    print("\nFirst 25 items:")
    for name in files[:25]:
        print(name)

    print("\nArchive integrity:", "OK" if z.testzip() is None else "ERROR")

Total items: 1204

First 25 items:
bearingEmu/
bearingEmu/attributes_00.csv
bearingEmu/test/
bearingEmu/test/section_00_source_test_anomaly_0000_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0001_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0002_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0003_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0004_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0005_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0006_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0007_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0008_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0009_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0010_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0011_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0012_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0013_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0014_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0015_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0016_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0017_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0018_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0019_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0020_noAttribute.wav
bearingEmu/test/section_00_source_test_anomaly_0021_noAttribute.wav

Archive integrity: OK

In [18]:
import zipfile

zip_path = DATA_DIR / "dev_bearingEmu.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(DATA_DIR)

EXTRACTED_DIR = DATA_DIR / "bearingEmu"

print("Extraction complete:", EXTRACTED_DIR.exists())
print("Dataset folders:", [p.name for p in EXTRACTED_DIR.iterdir() if p.is_dir()])
print("Attributes file exists:", (EXTRACTED_DIR / "attributes_00.csv").exists())

Extraction complete: True
Dataset folders: ['test', 'train']
Attributes file exists: True

In [19]:
from pathlib import Path
import pandas as pd

train_files = list((EXTRACTED_DIR / "train").glob("*.wav"))
test_files = list((EXTRACTED_DIR / "test").glob("*.wav"))

attributes = pd.read_csv(EXTRACTED_DIR / "attributes_00.csv")

print("Training WAV files:", len(train_files))
print("Testing WAV files:", len(test_files))
print("Attributes shape:", attributes.shape)
print("\nCSV columns:")
print(attributes.columns.tolist())
print("\nFirst 5 rows:")
display(attributes.head())

Training WAV files: 1000
Testing WAV files: 200
Attributes shape: (1200, 1)

CSV columns:
['file_name']

First 5 rows:

                                           file_name
0  /bearingEmu/train/section_00_source_train_norm...
1  /bearingEmu/train/section_00_source_train_norm...
2  /bearingEmu/train/section_00_source_train_norm...
3  /bearingEmu/train/section_00_source_train_norm...
4  /bearingEmu/train/section_00_source_train_norm...

In [20]:
from collections import Counter
import soundfile as sf

print("TRAIN — sample filenames:")
for p in sorted(train_files)[:8]:
    print(p.name)

print("\nTEST — sample filenames:")
for p in sorted(test_files)[:12]:
    print(p.name)

print("\nTRAIN filename patterns:")
print(Counter(
    "normal" if "norm" in p.name.lower()
    else "anomaly" if "anomaly" in p.name.lower()
    else "other"
    for p in train_files
))

print("\nTEST filename patterns:")
print(Counter(
    "normal" if "norm" in p.name.lower()
    else "anomaly" if "anomaly" in p.name.lower()
    else "other"
    for p in test_files
))

print("\nExample audio metadata:")
print(sf.info(str(train_files[0])))

TRAIN — sample filenames:
section_00_source_train_normal_0000_noAttribute.wav
section_00_source_train_normal_0001_noAttribute.wav
section_00_source_train_normal_0002_noAttribute.wav
section_00_source_train_normal_0003_noAttribute.wav
section_00_source_train_normal_0004_noAttribute.wav
section_00_source_train_normal_0005_noAttribute.wav
section_00_source_train_normal_0006_noAttribute.wav
section_00_source_train_normal_0007_noAttribute.wav

TEST — sample filenames:
section_00_source_test_anomaly_0000_noAttribute.wav
section_00_source_test_anomaly_0001_noAttribute.wav
section_00_source_test_anomaly_0002_noAttribute.wav
section_00_source_test_anomaly_0003_noAttribute.wav
section_00_source_test_anomaly_0004_noAttribute.wav
section_00_source_test_anomaly_0005_noAttribute.wav
section_00_source_test_anomaly_0006_noAttribute.wav
section_00_source_test_anomaly_0007_noAttribute.wav
section_00_source_test_anomaly_0008_noAttribute.wav
section_00_source_test_anomaly_0009_noAttribute.wav
section_00_source_test_anomaly_0010_noAttribute.wav
section_00_source_test_anomaly_0011_noAttribute.wav

TRAIN filename patterns:
Counter({'normal': 1000})

TEST filename patterns:
Counter({'anomaly': 100, 'normal': 100})

Example audio metadata:
/content/AURIX_data/bearingEmu/train/section_00_source_train_normal_0067_noAttribute.wav
samplerate: 16000 Hz
channels: 2
duration: 10.000 s
format: WAV (Microsoft) [WAV]
subtype: Signed 16 bit PCM [PCM_16]

In [21]:
import soundfile as sf
import numpy as np

sample_file = train_files[0]
audio, sr = sf.read(sample_file)

print("File:", sample_file.name)
print("Audio shape:", audio.shape)
print("Sample rate:", sr)

for ch in range(audio.shape[1]):
    signal = audio[:, ch]
    print(f"\nChannel {ch}:")
    print("  Mean:", round(float(np.mean(signal)), 6))
    print("  Standard deviation:", round(float(np.std(signal)), 6))
    print("  RMS:", round(float(np.sqrt(np.mean(signal**2))), 6))

File: section_00_source_train_normal_0067_noAttribute.wav
Audio shape: (160000, 2)
Sample rate: 16000

Channel 0:
  Mean: -4.6e-05
  Standard deviation: 0.011981
  RMS: 0.011981

Channel 1:
  Mean: -4.7e-05
  Standard deviation: 0.012002
  RMS: 0.012002

In [22]:
correlation = np.corrcoef(audio[:, 0], audio[:, 1])[0, 1]
difference_rms = np.sqrt(np.mean((audio[:, 0] - audio[:, 1]) ** 2))

print("Channel correlation:", round(float(correlation), 6))
print("Difference RMS:", round(float(difference_rms), 6))

Channel correlation: 0.340717
Difference RMS: 0.013769

In [23]:
import soundfile as sf
import numpy as np

normal_file = next(
    f for f in sorted(test_files) if "normal" in f.name.lower()
)
anomaly_file = next(
    f for f in sorted(test_files) if "anomaly" in f.name.lower()
)

for label, file_path in [
    ("Normal", normal_file),
    ("Anomaly", anomaly_file),
]:
    signal, sample_rate = sf.read(file_path)

    correlation = np.corrcoef(signal[:, 0], signal[:, 1])[0, 1]
    difference_rms = np.sqrt(
        np.mean((signal[:, 0] - signal[:, 1]) ** 2)
    )

    print(f"{label}: {file_path.name}")
    print(f"  Correlation: {correlation:.6f}")
    print(f"  Difference RMS: {difference_rms:.6f}")

Normal: section_00_source_test_normal_0000_noAttribute.wav
  Correlation: 0.292882
  Difference RMS: 0.013815
Anomaly: section_00_source_test_anomaly_0000_noAttribute.wav
  Correlation: 0.329715
  Difference RMS: 0.014255

In [24]:
from collections import Counter

train_names = [f.name for f in train_files]
test_names = [f.name for f in test_files]

train_ids = set(train_names)
test_ids = set(test_names)

print("=== AURIX: Dataset Split Audit ===")
print("Training files:", len(train_names))
print("Testing files:", len(test_names))
print("Duplicate filenames in train:", len(train_names) - len(train_ids))
print("Duplicate filenames in test:", len(test_names) - len(test_ids))
print("Filename overlap between splits:", len(train_ids & test_ids))

print("\nTraining filename categories:")
print(Counter(
    "anomaly" if "anomaly" in name.lower()
    else "normal" if "normal" in name.lower()
    else "other"
    for name in train_names
))

print("\nTesting filename categories:")
print(Counter(
    "anomaly" if "anomaly" in name.lower()
    else "normal" if "normal" in name.lower()
    else "other"
    for name in test_names
))

=== AURIX: Dataset Split Audit ===
Training files: 1000
Testing files: 200
Duplicate filenames in train: 0
Duplicate filenames in test: 0
Filename overlap between splits: 0

Training filename categories:
Counter({'normal': 1000})

Testing filename categories:
Counter({'anomaly': 100, 'normal': 100})

In [25]:
import pandas as pd

attributes_path = EXTRACTED_DIR / "attributes_00.csv"
attributes_df = pd.read_csv(attributes_path)

print("Dataset metadata shape:", attributes_df.shape)
print("\nAvailable columns:")
print(attributes_df.columns.tolist())

print("\nFirst 10 rows:")
print(attributes_df.head(10).to_string(index=False))

print("\nMissing values per column:")
print(attributes_df.isna().sum().to_string())

Dataset metadata shape: (1200, 1)

Available columns:
['file_name']

First 10 rows:
                                                            file_name
/bearingEmu/train/section_00_source_train_normal_0000_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0001_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0002_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0003_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0004_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0005_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0006_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0007_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0008_noAttribute.wav
/bearingEmu/train/section_00_source_train_normal_0009_noAttribute.wav

Missing values per column:
file_name    0

In [26]:
from pathlib import Path
import zipfile
from pathlib import PurePosixPath

zip_path = Path("/content/AURIX_data/dev_bearingEmu.zip")

with zipfile.ZipFile(zip_path, "r") as z:
    names = z.namelist()

    candidates = [
        name for name in names
        if not name.endswith("/")
        and (
            PurePosixPath(name).suffix.lower()
            in {".md", ".txt", ".pdf", ".csv", ".json", ".yaml", ".yml", ".xml"}
            or any(term in name.lower()
                   for term in ("readme", "license", "metadata", "attribute"))
        )
    ]

    print("Archive entries:", len(names))
    print("Documentation/metadata candidates:", len(candidates))

    for name in candidates[:100]:
        print(f"{name} ({z.getinfo(name).file_size} bytes)")

Archive entries: 1204
Documentation/metadata candidates: 1201
bearingEmu/attributes_00.csv (84911 bytes)
bearingEmu/test/section_00_source_test_anomaly_0000_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0001_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0002_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0003_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0004_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0005_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0006_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0007_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0008_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0009_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0010_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0011_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0012_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0013_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0014_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0015_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0016_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0017_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0018_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0019_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0020_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0021_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0022_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0023_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0024_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0025_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0026_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0027_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0028_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0029_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0030_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0031_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0032_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0033_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0034_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0035_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0036_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0037_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0038_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0039_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0040_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0041_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0042_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0043_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0044_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0045_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0046_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0047_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0048_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_anomaly_0049_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0000_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0001_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0002_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0003_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0004_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0005_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0006_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0007_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0008_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0009_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0010_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0011_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0012_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0013_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0014_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0015_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0016_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0017_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0018_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0019_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0020_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0021_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0022_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0023_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0024_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0025_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0026_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0027_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0028_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0029_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0030_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0031_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0032_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0033_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0034_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0035_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0036_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0037_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0038_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0039_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0040_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0041_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0042_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0043_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0044_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0045_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0046_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0047_noAttribute.wav (640044 bytes)
bearingEmu/test/section_00_source_test_normal_0048_noAttribute.wav (640044 bytes)

In [27]:
import zipfile
from pathlib import PurePosixPath

with zipfile.ZipFile(zip_path, "r") as z:
    files = [n for n in z.namelist() if not n.endswith("/")]

    non_audio = [
        n for n in files
        if PurePosixPath(n).suffix.lower() != ".wav"
    ]

    print("Total files:", len(files))
    print("Non-audio files:", len(non_audio))

    for name in non_audio:
        print(f"{name} ({z.getinfo(name).file_size} bytes)")

Total files: 1201
Non-audio files: 1
bearingEmu/attributes_00.csv (84911 bytes)

In [28]:
import soundfile as sf
import numpy as np

samples_to_check = [
    train_files[0],
    train_files[len(train_files) // 2],
    train_files[-1],
    test_files[0],
    test_files[-1],
]

print("=== AURIX: Channel Structure Audit ===")

for path in samples_to_check:
    info = sf.info(str(path))
    audio, sr = sf.read(str(path), dtype="float32")

    ch0 = audio[:, 0]
    ch1 = audio[:, 1]

    correlation = np.corrcoef(ch0, ch1)[0, 1]
    difference_rms = np.sqrt(np.mean((ch0 - ch1) ** 2))

    print(f"\nFile: {path.name}")
    print(f"Sample rate: {sr} Hz")
    print(f"Channels: {info.channels}")
    print(f"Frames: {info.frames}")
    print(f"Subtype: {info.subtype}")
    print(f"Channel correlation: {correlation:.6f}")
    print(f"Difference RMS: {difference_rms:.6f}")

=== AURIX: Channel Structure Audit ===

File: section_00_source_train_normal_0067_noAttribute.wav
Sample rate: 16000 Hz
Channels: 2
Frames: 160000
Subtype: PCM_16
Channel correlation: 0.340717
Difference RMS: 0.013769

File: section_00_source_train_normal_0316_noAttribute.wav
Sample rate: 16000 Hz
Channels: 2
Frames: 160000
Subtype: PCM_16
Channel correlation: 0.400004
Difference RMS: 0.013184

File: section_00_source_train_normal_0902_noAttribute.wav
Sample rate: 16000 Hz
Channels: 2
Frames: 160000
Subtype: PCM_16
Channel correlation: 0.284035
Difference RMS: 0.013872

File: section_00_target_test_anomaly_0033_noAttribute.wav
Sample rate: 16000 Hz
Channels: 2
Frames: 160000
Subtype: PCM_16
Channel correlation: 0.313052
Difference RMS: 0.013540

File: section_00_source_test_anomaly_0007_noAttribute.wav
Sample rate: 16000 Hz
Channels: 2
Frames: 160000
Subtype: PCM_16
Channel correlation: 0.283258
Difference RMS: 0.013543

In [29]:
from collections import Counter

print("=== AURIX: Test Domain Audit ===")

for path in sorted(test_files, key=lambda p: p.name):
    pass

categories = Counter()

for path in test_files:
    name = path.name.lower()

    domain = (
        "source" if "_source_" in name
        else "target" if "_target_" in name
        else "unknown"
    )

    label = (
        "anomaly" if "_anomaly_" in name
        else "normal" if "_normal_" in name
        else "unknown"
    )

    categories[(domain, label)] += 1

for (domain, label), count in sorted(categories.items()):
    print(f"{domain:8} | {label:8} | {count}")

print("\nTotal test files:", len(test_files))

=== AURIX: Test Domain Audit ===
source   | anomaly  | 50
source   | normal   | 50
target   | anomaly  | 50
target   | normal   | 50

Total test files: 200

In [30]:
from collections import Counter

train_counts = Counter()

for path in train_files:
    name = path.name.lower()

    domain = (
        "source" if "_source_" in name
        else "target" if "_target_" in name
        else "unknown"
    )

    label = (
        "anomaly" if "_anomaly_" in name
        else "normal" if "_normal_" in name
        else "unknown"
    )

    train_counts[(domain, label)] += 1

print("=== AURIX: Training Domain Audit ===")

for (domain, label), count in sorted(train_counts.items()):
    print(f"{domain:8} | {label:8} | {count}")

print("\nTotal training files:", len(train_files))

=== AURIX: Training Domain Audit ===
source   | normal   | 990
target   | normal   | 10

Total training files: 1000

In [31]:
print("=== Target training files ===")

target_train_files = sorted(
    [p for p in train_files if "_target_" in p.name.lower()],
    key=lambda p: p.name
)

for path in target_train_files:
    print(path.name)

print("\n=== Source training index ranges ===")

source_indices = sorted(
    int(p.name.split("_normal_")[1].split("_")[0])
    for p in train_files
    if "_source_" in p.name.lower()
    and "_normal_" in p.name.lower()
)

print("Count:", len(source_indices))
print("Minimum index:", min(source_indices))
print("Maximum index:", max(source_indices))

=== Target training files ===
section_00_target_train_normal_0000_noAttribute.wav
section_00_target_train_normal_0001_noAttribute.wav
section_00_target_train_normal_0002_noAttribute.wav
section_00_target_train_normal_0003_noAttribute.wav
section_00_target_train_normal_0004_noAttribute.wav
section_00_target_train_normal_0005_noAttribute.wav
section_00_target_train_normal_0006_noAttribute.wav
section_00_target_train_normal_0007_noAttribute.wav
section_00_target_train_normal_0008_noAttribute.wav
section_00_target_train_normal_0009_noAttribute.wav

=== Source training index ranges ===
Count: 990
Minimum index: 0
Maximum index: 989

In [32]:
from pathlib import Path
import torch

PROJECT_DIR = Path("/content/AURIX.V1")
DATA_DIR = Path("/content/AURIX_data/bearingEmu")
RESULTS_DIR = Path("/content/AURIX_results")

assert PROJECT_DIR.exists(), "Project directory not found"
assert (PROJECT_DIR / "AURIX.ipynb").exists(), "Notebook not found"
assert (DATA_DIR / "train").is_dir(), "Training data not found"
assert (DATA_DIR / "test").is_dir(), "Test data not found"

train_files = sorted((DATA_DIR / "train").glob("*.wav"))
test_files = sorted((DATA_DIR / "test").glob("*.wav"))

print("Project:", PROJECT_DIR)
print("Training WAV files:", len(train_files))
print("Test WAV files:", len(test_files))
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Results directory exists:", RESULTS_DIR.exists())
print("AURIX preflight check passed.")

Project: /content/AURIX.V1
Training WAV files: 1000
Test WAV files: 200
PyTorch: 2.11.0+cpu
CUDA available: False
Results directory exists: True
AURIX preflight check passed.

In [33]:
from scipy.io import wavfile
import numpy as np

sample_path = next(
    p for p in train_files
    if "_source_train_normal_" in p.name
)

sample_rate, audio = wavfile.read(sample_path)

print("File:", sample_path.name)
print("Sample rate:", sample_rate)
print("Audio shape:", audio.shape)
print("Data type:", audio.dtype)

assert sample_rate == 16000, "Unexpected sample rate"
assert audio.ndim == 2 and audio.shape[1] == 2, "Expected stereo audio"
assert np.isfinite(audio).all(), "Audio contains invalid values"

for ch in range(2):
    x = audio[:, ch].astype(np.float64)
    print(
        f"Channel {ch}: "
        f"RMS={np.sqrt(np.mean(x**2)):.6f}, "
        f"Std={np.std(x):.6f}"
    )

print("Stereo audio validation passed.")

File: section_00_source_train_normal_0000_noAttribute.wav
Sample rate: 16000
Audio shape: (160000, 2)
Data type: int16
Channel 0: RMS=392.078122, Std=392.075736
Channel 1: RMS=423.318409, Std=423.316141
Stereo audio validation passed.

In [34]:
import importlib.util

packages = [
    "numpy",
    "scipy",
    "sklearn",
    "torch",
    "librosa",
    "soundfile",
]

for package in packages:
    available = importlib.util.find_spec(package) is not None
    print(f"{package}: {'AVAILABLE' if available else 'MISSING'}")

numpy: AVAILABLE
scipy: AVAILABLE
sklearn: AVAILABLE
torch: AVAILABLE
librosa: AVAILABLE
soundfile: AVAILABLE

In [35]:
EXPERIMENT_PLAN = {
    "project": "AURIX",
    "seed": 42,
    "sample_rate": 16000,
    "channels": {
        "near": 0,
        "far": 1,
    },
    "comparisons": [
        "channel_0_only",
        "channel_1_only",
        "early_fusion",
        "late_fusion",
    ],
    "evaluation_domains": ["source", "target"],
    "primary_metrics": ["AUC", "pAUC"],
    "test_set_policy": "final evaluation only",
    "training_mode": "normal-only anomaly detection",
}

for key, value in EXPERIMENT_PLAN.items():
    print(f"{key}: {value}")

print("\nExperiment plan initialized; no model trained.")

project: AURIX
seed: 42
sample_rate: 16000
channels: {'near': 0, 'far': 1}
comparisons: ['channel_0_only', 'channel_1_only', 'early_fusion', 'late_fusion']
evaluation_domains: ['source', 'target']
primary_metrics: ['AUC', 'pAUC']
test_set_policy: final evaluation only
training_mode: normal-only anomaly detection

Experiment plan initialized; no model trained.

In [36]:
import requests

url = (
    "https://raw.githubusercontent.com/"
    "nttcslab/dcase2023_task2_baseline_ae/main/baseline.yaml"
)

response = requests.get(url, timeout=20)
response.raise_for_status()

print(response.text)

--dataset_directory: ./data
--result_directory: ./results
--export_dir: baseline

--use_cuda: True
--log_interval: 100
--model: DCASE2023T2-AE
--score: MSE
--seed: 13711
--is_auto_download: False

--max_fpr: 0.1
--decision_threshold: 0.9

# feature
--n_mels: 128
--frames: 5
--frame_hop_length: 1
--n_fft: 1024
--hop_length: 512
--power: 2.0
--fmin: 0.0
--fmax: null
--win_length: null

# fit
--batch_size: 256
--epochs: 100
-lr: 0.001
--shuffle: True
--validation_split: 0.1

In [37]:
import requests

url = (
    "https://raw.githubusercontent.com/"
    "nttcslab/dcase2023_task2_baseline_ae/main/"
    "model.py"
)

response = requests.get(url, timeout=20)
response.raise_for_status()

source_code = response.text

for line_number, line in enumerate(source_code.splitlines(), start=1):
    if any(term in line.lower() for term in [
        "cuda",
        "device",
        "to(",
        "mps",
    ]):
        print(f"{line_number}: {line}")

HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/nttcslab/dcase2023_task2_baseline_ae/main/model.py

In [38]:
import requests

api_url = (
    "https://api.github.com/repos/"
    "nttcslab/dcase2023_task2_baseline_ae/contents"
)

response = requests.get(api_url, timeout=20)
response.raise_for_status()

for item in response.json():
    if item["type"] == "dir":
        print(f"\n[{item['name']}/]")
        folder_url = item["url"]
        folder_response = requests.get(folder_url, timeout=20)
        folder_response.raise_for_status()

        for child in folder_response.json():
            print(f"  {child['name']}")
    else:
        print(item["name"])

[.github/]
  pull_request_template.md
01_train_2026t2.sh
02a_test_2026t2.sh
02b_test_2026t2.sh
03_summarize_results.sh
CONTRIBUTING.md
LICENSE
LICENSEv2.1.pdf
README.md
README_legacy.md
baseline.yaml
common.py

[data/]
  dcase2020t2
  dcase2021t2
  dcase2022t2
  dcase2023t2
  dcase2024t2
  dcase2025t2
  dcase2026t2
data_download_2026add.sh
data_download_2026dev.sh
data_download_2026eval.sh

[datasets/]
  datasets.py
  dcase_dcase202x_t2_loader.py
  download_path_2023.yaml
  download_path_2024.yaml
  download_path_2025.yaml
  download_path_2026.yaml
  download_path_legacy.yaml
  eval_data_list_2020.csv
  eval_data_list_2021.csv
  eval_data_list_2022.csv
  eval_data_list_2023.csv
  eval_data_list_2024.csv
  eval_data_list_2025.csv
  eval_data_list_2026.csv
  ground_truth_attributes
  loader_common.py
  machine_type_2023_dev.yaml
  machine_type_2023_eval.yaml
  machine_type_2024_dev.yaml
  machine_type_2024_eval.yaml
  machine_type_2025_dev.yaml
  machine_type_2025_eval.yaml
  machine_type_2026_dev.yaml
  machine_type_2026_eval.yaml
  machine_type_legacy.yaml
dockerfile

[logs/]
  .gitignore

[models/]
  checkpoint
  saved_model

[networks/]
  base_model.py
  criterion
  dcase2023t2_ae
  models.py
requirements.txt

[results/]
  dev_data
  eval_data
test_ae.sh

[tools/]
  01_train_legacy.sh
  02a_test_legacy.sh
  02b_test_legacy.sh
  README.md
  concat_divided_roc.py
  data_download_2020.sh
  data_download_2021.sh
  data_download_2022.sh
  data_download_2023.sh
  data_download_2024.sh
  data_download_2025.sh
  export_results.py
  export_results.sh
  extract_results.py
  plot_anm_score.py
  plot_common.py
  plot_loss_curve.py
  plot_time_frequency.py
  rename_eval_wav.py
train.py
train_ae.sh

In [39]:
import requests

url = (
    "https://raw.githubusercontent.com/"
    "nttcslab/dcase2023_task2_baseline_ae/main/"
    "datasets/datasets.py"
)

response = requests.get(url, timeout=20)
response.raise_for_status()

for number, line in enumerate(response.text.splitlines(), start=1):
    if any(word in line.lower() for word in [
        "class datasets",
        "def data",
        "dcase2026",
        "bearing",
        "dataset",
        "loader",
    ]):
        print(f"{number}: {line}")

2: from torch.utils.data.dataset import Subset
6: from datasets.loader_common import get_machine_type_dict
7: from datasets.dcase_dcase202x_t2_loader import DCASE202XT2Loader
20:         dataset_name = args.dataset[:11]
21:         machine_type = args.dataset[11:]
23:             data_path = f'{args.dataset_directory}/{dataset_name.lower()}/eval_data/'
26:             data_path = f'{args.dataset_directory}/{dataset_name.lower()}/dev_data/'
33:         self.machine_type_dict = get_machine_type_dict(dataset_name, mode=args.dev)["machine_type"]
38:         section_keyword = get_machine_type_dict(dataset_name, mode=args.dev)["section_keyword"]
39:         train_data = DCASE202XT2Loader(
41:                 dataset_name=dataset_name,
62:         self.train_dataset = Subset(train_data, train_index)
63:         self.train_loader = torch.utils.data.DataLoader(
64:             self.train_dataset,
67:         self.valid_dataset   = Subset(train_data, valid_index)
68:         self.valid_loader = torch.utils.data.DataLoader(
69:             self.valid_dataset,
73:         self.test_loader = []
77:            _test_loader = DCASE202XT2Loader(
79:                 dataset_name=dataset_name,
98:            self.test_loader.append(
99:                 torch.utils.data.DataLoader(
100:                     _test_loader,
101:                     batch_size=_test_loader.n_vectors_ea_file, shuffle=False
104:            self.mode = args.dev or _test_loader.mode
107: class Datasets:
108:     DatasetsDic = {
109:         'DCASE2026T2ToyDrone':DCASE202XT2,
110:         'DCASE2026T2ToothBrush':DCASE202XT2,
111:         'DCASE2026T2SewingMachine':DCASE202XT2,
112:         'DCASE2026T2BlowerDustCollector':DCASE202XT2,
113:         'DCASE2026T2Sander':DCASE202XT2,
114:         'DCASE2026T2valveEmu':DCASE202XT2,
115:         'DCASE2026T2sliderEmu':DCASE202XT2,
116:         'DCASE2026T2gearboxEmu':DCASE202XT2,
117:         'DCASE2026T2fan':DCASE202XT2,
118:         'DCASE2026T2bearingEmu':DCASE202XT2,
119:         'DCASE2026T2ToyCarEmu':DCASE202XT2,
120:         'DCASE2026T2ToyCar':DCASE202XT2,
131:         'DCASE2025T2bearing':DCASE202XT2,
147:         'DCASE2024T2bearing':DCASE202XT2,
153:         'DCASE2023T2bearing':DCASE202XT2,
166:         'DCASE2022T2bearing':DCASE202XT2,
188:     def __init__(self,datasets_str):
189:         self.data = Datasets.DatasetsDic[datasets_str]
192:         return Datasets.DatasetsDic.keys()

In [40]:
import requests
from pathlib import Path

BASE = (
    "https://raw.githubusercontent.com/"
    "nttcslab/dcase2023_task2_baseline_ae/main/"
)

files_to_check = {
    "2026 training script": "01_train_2026t2.sh",
    "dataset loader": "datasets/dcase_dcase202x_t2_loader.py",
    "loader utilities": "datasets/loader_common.py",
}

keywords = (
    "dataset_directory", "dev_data", "eval_data",
    "bearingEmu", "mono", "channel", "stereo",
    "sound", "wav", "machine_type", "section_keyword"
)

for title, relative_path in files_to_check.items():
    print(f"\n{'=' * 18} {title} {'=' * 18}")
    url = BASE + relative_path
    response = requests.get(url, timeout=30)
    print("HTTP status:", response.status_code)

    if response.status_code != 200:
        print("Could not retrieve this file.")
        continue

    lines = response.text.splitlines()

    if title == "2026 training script":
        for i, line in enumerate(lines, 1):
            print(f"{i}: {line}")
    else:
        matches = [
            i for i, line in enumerate(lines)
            if any(word.lower() in line.lower() for word in keywords)
        ]
        shown = set()
        for i in matches:
            for j in range(max(0, i - 2), min(len(lines), i + 3)):
                if j not in shown:
                    print(f"{j + 1}: {lines[j]}")
                    shown.add(j)
            print("---")

print("\n========== AURIX dataset paths ==========")
for path in [
    Path("/content/AURIX_data/bearingEmu/train"),
    Path("/content/AURIX_data/bearingEmu/test"),
    Path("/content/AURIX_data/bearingEmu/attributes_00.csv"),
]:
    print(f"{path}: exists={path.exists()}")

================== 2026 training script ==================
HTTP status: 200
1: TZ=JST-9 date
2:
3: echo $0 $*
4:
5: dev_eval=$1
6: echo -e "\tdev_eval = '$dev_eval'"
7: echo
8:
9: # check args
10: if [ "${dev_eval}" != "-d" ] \
11:     && [ "${dev_eval}" != "-e" ] \
12:     && [ "${dev_eval}" != "--dev" ] \
13:     && [ "${dev_eval}" != "--eval" ]
14: then
15:     echo "$0: argument error"
16:     echo -e "usage\t: $0 ['-d' | '--dev' | '-e' | '--eval']"
17:     echo -e "\tinvalid choice '$dev_eval'"
18:     echo -e "\tchoice from ['-d' | '--dev' | '-e' | '--eval']."
19:     echo -e "\t\t-d, --dev\t: Using Development dataset. "
20:     echo -e "\t\t-e, --eval\t: Using Additional training dataset and Evaluation dataset. "
21:     echo -e "example\t: $ bash $0 -d"
22:     exit 1
23: fi
24:
25: # main process
26: base_job="bash"
27: job="train_ae.sh"
28: mono=False
29:
30: if [ "${dev_eval}" = "-d" ] || [ "${dev_eval}" = "--dev" ]
31: then
32:     dataset_list="\
33:         DCASE2026T2ToyCar \
34:         DCASE2026T2ToyCarEmu \
35:         DCASE2026T2bearingEmu \
36:         DCASE2026T2fan \
37:         DCASE2026T2gearboxEmu \
38:         DCASE2026T2sliderEmu \
39:         DCASE2026T2valveEmu \
40:     "
41: elif [ "${dev_eval}" = "-e" ] || [ "${dev_eval}" = "--eval" ]
42: then
43:     dataset_list="\
44:         DCASE2026T2ToyDrone \
45:         DCASE2026T2ToothBrush \
46:         DCASE2026T2SewingMachine \
47:         DCASE2026T2BlowerDustCollector \
48:         DCASE2026T2Sander \
49:     "
50: fi
51:
52: for dataset in $dataset_list; do
53:     ${base_job} ${job} ${dataset} ${dev_eval} ${mono} 0
54: done

================== dataset loader ==================
HTTP status: 200
15:                 root:str,
16:                 dataset_name,
17:                 section_keyword,
18:                 machine_type:str="ToyCar",
19:                 section_ids=[],
---
20:                 train=True,
---
32:                 use_id = [],
33:                 is_auto_download=False,
34:                 mono=True,
35:     ):
36:         super().__init__()
---
38:         self.use_id = use_id
39:         self.section_ids = section_ids
40:         self.machine_type = machine_type
41:
42:         target_dir = os.getcwd()+"/"+root+"raw/"+machine_type
---
43:         dir_name = "train" if train else "test"
44:
---
53:
54:         self.pickle_dir = os.path.abspath(
55:             "{dir}/processed/{machine_type}/{dir_name}".format(
56:                 dir=root,
57:                 machine_type=machine_type,
---
58:                 dir_name=dir_name
59:             )
---
79:                 target_dir=target_dir,
80:                 dir_name=dir_name,
81:                 machine_type=machine_type,
82:                 data_type=data_type,
83:                 dataset=dataset_name,
---
89:         print("dataset dir is exists.")
90:
91:         # get section names from wave file names
92:         section_names = [f"{section_keyword}_{section_id}" for section_id in section_ids]
93:         unique_section_names = np.unique(section_names)
---
94:         n_sections = len(unique_section_names)
---
98:         if not os.path.exists(self.log_melspectrogram_dir):
99:             os.makedirs(self.log_melspectrogram_dir, exist_ok=True)
100:         pickle_name = section_keyword
101:         for section_id in section_ids:
102:             pickle_name = f"{pickle_name}_{section_id}"
---
121:             fmin=fmin,
122:             win_length=win_length,
123:             mono=mono,
124:         )
125:         if len(self.use_id) > 0:
---
157:             fmin,
158:             win_length,
159:             mono=True,
160:         ):
161:
---
196:                     is_enabled_dataset_dir_lock = False
197:
198:             # number of wave files in each section
199:             # required for calculating y_pred for each wave file
200:             n_files_ea_section = []
---
201:
---
219:
220:                 data_ea_section = file_list_to_data(files,
221:                                         msg=f"generate {self.machine_type} section {self.section_ids[section_idx]} {dir_name} dataset",
222:                                         n_mels=n_mels,
223:                                         n_frames=frames,
---
229:                                         fmin=fmin,
230:                                         win_length=win_length,
231:                                         mono=mono)
232:                 self.data = np.append(self.data, data_ea_section, axis=0)
233:                 if self.mode or train:
---
244:             # number of all files
245:             n_all_files = sum(n_files_ea_section)
246:             # number of vectors for each wave file
247:             self.n_vectors_ea_file = int(self.data.shape[0] / n_all_files)
248:
---
332:                         fmin=None,
333:                         win_length=None,
334:                         mono=True):
335:     """
336:     convert the file_list to a vector array.
---
338:
339:     file_list : list [ str ]
340:         .wav filename list of dataset
341:     msg : str ( default = "calc..." )
342:         description for tqdm.
---
361:                                                 fmin=fmin,
362:                                                 win_length=win_length,
363:                                                 mono=mono)
364:         vectors = vectors[: : n_hop_frames, :]
365:         if idx == 0:
---

================== loader utilities ==================
HTTP status: 200
29: import datetime
30: from enum import Enum, auto
31: import soundfile as sf
32:
33: from tools.rename_eval_wav import copy_wav as rename_wav
---
34: ########################################################################
35:
---
88: # file I/O
89: ########################################################################
90: # wav file input
91: def file_load(wav_name, mono=False):
92:     """
---
93:     load .wav file.
---
94:
95:     wav_name : str
---
96:         target .wav file
97:     mono : boolean
---
98:         When load a multi channels file and this param True, the returned data will be merged for mono data
---
99:
---
100:     return : numpy.array( float )
---
101:     """
102:     info = sf.info(wav_name)
103:     ch = info.channels
104:     assert any([
---
105:         mono and ch == 1,
---
106:         not mono and ch > 1,
107:     ]), f"Channel mismatch: The file is {ch=}, but {mono=} is specified."
---
108:
---
109:     try:
---
110:         if mono:
111:             return librosa.load(wav_name, sr=None, mono=mono)
112:         else:
---
113:             y, sr = librosa.load(wav_name, sr=None, mono=mono)
---
114:             return y[0], sr
115:     except:
---
116:         logger.error("file_broken or not exists!! : {}".format(wav_name))
117:
118:
---
132:                     fmin=None,
133:                     win_length=None,
134:                     mono=True):
135:     """
136:     convert file_name to a vector array.
---
137:
138:     file_name : str
139:         target .wav file
140:
141:     return : numpy.array( numpy.array( float ) )
---
147:
148:     # generate melspectrogram using librosa
149:     y, sr = file_load(file_name, mono=mono)
150:
151:     mel_spectrogram = librosa.feature.melspectrogram(y=y,
---
191:         if active type the development :
192:             dirs :  list [ str ]
193:                 load base directory list of dev_data
194:         if active type the evaluation :
195:             dirs : list [ str ]
---
196:                 load base directory list of eval_data
197:     """
198:     if mode:
---
215: def get_section_names(target_dir,
216:                       dir_name,
217:                       ext="wav"):
218:     """
219:     target_dir : str
---
221:     dir_name : str
222:         sub directory name
223:     ext : str (default="wav)
224:         file extension of audio files
225:
---
241:
242: ########################################################################
243: # get the list of wave file paths
244: ########################################################################
245: def file_list_generator(target_dir,
---
251:                         prefix_normal="normal",
252:                         prefix_anomaly="anomaly",
253:                         ext="wav"):
254:     """
255:     target_dir : str
---
263:     prefix_anomaly : str (default="anomaly")
264:         anomaly directory name
265:     ext : str (default="wav")
266:         file extension of audio files
267:
---
317:         logger.info("#files : {num}".format(num=len(files)))
318:         if len(files) == 0:
319:             logger.exception("no_wav_file!!")
320:         print("\n========================================")
321:
---
334:         logger.info("#files : {num}".format(num=len(files)))
335:         if len(files) == 0:
336:             logger.exception("no_wav_file!!")
337:         print("\n=========================================")
338:
---
349:     target_dir,
350:     dir_name,
351:     machine_type,
352:     data_type,
353:     dataset,
---
392:         return
393:
394:     for i in np.arange(len(file_url[machine_type][data_type])):
395:         zip_file_basename = os.path.basename(file_url[machine_type][data_type][i])
396:         zip_file_path = f"{target_dir}/../{zip_file_basename}"
---
397:         try:
---
398:             if not zipfile.is_zipfile(zip_file_path):
399:                 print(f"Downloading...\n\tURL: {file_url[machine_type][data_type][i]}\r\tDownload: {zip_file_path}")
400:                 urllib.request.urlretrieve(
401:                     file_url[machine_type][data_type][i],
---
402:                     zip_file_path,
403:                     urllib_progress
---
409:                 target_dir,
410:                 dir_name,
411:                 machine_type,
412:                 data_type,
413:                 dataset,
---
437:
438:     if data_type == "eval" and dir_name == "test":
439:         rename_wav(
440:             dataset_parent_dir=root,
441:             dataset_type=dataset,
---
486: ########################################################################
487: YAML_PATH = {
488:     "legacy":"datasets/machine_type_legacy.yaml",
489:     "DCASE2023T2_dev":"datasets/machine_type_2023_dev.yaml",
490:     "DCASE2023T2_eval":"datasets/machine_type_2023_eval.yaml",
---
491:     "DCASE2024T2_dev":"datasets/machine_type_2024_dev.yaml",
---
492:     "DCASE2024T2_eval":"datasets/machine_type_2024_eval.yaml",
---
493:     "DCASE2025T2_dev":"datasets/machine_type_2025_dev.yaml",
---
494:     "DCASE2025T2_eval":"datasets/machine_type_2025_eval.yaml",
---
495:     "DCASE2026T2_dev":"datasets/machine_type_2026_dev.yaml",
---
496:     "DCASE2026T2_eval":"datasets/machine_type_2026_eval.yaml",
---
497: }
---
498:
---
499: def get_machine_type_dict(dataset_name, mode=True):
500:     if dataset_name in ["DCASE2020T2", "DCASE2021T2", "DCASE2022T2"]:
501:         yaml_path = YAML_PATH["legacy"]
---
520:
521:     with open(yaml_path, "r") as f:
522:         machine_type_dict = yaml.safe_load(f)
523:         return machine_type_dict[dataset_name]
---
---

========== AURIX dataset paths ==========
/content/AURIX_data/bearingEmu/train: exists=True
/content/AURIX_data/bearingEmu/test: exists=True
/content/AURIX_data/bearingEmu/attributes_00.csv: exists=True

In [41]:
from pathlib import Path
import subprocess

BASELINE_DIR = Path("/content/dcase2026_baseline_ae")
SOURCE_DIR = Path("/content/AURIX_data/bearingEmu")

# Get the official baseline code
if not (BASELINE_DIR / ".git").exists():
    subprocess.run(
        [
            "git", "clone",
            "https://github.com/nttcslab/dcase2023_task2_baseline_ae.git",
            str(BASELINE_DIR),
        ],
        check=True,
    )

# Expected DCASE 2026 development-data structure
raw_dir = (
    BASELINE_DIR
    / "data/dcase2026t2/dev_data/raw/bearingEmu"
)

for split in ("train", "test"):
    section_dir = raw_dir / split / "section_00"
    section_dir.mkdir(parents=True, exist_ok=True)

    source_split = SOURCE_DIR / split
    wav_files = sorted(source_split.glob("*.wav"))

    for wav in wav_files:
        link = section_dir / wav.name
        if not link.exists():
            link.symlink_to(wav.resolve())

    print(f"{split}: {len(wav_files)} WAV files linked")

attributes_src = SOURCE_DIR / "attributes_00.csv"
attributes_dst = raw_dir / "attributes_00.csv"

if not attributes_dst.exists():
    attributes_dst.symlink_to(attributes_src.resolve())

print("Training started: NO")
print("Original dataset modified: NO")
print("Prepared path:", raw_dir)

train: 1000 WAV files linked
test: 200 WAV files linked
Training started: NO
Original dataset modified: NO
Prepared path: /content/dcase2026_baseline_ae/data/dcase2026t2/dev_data/raw/bearingEmu

In [42]:
from pathlib import Path
import soundfile as sf

DATA = Path(
    "/content/dcase2026_baseline_ae/data/"
    "dcase2026t2/dev_data/raw/bearingEmu"
)

for split, expected in [("train", 1000), ("test", 200)]:
    folder = DATA / split
    files = sorted(folder.rglob("*.wav"))

    print(f"\n{split.upper()}: {len(files)} WAV files")
    print("Expected:", expected)
    print("Count correct:", len(files) == expected)

    if files:
        audio, sr = sf.read(files[0], always_2d=True)
        print("Sample:", files[0].name)
        print("Sample rate:", sr)
        print("Audio shape:", audio.shape)
        print("Channels:", audio.shape[1])
        print("Duration (seconds):", len(audio) / sr)

TRAIN: 1000 WAV files
Expected: 1000
Count correct: True
Sample: section_00_source_train_normal_0000_noAttribute.wav
Sample rate: 16000
Audio shape: (160000, 2)
Channels: 2
Duration (seconds): 10.0

TEST: 200 WAV files
Expected: 200
Count correct: True
Sample: section_00_source_test_anomaly_0000_noAttribute.wav
Sample rate: 16000
Audio shape: (160000, 2)
Channels: 2
Duration (seconds): 10.0

In [43]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for filename in ["01_train_2026t2.sh", "baseline.yaml"]:
    path = repo / filename
    print(f"\n{'=' * 12} {filename} {'=' * 12}")

    if path.exists():
        print(path.read_text()[:12000])
    else:
        print("File not found:", path)

============ 01_train_2026t2.sh ============
TZ=JST-9 date

echo $0 $*

dev_eval=$1
echo -e "\tdev_eval = '$dev_eval'"
echo

# check args
if [ "${dev_eval}" != "-d" ] \
    && [ "${dev_eval}" != "-e" ] \
    && [ "${dev_eval}" != "--dev" ] \
    && [ "${dev_eval}" != "--eval" ]
then
    echo "$0: argument error"
    echo -e "usage\t: $0 ['-d' | '--dev' | '-e' | '--eval']"
    echo -e "\tinvalid choice '$dev_eval'"
    echo -e "\tchoice from ['-d' | '--dev' | '-e' | '--eval']."
    echo -e "\t\t-d, --dev\t: Using Development dataset. "
    echo -e "\t\t-e, --eval\t: Using Additional training dataset and Evaluation dataset. "
    echo -e "example\t: $ bash $0 -d"
    exit 1
fi

# main process
base_job="bash"
job="train_ae.sh"
mono=False

if [ "${dev_eval}" = "-d" ] || [ "${dev_eval}" = "--dev" ]
then
    dataset_list="\
        DCASE2026T2ToyCar \
        DCASE2026T2ToyCarEmu \
        DCASE2026T2bearingEmu \
        DCASE2026T2fan \
        DCASE2026T2gearboxEmu \
        DCASE2026T2sliderEmu \
        DCASE2026T2valveEmu \
    "
elif [ "${dev_eval}" = "-e" ] || [ "${dev_eval}" = "--eval" ]
then
    dataset_list="\
        DCASE2026T2ToyDrone \
        DCASE2026T2ToothBrush \
        DCASE2026T2SewingMachine \
        DCASE2026T2BlowerDustCollector \
        DCASE2026T2Sander \
    "
fi

for dataset in $dataset_list; do
    ${base_job} ${job} ${dataset} ${dev_eval} ${mono} 0
done


============ baseline.yaml ============
--dataset_directory: ./data
--result_directory: ./results
--export_dir: baseline

--use_cuda: True
--log_interval: 100
--model: DCASE2023T2-AE
--score: MSE
--seed: 13711
--is_auto_download: False

--max_fpr: 0.1
--decision_threshold: 0.9

# feature
--n_mels: 128
--frames: 5
--frame_hop_length: 1
--n_fft: 1024
--hop_length: 512
--power: 2.0
--fmin: 0.0
--fmax: null
--win_length: null

# fit
--batch_size: 256
--epochs: 100
-lr: 0.001
--shuffle: True
--validation_split: 0.1

In [44]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

targets = [
    repo / "train_ae.sh",
    repo / "datasets/dcase_dcase202x_t2_loader.py",
    repo / "networks/dcase2023t2_ae/dcase2023t2_ae.py",
]

keywords = (
    "mono", "soundfile", "wavfile", "librosa.load",
    "sf.read", "channel", "n_mels", "mel_spectrogram",
    "stft", "torch.device", "cuda"
)

for path in targets:
    print(f"\n{'=' * 20}\nFILE: {path.name}\n{'=' * 20}")

    if not path.exists():
        print("File not found")
        continue

    lines = path.read_text(errors="replace").splitlines()
    matches = [
        i for i, line in enumerate(lines)
        if any(word in line.lower() for word in keywords)
    ]

    shown = set()
    for i in matches:
        for j in range(max(0, i - 2), min(len(lines), i + 3)):
            if j not in shown:
                print(f"{j + 1}: {lines[j]}")
                shown.add(j)
        print("---")

====================
FILE: train_ae.sh
====================
3: dataset=$1
4: dev_eval=$2
5: mono=$3
6: id_1=$4
7: id_2=$5
---
27:     --use_ids ${id} \
28:     --train_only \
29:     --mono=${mono} \
---

====================
FILE: dcase_dcase202x_t2_loader.py
====================
19:                 section_ids=[],
20:                 train=True,
21:                 n_mels=128,
22:                 frames=5,
23:                 frame_hop_length=1,
---
32:                 use_id = [],
33:                 is_auto_download=False,
34:                 mono=True,
35:     ):
36:         super().__init__()
---
64:             fmin_max = f"_f{fmin}-{fmax}"
65:         self.log_melspectrogram_dir = os.path.abspath(
66:             "{dir}/mels{n_mels}_fft{n_fft}_hop{hop_length}{fmin_max}".format(
67:                 dir=self.pickle_dir,
68:                 n_mels=n_mels,
---
69:                 n_fft=n_fft,
70:                 hop_length=hop_length,
---
112:             dir_name=dir_name,
113:             train=train,
114:             n_mels=n_mels,
115:             frames=frames,
116:             frame_hop_length=frame_hop_length,
---
121:             fmin=fmin,
122:             win_length=win_length,
123:             mono=mono,
124:         )
125:         if len(self.use_id) > 0:
---
148:             dir_name,
149:             train,
150:             n_mels,
151:             frames,
152:             frame_hop_length,
---
157:             fmin,
158:             win_length,
159:             mono=True,
160:         ):
161:
---
200:             n_files_ea_section = []
201:
202:             self.data = np.empty((0, frames * n_mels), float)
203:             self.y_true = np.empty(0, float)
204:             self.condition = np.empty((0, n_sections), float)
---
220:                 data_ea_section = file_list_to_data(files,
221:                                         msg=f"generate {self.machine_type} section {self.section_ids[section_idx]} {dir_name} dataset",
222:                                         n_mels=n_mels,
223:                                         n_frames=frames,
224:                                         n_hop_frames=frame_hop_length,
---
229:                                         fmin=fmin,
230:                                         win_length=win_length,
231:                                         mono=mono)
232:                 self.data = np.append(self.data, data_ea_section, axis=0)
233:                 if self.mode or train:
---
323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,
326:                         n_frames=5,
327:                         n_hop_frames=1,
---
332:                         fmin=None,
333:                         win_length=None,
334:                         mono=True):
335:     """
336:     convert the file_list to a vector array.
---
348:     """
349:     # calculate the number of dimensions
350:     dims = n_mels * n_frames
351:
352:     # iterate file_to_vector_array()
---
353:     for idx in tqdm(range(len(file_list)), desc=msg):
354:         vectors = com.file_to_vectors(file_list[idx],
355:                                                 n_mels=n_mels,
356:                                                 n_frames=n_frames,
357:                                                 n_fft=n_fft,
---
361:                                                 fmin=fmin,
362:                                                 win_length=win_length,
363:                                                 mono=mono)
364:         vectors = vectors[: : n_hop_frames, :]
365:         if idx == 0:
---

====================
FILE: dcase2023t2_ae.py
====================

In [45]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

targets = {
    "feature extraction": repo / "common.py",
    "audio loader": repo / "datasets/dcase_dcase202x_t2_loader.py",
}

for label, path in targets.items():
    print(f"\n{'=' * 15} {label} {'=' * 15}")

    if not path.exists():
        print("File not found:", path)
        continue

    lines = path.read_text(errors="replace").splitlines()
    terms = ["def file_to_vectors", "def file_to_vector_array",
             "mono", "sf.read", "librosa.load", "mean(axis",
             "channel", "def file_list_to_data"]

    hits = [
        i for i, line in enumerate(lines)
        if any(term in line.lower() for term in terms)
    ]

    shown = set()
    for i in hits:
        for j in range(max(0, i - 3), min(len(lines), i + 9)):
            if j not in shown:
                print(f"{j + 1}: {lines[j]}")
                shown.add(j)
        print("---")

=============== feature extraction ===============
95:                     help='Machine ID to be treated as nml data')
96:     parser.add_argument('--is_auto_download', type=str2bool, default=False,
97:                         help="Download dataset if not exist")
98:     parser.add_argument("--mono", type=str2bool, default=True,
99:                         help="Load input audio as monaural. DCASE2020T2-2025T2 are monaural, DCASE2026T2 is stereo")
100:
101:     # save data
102:     parser.add_argument('--result_directory', type=str, default='results/', metavar='N',
103:                         help='Where to store images')
104:     parser.add_argument('--export_dir',type=str, default='',
105:                         help='Name of the directory to be generated under the Result directory.')
106:     parser.add_argument('-tag','--model_name_suffix',type=str, default='',
---

=============== audio loader ===============
31:                 source_domain="mix",
32:                 use_id = [],
33:                 is_auto_download=False,
34:                 mono=True,
35:     ):
36:         super().__init__()
37:
38:         self.use_id = use_id
39:         self.section_ids = section_ids
40:         self.machine_type = machine_type
41:
42:         target_dir = os.getcwd()+"/"+root+"raw/"+machine_type
---
120:             fmax=fmax,
121:             fmin=fmin,
122:             win_length=win_length,
123:             mono=mono,
124:         )
125:         if len(self.use_id) > 0:
126:             idx_list = [i for i, n in enumerate(np.argmax(self.condition, axis=1)) if int(section_ids[n]) in self.use_id]
127:         else:
128:             idx_list = list(range(len(self.condition)))
129:         idx_list_2 = [i//self.n_vectors_ea_file for i in idx_list[::self.n_vectors_ea_file]]
130:         self.data = self.data[idx_list]
131:         if len(self.y_true) > 0:
---
156:             fmax,
157:             fmin,
158:             win_length,
159:             mono=True,
160:         ):
161:
162:         pickle_lockfile_path = os.path.abspath(f"{self.log_melspectrogram_dir}/{pickle_name}_lockfile")
163:         if os.path.isfile(pickle_path) and not os.path.isfile(pickle_lockfile_path):
164:             print("Setup has already been completed.")
165:             print(f"{pickle_path} is exists.")
166:             self.load_pickle(pickle_path=pickle_path)
167:             return
---
228:                                         fmax=fmax,
229:                                         fmin=fmin,
230:                                         win_length=win_length,
231:                                         mono=mono)
232:                 self.data = np.append(self.data, data_ea_section, axis=0)
233:                 if self.mode or train:
234:                     self.y_true = np.append(self.y_true, y_true, axis=0)
235:                 for i in range(len(data_ea_section) // len(files)):
236:                     self.condition = np.append(self.condition, condition, axis=0)
237:
238:             if is_enabled_dataset_dir_lock:
239:                 com.release_read_lock(
---
320:     def __len__(self):
321:         return self.dataset_len
322:
323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,
326:                         n_frames=5,
327:                         n_hop_frames=1,
328:                         n_fft=1024,
329:                         hop_length=512,
330:                         power=2.0,
331:                         fmax=None,
---
332:                         fmin=None,
333:                         win_length=None,
334:                         mono=True):
335:     """
336:     convert the file_list to a vector array.
337:     file_to_vector_array() is iterated, and the output vector array is concatenated.
338:
339:     file_list : list [ str ]
340:         .wav filename list of dataset
341:     msg : str ( default = "calc..." )
342:         description for tqdm.
---
360:                                                 fmax=fmax,
361:                                                 fmin=fmin,
362:                                                 win_length=win_length,
363:                                                 mono=mono)
364:         vectors = vectors[: : n_hop_frames, :]
365:         if idx == 0:
366:             data = np.zeros((len(file_list) * vectors.shape[0], dims), float)
367:         if len(file_list) * vectors.shape[0] > data.shape[0]:
368:             tmp_data = np.zeros((len(file_list) * vectors.shape[0], dims), float)
369:             tmp_data[:data.shape[0], :] = data
370:             data = tmp_data
371:         data[vectors.shape[0] * idx : vectors.shape[0] * (idx + 1), :] = vectors
---

In [48]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for filename in ["common.py", "utils.py"]:
    path = repo / filename
    if not path.exists():
        continue

    lines = path.read_text(errors="replace").splitlines()
    for i, line in enumerate(lines):
        if "def file_to_vectors" in line or "def file_to_vector_array" in line:
            print(f"\n--- {filename}, line {i+1} ---")
            for j in range(i, min(i + 65, len(lines))):
                print(f"{j+1}: {lines[j]}")

In [49]:
from pathlib import Path
import subprocess

repo = "/content/dcase2026_baseline_ae"

result = subprocess.run(
    [
        "grep", "-R", "-n",
        "-E", "file_to_vectors|file_to_vector_array|librosa\\.load|sf\\.read|soundfile\\.read",
        repo,
        "--include=*.py"
    ],
    capture_output=True,
    text=True
)

print(result.stdout if result.stdout.strip() else "No matching audio-loading code found.")

/content/dcase2026_baseline_ae/tools/plot_common.py:206:    # y, sr = librosa.load(filename, sr=None, mono=False)   # read all
/content/dcase2026_baseline_ae/tools/plot_common.py:207:    y1, sr = librosa.load(filename, sr=None, mono=False, offset=3.0, duration=1.0)   # read for 3 seconds to 1 second
/content/dcase2026_baseline_ae/tools/plot_common.py:208:    y2, sr = librosa.load(filename, sr=None, mono=False, offset=6.5, duration=1.0)   # read for 6.5 seconds to 1 second
/content/dcase2026_baseline_ae/datasets/dcase_dcase202x_t2_loader.py:337:    file_to_vector_array() is iterated, and the output vector array is concatenated.
/content/dcase2026_baseline_ae/datasets/dcase_dcase202x_t2_loader.py:352:    # iterate file_to_vector_array()
/content/dcase2026_baseline_ae/datasets/dcase_dcase202x_t2_loader.py:354:        vectors = com.file_to_vectors(file_list[idx],
/content/dcase2026_baseline_ae/datasets/loader_common.py:111:            return librosa.load(wav_name, sr=None, mono=mono)
/content/dcase2026_baseline_ae/datasets/loader_common.py:113:            y, sr = librosa.load(wav_name, sr=None, mono=mono)
/content/dcase2026_baseline_ae/datasets/loader_common.py:125:def file_to_vectors(file_name,

In [50]:
from pathlib import Path

p = Path(
    "/content/dcase2026_baseline_ae/datasets/loader_common.py"
)

lines = p.read_text(errors="replace").splitlines()

for i in range(95, min(190, len(lines))):
    print(f"{i+1}: {lines[i]}")

96:         target .wav file
97:     mono : boolean
98:         When load a multi channels file and this param True, the returned data will be merged for mono data
99:
100:     return : numpy.array( float )
101:     """
102:     info = sf.info(wav_name)
103:     ch = info.channels
104:     assert any([
105:         mono and ch == 1,
106:         not mono and ch > 1,
107:     ]), f"Channel mismatch: The file is {ch=}, but {mono=} is specified."
108:
109:     try:
110:         if mono:
111:             return librosa.load(wav_name, sr=None, mono=mono)
112:         else:
113:             y, sr = librosa.load(wav_name, sr=None, mono=mono)
114:             return y[0], sr
115:     except:
116:         logger.error("file_broken or not exists!! : {}".format(wav_name))
117:
118:
119: ########################################################################
120:
121:
122: ########################################################################
123: # feature extractor
124: ########################################################################
125: def file_to_vectors(file_name,
126:                     n_mels=64,
127:                     n_frames=5,
128:                     n_fft=1024,
129:                     hop_length=512,
130:                     power=2.0,
131:                     fmax=None,
132:                     fmin=None,
133:                     win_length=None,
134:                     mono=True):
135:     """
136:     convert file_name to a vector array.
137:
138:     file_name : str
139:         target .wav file
140:
141:     return : numpy.array( numpy.array( float ) )
142:         vector array
143:         * dataset.shape = (dataset_size, feature_vector_length)
144:     """
145:     # calculate the number of dimensions
146:     dims = n_mels * n_frames
147:
148:     # generate melspectrogram using librosa
149:     y, sr = file_load(file_name, mono=mono)
150:
151:     mel_spectrogram = librosa.feature.melspectrogram(y=y,
152:                                                         sr=sr,
153:                                                         n_fft=n_fft,
154:                                                         hop_length=hop_length,
155:                                                         n_mels=n_mels,
156:                                                         power=power,
157:                                                         fmax=fmax,
158:                                                         fmin=fmin,
159:                                                         win_length=win_length)
160:
161:     # convert melspectrogram to log mel energies
162:     log_mel_spectrogram = 20.0 / power * np.log10(np.maximum(mel_spectrogram, sys.float_info.epsilon))
163:
164:     # calculate total vector size
165:     n_vectors = log_mel_spectrogram.shape[-1] - n_frames + 1
166:
167:     # skip too short clips
168:     if n_vectors < 1:
169:         return np.empty((0, dims))
170:
171:     # generate feature vectors by concatenating multi frames
172:     vectors = np.zeros((n_vectors, dims))
173:     for t in range(n_frames):
174:         vectors[:, n_mels * t : n_mels * (t + 1)] = log_mel_spectrogram[:, t : t + n_vectors].T
175:
176:     return vectors
177:
178:
179: ########################################################################
180:
181:
182: ########################################################################
183: # get directory paths according to mode
184: ########################################################################
185: def select_dirs(param, mode):
186:     """
187:     param : dict
188:         baseline.yaml data
189:
190:     return :

In [51]:
import sys
import numpy as np
import librosa
import soundfile as sf
from pathlib import Path

wav = next(
    Path("/content/AURIX_data/bearingEmu/train")
    .glob("*.wav")
)

audio, sr = sf.read(wav)

print("File:", wav.name)
print("Sample rate:", sr)
print("Original shape:", audio.shape)
print("Channels:", audio.shape[1] if audio.ndim == 2 else 1)

if audio.ndim == 2 and audio.shape[1] >= 2:
    for ch in range(2):
        mel = librosa.feature.melspectrogram(
            y=audio[:, ch].astype(np.float32),
            sr=sr,
            n_fft=1024,
            hop_length=512,
            n_mels=128,
            power=2.0
        )
        print(
            f"Channel {ch}:",
            f"RMS={np.sqrt(np.mean(audio[:, ch]**2)):.6f}",
            f"Mel shape={mel.shape}",
            f"Finite={np.isfinite(mel).all()}"
        )
else:
    print("ERROR: Expected a stereo audio file.")

File: section_00_source_train_normal_0067_noAttribute.wav
Sample rate: 16000
Original shape: (160000, 2)
Channels: 2
Channel 0: RMS=0.011981 Mel shape=(128, 313) Finite=True
Channel 1: RMS=0.012002 Mel shape=(128, 313) Finite=True

In [52]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for p in [
    repo / "networks/dcase2023t2_ae/dcase2023t2_ae.py",
    repo / "networks/base_model.py",
]:
    print(f"\n{'='*70}\nFILE: {p.name}\n{'='*70}")

    lines = p.read_text(errors="replace").splitlines()

    for i, line in enumerate(lines):
        if any(term in line.lower() for term in [
            "def forward",
            "def train",
            "input_size",
            "n_mels",
            "feature",
            "dataloader",
            "def decision_function",
            "def predict"
        ]):
            start = max(0, i - 3)
            end = min(len(lines), i + 9)
            print(f"\n--- lines {start+1}-{end} ---")
            for j in range(start, end):
                print(f"{j+1}: {lines[j]}")

======================================================================
FILE: dcase2023t2_ae.py
======================================================================

--- lines 41-52 ---
41:         ]
42:         return "loss,val_loss,recon_loss,recon_loss_source,recon_loss_target"
43:
44:     def train(self, epoch):
45:         if epoch <= self.epoch:
46:             return
47:         torch.autograd.set_detect_anomaly(True)
48:         train_loss = 0
49:         train_recon_loss = 0
50:         train_recon_loss_source = 0
51:         train_recon_loss_target = 0
52:         y_pred = []

======================================================================
FILE: base_model.py
======================================================================

--- lines 148-159 ---
148:         # determine threshold for decision
149:         return scipy.stats.gamma.ppf(q=self.args.decision_threshold, a=shape_hat, loc=loc_hat, scale=scale_hat)
150:
151:     def train(self, epoch):
152:         pass
153:
154:     def test(self):
155:         pass
156:
157:     def copy_eval_data_score(self, decision_result_csv_path, anomaly_score_csv_path):
158:         eval_data_decision_result_csv_path = self.eval_data_result_dir / os.path.basename(decision_result_csv_path).replace(self.model_name_suffix, "")
159:         print(f"copy decision result: {decision_result_csv_path}\n\t->{eval_data_decision_result_csv_path}")

In [53]:
from pathlib import Path

p = Path(
    "/content/dcase2026_baseline_ae/networks/dcase2023t2_ae/dcase2023t2_ae.py"
)

lines = p.read_text(errors="replace").splitlines()

for i in range(min(150, len(lines))):
    print(f"{i+1}: {lines[i]}")

1: import os
2: import sys
3: import torch
4: from torch import optim
5: import torch.nn.functional as F
6: import numpy as np
7: import scipy
8: from sklearn import metrics
9: import csv
10: from tqdm import tqdm
11:
12: from networks.base_model import BaseModel
13: from networks.dcase2023t2_ae.network import AENet
14: from networks.criterion.mahala import cov_v, loss_function_mahala, calc_inv_cov
15: from tools.plot_anm_score import AnmScoreFigData
16: from tools.plot_loss_curve import csv_to_figdata
17:
18: class DCASE2023T2AE(BaseModel):
19:     def __init__(self, args, train, test):
20:         super().__init__(
21:             args=args,
22:             train=train,
23:             test=test
24:         )
25:         parameter_list = [{"params":self.model.parameters()}]
26:         self.optimizer = optim.Adam(parameter_list, lr=self.args.learning_rate)
27:         self.mse_score_distr_file_path = self.model_dir/f"score_distr_{self.args.model}_{self.args.dataset}{self.model_name_suffix}{self.eval_suffix}_seed{self.args.seed}_mse.pickle"
28:         self.mahala_score_distr_file_path = self.model_dir/f"score_distr_{self.args.model}_{self.args.dataset}{self.model_name_suffix}{self.eval_suffix}_seed{self.args.seed}_mahala.pickle"
29:
30:
31:     def init_model(self):
32:         self.block_size = self.data.height
33:         return AENet(input_dim=self.data.input_dim, block_size=self.block_size)
34:
35:     def get_log_header(self):
36:         self.column_heading_list=[
37:                 ["loss"],
38:                 ["val_loss"],
39:                 ["recon_loss"],
40:                 ["recon_loss_source", "recon_loss_target"],
41:         ]
42:         return "loss,val_loss,recon_loss,recon_loss_source,recon_loss_target"
43:
44:     def train(self, epoch):
45:         if epoch <= self.epoch:
46:             return
47:         torch.autograd.set_detect_anomaly(True)
48:         train_loss = 0
49:         train_recon_loss = 0
50:         train_recon_loss_source = 0
51:         train_recon_loss_target = 0
52:         y_pred = []
53:
54:         train_loader = self.train_loader
55:
56:         if epoch == self.args.epochs + 1:
57:             print("\n============== CALCULATE COVARIANCE ==============")
58:             is_calc_cov = True
59:             self.model.eval()
60:             torch.set_grad_enabled(False)
61:             # initialize mahalanobis param
62:             cov_x_source = np.zeros((self.block_size, self.block_size))
63:             cov_x_source = torch.from_numpy(cov_x_source)
64:             cov_x_source = cov_x_source.to(self.device).float()
65:             cov_x_target = cov_x_source.clone().detach()
66:             num_source = 0
67:             num_target = 0
68:             epoch = self.args.epochs
69:         else:
70:             self.model.train()
71:             is_calc_cov = False
72:
73:         for batch_idx, batch in enumerate(tqdm(train_loader)):
74:             data = batch[0]
75:             data = data.to(self.device).float()
76:             if data.shape[0] <= 1:
77:                 continue
78:             data_name_list = batch[3]
79:             machine_id = torch.argmax(batch[2], dim=1).long()
80:             machine_id = machine_id.to(self.device)
81:
82:             is_target_list = ["target" in data_name for data_name in data_name_list]
83:             is_source_list = np.logical_not(is_target_list).tolist()
84:             n_source = is_source_list.count(True)
85:             n_target = is_target_list.count(True)
86:
87:             if not is_calc_cov:
88:                 self.optimizer.zero_grad()
89:             recon_batch, z = self.model(data)
90:
91:             if is_calc_cov:
92:                 score_2d, cov_diff_source, cov_diff_target = loss_function_mahala(
93:                     recon_x=recon_batch,
94:                     x=data,
95:                     block_size=self.block_size,
96:                     update_cov=True,
97:                     reduction=False,
98:                     is_source_list=is_source_list,
99:                     is_target_list=is_target_list
100:                 )
101:                 cov_x_source_batch = cov_v(
102:                     diff=cov_diff_source,
103:                     num=1
104:                 )
105:                 cov_x_source += cov_x_source_batch.clone().detach()
106:                 num_source += n_source
107:                 if n_target > 0:
108:                     cov_x_target_batch = cov_v(
109:                         diff=cov_diff_target,
110:                         num=1
111:                     )
112:                     cov_x_target += cov_x_target_batch.clone().detach()
113:                     num_target += n_target
114:             else:
115:                 score_2d = self.loss_fn(
116:                     recon_batch,
117:                     data
118:                 )
119:
120:             # loss reduction
121:             n_loss = len(score_2d)
122:             score = self.loss_reduction_1d(score=score_2d)
123:
124:             recon_loss = self.loss_reduction(score=score, n_loss=n_loss)
125:             recon_loss_source = self.loss_reduction(score=score[is_source_list], n_loss=n_source)
126:             if n_target > 0:
127:                 recon_loss_target = self.loss_reduction(score=score[is_target_list], n_loss=n_target)
128:             else:
129:                 recon_loss_target = 0
130:
131:             self.loss = recon_loss
132:             if not is_calc_cov:
133:                 self.loss.backward()
134:                 self.optimizer.step()
135:             train_loss += float(self.loss)
136:             train_recon_loss += float(recon_loss)
137:             train_recon_loss_source += float(recon_loss_source)
138:             train_recon_loss_target += float(recon_loss_target)
139:
140:
141:             # calculate y_pred for fitting anomaly score distribution
142:             y_pred.append(self.loss.item())
143:
144:             if batch_idx % self.args.log_interval == 0 and not is_calc_cov:
145:                 print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
146:                     epoch, batch_idx * len(data), len(train_loader.dataset),
147:                     100. * batch_idx / len(train_loader),
148:                     self.loss.item()))
149:
150:         if is_calc_cov:

In [54]:
from pathlib import Path

p = Path(
    "/content/dcase2026_baseline_ae/networks/dcase2023t2_ae/network.py"
)

lines = p.read_text(errors="replace").splitlines()

for i, line in enumerate(lines):
    print(f"{i+1}: {line}")

1: import torch
2: from torch import nn
3:
4: class AENet(nn.Module):
5:     def __init__(self,input_dim, block_size):
6:         super(AENet,self).__init__()
7:         self.input_dim = input_dim
8:         self.cov_source = nn.Parameter(torch.zeros(block_size, block_size), requires_grad=False)
9:         self.cov_target = nn.Parameter(torch.zeros(block_size, block_size), requires_grad=False)
10:
11:         self.encoder = nn.Sequential(
12:             nn.Linear(self.input_dim,128),
13:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
14:             nn.ReLU(),
15:             nn.Linear(128,128),
16:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
17:             nn.ReLU(),
18:             nn.Linear(128,128),
19:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
20:             nn.ReLU(),
21:             nn.Linear(128,128),
22:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
23:             nn.ReLU(),
24:             nn.Linear(128,8),
25:             nn.BatchNorm1d(8,momentum=0.01, eps=1e-03),
26:             nn.ReLU(),
27:         )
28:
29:         self.decoder = nn.Sequential(
30:             nn.Linear(8,128),
31:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
32:             nn.ReLU(),
33:             nn.Linear(128,128),
34:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
35:             nn.ReLU(),
36:             nn.Linear(128,128),
37:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
38:             nn.ReLU(),
39:             nn.Linear(128,128),
40:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
41:             nn.ReLU(),
42:             nn.Linear(128,self.input_dim)
43:         )
44:
45:     def forward(self, x):
46:         z = self.encoder(x.view(-1,self.input_dim))
47:         return self.decoder(z), z

In [55]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for rel in [
    "datasets/dcase_dcase202x_t2_loader.py",
    "networks/base_model.py",
]:
    p = repo / rel
    lines = p.read_text(errors="replace").splitlines()

    print(f"\n{'='*65}\n{rel}\n{'='*65}")

    terms = [
        "input_dim", "height", "validation_split",
        "train_loader", "val_loader", "DataLoader",
        "self.data", "def __init__"
    ]

    shown = set()
    for i, line in enumerate(lines):
        if any(term in line for term in terms):
            start = max(0, i - 2)
            end = min(len(lines), i + 5)
            if any(j in shown for j in range(start, end)):
                continue
            shown.update(range(start, end))
            print(f"\n--- lines {start+1}-{end} ---")
            for j in range(start, end):
                print(f"{j+1}: {lines[j]}")

=================================================================
datasets/dcase_dcase202x_t2_loader.py
=================================================================

--- lines 12-18 ---
12:
13: class DCASE202XT2Loader(torch.utils.data.Dataset):
14:     def __init__(self,
15:                 root:str,
16:                 dataset_name,
17:                 section_keyword,
18:                 machine_type:str="ToyCar",

--- lines 128-134 ---
128:             idx_list = list(range(len(self.condition)))
129:         idx_list_2 = [i//self.n_vectors_ea_file for i in idx_list[::self.n_vectors_ea_file]]
130:         self.data = self.data[idx_list]
131:         if len(self.y_true) > 0:
132:             self.y_true = self.y_true[idx_list_2]
133:         self.condition = self.condition[idx_list]
134:         self.basenames = [self.basenames[i] for i in idx_list_2]

--- lines 135-141 ---
135:
136:         # getitem method setting
137:         self.frame_idx_list = list(range(len(self.data)))
138:         self.dataset_len = len(self.frame_idx_list)
139:         self.getitem_fn = self.default_item
140:
141:     def load_pre_process(

--- lines 200-206 ---
200:             n_files_ea_section = []
201:
202:             self.data = np.empty((0, frames * n_mels), float)
203:             self.y_true = np.empty(0, float)
204:             self.condition = np.empty((0, n_sections), float)
205:             self.basenames = []
206:             for section_idx, section_name in enumerate(unique_section_names):

--- lines 230-236 ---
230:                                         win_length=win_length,
231:                                         mono=mono)
232:                 self.data = np.append(self.data, data_ea_section, axis=0)
233:                 if self.mode or train:
234:                     self.y_true = np.append(self.y_true, y_true, axis=0)
235:                 for i in range(len(data_ea_section) // len(files)):
236:                     self.condition = np.append(self.condition, condition, axis=0)

--- lines 245-251 ---
245:             n_all_files = sum(n_files_ea_section)
246:             # number of vectors for each wave file
247:             self.n_vectors_ea_file = int(self.data.shape[0] / n_all_files)
248:
249:             # save dataset to pickle
250:             with open(pickle_path, 'wb') as f:
251:                 pickle.dump((

--- lines 286-292 ---
286:         try:
287:             with open(pickle_path, 'rb') as f:
288:                 self.data, self.y_true, self.condition, self.n_vectors_ea_file, self.basenames = pickle.load(f)
289:         except FileNotFoundError:
290:             print(f"{datetime.datetime.now()}\tFileNotFoundError: can not load pickle.")
291:             time.sleep(retry_delay_time)
292:             print(f"retry load pickle : {retry_count+1}/{retry_lim}")

--- lines 312-318 ---
312:
313:     def default_item(self, index):
314:         data = self.data[index]
315:         y_true = self.y_true[index//self.n_vectors_ea_file] if len(self.y_true) > 0 else -1
316:         condition = self.condition[index]
317:         basename = self.basenames[index//self.n_vectors_ea_file]
318:         return data, y_true, condition, basename, index

--- lines 319-325 ---
319:
320:     def __len__(self):
321:         return self.dataset_len
322:
323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,

=================================================================
networks/base_model.py
=================================================================

--- lines 14-20 ---
14:
15: class BaseModel(object):
16:     def __init__(self, args, train, test):
17:         self.args = args
18:         print("selected gpu id:{}".format(args.gpu_id))
19:         self.device = torch.device("cuda" if args.cuda else "cpu",args.gpu_id[0])
20:         print(self.device)

--- lines 25-31 ---
25:             print("please set another name \n{}".format(Datasets.show_list()))
26:             raise e
27:         self.train_loader = self.data.train_loader
28:         self.valid_loader = self.data.valid_loader
29:         self.test_loader = self.data.test_loader
30:
31:         self.epoch = 0

--- lines 97-103 ---
97:             frames=args.frames,
98:             frame_hop_length=args.frame_hop_length,
99:             shape=(self.data.channel, self.data.width, self.data.height)
100:         )
101:
102:         self.result_column_dict = {
103:             "single_domain":["section", "AUC", "pAUC", "precision", "recall", "F1 score"],

In [56]:
from pathlib import Path
import yaml
import torch

repo = Path("/content/dcase2026_baseline_ae")

print("=== CPU device check ===")
try:
    device = torch.device("cpu", 0)
    print("torch.device('cpu', 0):", device)
except Exception as e:
    print("CPU device error:", repr(e))

print("\n=== Baseline configuration ===")
for p in repo.rglob("baseline.yaml"):
    if "results" not in p.parts:
        print("Config:", p)
        try:
            cfg = yaml.safe_load(p.read_text())
            for key in [
                "--use_cuda", "--n_mels", "--frames",
                "--batch_size", "--epochs", "--validation_split",
                "--seed", "--mono"
            ]:
                if key in cfg:
                    print(f"{key}: {cfg[key]}")
        except Exception as e:
            print("Could not read config:", repr(e))

print("\n=== Existing feature caches ===")
for folder in [
    repo / "data",
    Path("/content/AURIX_data/bearingEmu")
]:
    if folder.exists():
        caches = [
            p for p in folder.rglob("*")
            if p.is_file() and p.suffix.lower() in {".pickle", ".pkl"}
        ]
        print(f"{folder}: {len(caches)} pickle/cache files")
        for p in caches[:10]:
            print(" ", p)

=== CPU device check ===
torch.device('cpu', 0): cpu:0

=== Baseline configuration ===
Config: /content/dcase2026_baseline_ae/baseline.yaml
--use_cuda: True
--n_mels: 128
--frames: 5
--batch_size: 256
--epochs: 100
--validation_split: 0.1
--seed: 13711

=== Existing feature caches ===
/content/dcase2026_baseline_ae/data: 0 pickle/cache files
/content/AURIX_data/bearingEmu: 0 pickle/cache files

In [57]:
import torch
from torch import nn

torch.manual_seed(13711)
device = torch.device("cpu")

model = nn.Sequential(
    nn.Linear(640, 128),
    nn.ReLU(),
    nn.Linear(128, 8),
    nn.ReLU(),
    nn.Linear(8, 640)
).to(device)

x = torch.randn(4, 640, device=device)

model.eval()
with torch.no_grad():
    reconstructed = model(x)

print("Device:", next(model.parameters()).device)
print("Input shape:", tuple(x.shape))
print("Output shape:", tuple(reconstructed.shape))
print("Finite output:", bool(torch.isfinite(reconstructed).all()))
print("CPU smoke test: PASS")

Device: cpu
Input shape: (4, 640)
Output shape: (4, 640)
Finite output: True
CPU smoke test: PASS

In [58]:
from pathlib import Path
import numpy as np
import librosa
import soundfile as sf

wav = Path(
    "/content/AURIX_data/bearingEmu/train/"
    "section_00_source_train_normal_0067_noAttribute.wav"
)

audio, sr = sf.read(wav, dtype="float32")

assert audio.ndim == 2 and audio.shape[1] == 2
assert sr == 16000

def extract_logmel(signal):
    mel = librosa.feature.melspectrogram(
        y=signal,
        sr=sr,
        n_fft=1024,
        hop_length=512,
        n_mels=128,
        power=2.0
    )
    return 10.0 * np.log10(np.maximum(mel, 1e-10))

mel0 = extract_logmel(audio[:, 0])
mel1 = extract_logmel(audio[:, 1])

# Concatenate channel features at each time frame.
fused = np.concatenate([mel0, mel1], axis=0)

print("File:", wav.name)
print("Channel 0 log-Mel:", mel0.shape)
print("Channel 1 log-Mel:", mel1.shape)
print("Early-fusion log-Mel:", fused.shape)
print("All finite:", all(
    np.isfinite(a).all() for a in (mel0, mel1, fused)
))
print("Fusion feature check: PASS")

File: section_00_source_train_normal_0067_noAttribute.wav
Channel 0 log-Mel: (128, 313)
Channel 1 log-Mel: (128, 313)
Early-fusion log-Mel: (256, 313)
All finite: True
Fusion feature check: PASS

In [59]:

from pathlib import Path
import pandas as pd

DATA_ROOT = Path("/content/AURIX_data/bearingEmu")
records = []

for split in ("train", "test"):
    folder = DATA_ROOT / split
    files = sorted(folder.glob("*.wav"))

    assert files, f"No WAV files found in {folder}"

    for file in files:
        name = file.name.lower()
        domain = "source" if "_source_" in name else (
            "target" if "_target_" in name else "unknown"
        )
        label = "normal" if "_normal_" in name else (
            "anomaly" if "_anomaly_" in name else "unknown"
        )

        records.append({
            "filename": file.name,
            "split": split,
            "domain": domain,
            "label": label,
            "path": str(file)
        })

manifest = pd.DataFrame(records)

print("Total WAV files:", len(manifest))
print("\nCounts by split, domain, and label:")
print(
    manifest.groupby(["split", "domain", "label"])
    .size()
    .to_string()
)

unknown = manifest[
    (manifest["domain"] == "unknown") |
    (manifest["label"] == "unknown")
]

print("\nUnrecognized filenames:", len(unknown))
assert len(unknown) == 0, (
    "Some filenames could not be classified. Inspect them before proceeding."
)

train = manifest[manifest["split"] == "train"]
test = manifest[manifest["split"] == "test"]

assert (train["label"] == "normal").all(), (
    "Unexpected non-normal training files; inspect before training."
)
assert len(train) == 1000 and len(test) == 200, (
    "Unexpected dataset size; investigate before training."
)

print("\nManifest validation: PASS")

Total WAV files: 1200

Counts by split, domain, and label:
split  domain  label
test   source  anomaly     50
               normal      50
       target  anomaly     50
               normal      50
train  source  normal     990
       target  normal      10

Unrecognized filenames: 0

Manifest validation: PASS

In [60]:

from pathlib import Path
from hashlib import sha256
from collections import defaultdict

root = Path("/content/AURIX_data/bearingEmu")
hashes_by_split = {"train": defaultdict(list), "test": defaultdict(list)}

for split in ("train", "test"):
    files = sorted((root / split).glob("*.wav"))

    for i, file in enumerate(files, start=1):
        digest = sha256(file.read_bytes()).hexdigest()
        hashes_by_split[split][digest].append(file.name)

    print(f"{split}: hashed {len(files)} WAV files")

train_hashes = set(hashes_by_split["train"])
test_hashes = set(hashes_by_split["test"])
overlap = train_hashes & test_hashes

print("\nExact-content hashes shared across train/test:", len(overlap))

if overlap:
    for digest in sorted(overlap):
        print("Matching files:")
        print("  train:", hashes_by_split["train"][digest])
        print("  test: ", hashes_by_split["test"][digest])
else:
    print("Exact-duplicate check: PASS")

train: hashed 1000 WAV files
test: hashed 200 WAV files

Exact-content hashes shared across train/test: 0
Exact-duplicate check: PASS

In [61]:

from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")
loader = repo / "datasets" / "loader_common.py"
dataset_loader = repo / "datasets" / "dcase_dcase202x_t2_loader.py"

for path in (loader, dataset_loader):
    print(f"\n{'=' * 18} {path.name} {'=' * 18}")

    if not path.exists():
        print("FILE NOT FOUND:", path)
        continue

    lines = path.read_text(encoding="utf-8").splitlines()

    terms = (
        "def file_load",
        "def file_to_vectors",
        "pickle_path",
        "pickle_lockfile_path",
        "mono=mono",
        "def __init__",
    )

    hits = [
        i for i, line in enumerate(lines)
        if any(term in line for term in terms)
    ]

    shown = set()
    for i in hits:
        start, end = max(0, i - 3), min(len(lines), i + 7)
        if any(j in shown for j in range(start, end)):
            continue
        print(f"\n--- lines {start + 1}-{end} ---")
        for j in range(start, end):
            print(f"{j + 1}: {lines[j]}")
            shown.add(j)

================== loader_common.py ==================

--- lines 88-97 ---
88: # file I/O
89: ########################################################################
90: # wav file input
91: def file_load(wav_name, mono=False):
92:     """
93:     load .wav file.
94:
95:     wav_name : str
96:         target .wav file
97:     mono : boolean

--- lines 108-117 ---
108:
109:     try:
110:         if mono:
111:             return librosa.load(wav_name, sr=None, mono=mono)
112:         else:
113:             y, sr = librosa.load(wav_name, sr=None, mono=mono)
114:             return y[0], sr
115:     except:
116:         logger.error("file_broken or not exists!! : {}".format(wav_name))
117:

--- lines 122-131 ---
122: ########################################################################
123: # feature extractor
124: ########################################################################
125: def file_to_vectors(file_name,
126:                     n_mels=64,
127:                     n_frames=5,
128:                     n_fft=1024,
129:                     hop_length=512,
130:                     power=2.0,
131:                     fmax=None,

--- lines 146-155 ---
146:     dims = n_mels * n_frames
147:
148:     # generate melspectrogram using librosa
149:     y, sr = file_load(file_name, mono=mono)
150:
151:     mel_spectrogram = librosa.feature.melspectrogram(y=y,
152:                                                         sr=sr,
153:                                                         n_fft=n_fft,
154:                                                         hop_length=hop_length,
155:                                                         n_mels=n_mels,

--- lines 472-481 ---
472:         except OSError:
473:             print(f"can not remove {lock_file_path}")
474:
475: def is_enabled_pickle(pickle_path):
476:     opcodes = []
477:     with open(pickle_path, "rb") as f:
478:         pickle = f.read()
479:         output = pickletools.genops(pickle=pickle)
480:         for opcode in output:
481:             opcodes.append(opcode[0])

================== dcase_dcase202x_t2_loader.py ==================

--- lines 11-20 ---
11: from datasets import loader_common as com
12:
13: class DCASE202XT2Loader(torch.utils.data.Dataset):
14:     def __init__(self,
15:                 root:str,
16:                 dataset_name,
17:                 section_keyword,
18:                 machine_type:str="ToyCar",
19:                 section_ids=[],
20:                 train=True,

--- lines 101-110 ---
101:         for section_id in section_ids:
102:             pickle_name = f"{pickle_name}_{section_id}"
103:         pickle_name = f"{pickle_name}_{source_domain}_TF{frames}-{frame_hop_length}_mel{n_fft}-{hop_length}"
104:         pickle_path = os.path.abspath(f"{self.log_melspectrogram_dir}/{pickle_name}.pickle")
105:
106:         self.load_pre_process(
107:             pickle_name=pickle_name,
108:             target_dir=target_dir,
109:             pickle_path=pickle_path,
110:             n_sections=n_sections,

--- lines 120-129 ---
120:             fmax=fmax,
121:             fmin=fmin,
122:             win_length=win_length,
123:             mono=mono,
124:         )
125:         if len(self.use_id) > 0:
126:             idx_list = [i for i, n in enumerate(np.argmax(self.condition, axis=1)) if int(section_ids[n]) in self.use_id]
127:         else:
128:             idx_list = list(range(len(self.condition)))
129:         idx_list_2 = [i//self.n_vectors_ea_file for i in idx_list[::self.n_vectors_ea_file]]

--- lines 142-151 ---
142:             self,
143:             pickle_name,
144:             target_dir,
145:             pickle_path,
146:             n_sections,
147:             unique_section_names,
148:             dir_name,
149:             train,
150:             n_mels,
151:             frames,

--- lines 159-168 ---
159:             mono=True,
160:         ):
161:
162:         pickle_lockfile_path = os.path.abspath(f"{self.log_melspectrogram_dir}/{pickle_name}_lockfile")
163:         if os.path.isfile(pickle_path) and not os.path.isfile(pickle_lockfile_path):
164:             print("Setup has already been completed.")
165:             print(f"{pickle_path} is exists.")
166:             self.load_pickle(pickle_path=pickle_path)
167:             return
168:         else:

--- lines 174-183 ---
174:             try:
175:                 pickle_lock.acquire_write_lock()
176:             except:
177:                 print(f"{datetime.datetime.now()}\tcan not lock {pickle_lockfile_path}.")
178:                 print(f"{pickle_path} is exists.")
179:                 self.load_pickle(pickle_path=pickle_path)
180:                 return
181:
182:             if os.path.exists(pickle_path):
183:                 print(f"{pickle_path} is exists.")

--- lines 185-194 ---
185:                     lock=pickle_lock,
186:                     lock_file_path=pickle_lockfile_path
187:                 )
188:                 self.load_pickle(pickle_path=pickle_path)
189:                 return
190:
191:             if is_enabled_dataset_dir_lock:
192:                 try:
193:                     dataset_dir_lock.acquire_read_lock()
194:                 except:

--- lines 228-237 ---
228:                                         fmax=fmax,
229:                                         fmin=fmin,
230:                                         win_length=win_length,
231:                                         mono=mono)
232:                 self.data = np.append(self.data, data_ea_section, axis=0)
233:                 if self.mode or train:
234:                     self.y_true = np.append(self.y_true, y_true, axis=0)
235:                 for i in range(len(data_ea_section) // len(files)):
236:                     self.condition = np.append(self.condition, condition, axis=0)
237:

--- lines 247-256 ---
247:             self.n_vectors_ea_file = int(self.data.shape[0] / n_all_files)
248:
249:             # save dataset to pickle
250:             with open(pickle_path, 'wb') as f:
251:                 pickle.dump((
252:                     self.data,
253:                     self.y_true,
254:                     self.condition,
255:                     self.n_vectors_ea_file,
256:                     self.basenames

--- lines 257-266 ---
257:                 ), f, protocol=pickle.HIGHEST_PROTOCOL)
258:
259:             count = 0
260:             while not com.is_enabled_pickle(pickle_path=pickle_path):
261:                 assert count < 10
262:                 print(f"{datetime.datetime.now()}\tpickle is not ready yet.")
263:                 time.sleep(count+1)
264:                 count+=1
265:                 print(f"retry check pickle.\ncount : {count}")
266:

--- lines 269-278 ---
269:                 lock_file_path=pickle_lockfile_path,
270:             )
271:
272:     def load_pickle(self, pickle_path, pickle_lock=None, pickle_lock_file=None, retry_count=0, retry_lim=20, retry_delay_time=1):
273:         assert retry_count < retry_lim
274:         if pickle_lock:
275:             try:
276:                 print("wait setting dataset")
277:                 pickle_lock.acquire_read_lock()
278:             except:

--- lines 282-291 ---
282:                 lock=pickle_lock,
283:                 lock_file_path=pickle_lock_file,
284:             )
285:         print(f"load pickle : {pickle_path}")
286:         try:
287:             with open(pickle_path, 'rb') as f:
288:                 self.data, self.y_true, self.condition, self.n_vectors_ea_file, self.basenames = pickle.load(f)
289:         except FileNotFoundError:
290:             print(f"{datetime.datetime.now()}\tFileNotFoundError: can not load pickle.")
291:             time.sleep(retry_delay_time)

--- lines 360-369 ---
360:                                                 fmax=fmax,
361:                                                 fmin=fmin,
362:                                                 win_length=win_length,
363:                                                 mono=mono)
364:         vectors = vectors[: : n_hop_frames, :]
365:         if idx == 0:
366:             data = np.zeros((len(file_list) * vectors.shape[0], dims), float)
367:         if len(file_list) * vectors.shape[0] > data.shape[0]:
368:             tmp_data = np.zeros((len(file_list) * vectors.shape[0], dims), float)
369:             tmp_data[:data.shape[0], :] = data

In [62]:

from pathlib import Path
import numpy as np
import librosa
import soundfile as sf

wav = Path(
    "/content/AURIX_data/bearingEmu/train/"
    "section_00_source_train_normal_0067_noAttribute.wav"
)

audio, sr = sf.read(wav, dtype="float32")
assert audio.ndim == 2 and audio.shape[1] == 2
assert sr == 16000

def logmel(signal):
    mel = librosa.feature.melspectrogram(
        y=signal,
        sr=sr,
        n_fft=1024,
        hop_length=512,
        n_mels=128,
        power=2.0,
    )
    return 10.0 * np.log10(np.maximum(mel, 1e-10)).T

def make_vectors(features, frames=5):
    # features: time × frequency
    if len(features) < frames:
        raise ValueError("Not enough frames")
    windows = np.stack(
        [features[i:i + frames].reshape(-1)
         for i in range(len(features) - frames + 1)]
    )
    return windows

m0 = logmel(audio[:, 0])
m1 = logmel(audio[:, 1])

# Same preprocessing per channel; early fusion joins features per frame.
v0 = make_vectors(m0)
v1 = make_vectors(m1)
vf = make_vectors(np.concatenate([m0, m1], axis=1))

for name, vectors in [
    ("Channel 0", v0),
    ("Channel 1", v1),
    ("Early fusion", vf),
]:
    print(
        f"{name}: shape={vectors.shape}, "
        f"finite={np.isfinite(vectors).all()}"
    )

assert v0.shape[1] == 640
assert v1.shape[1] == 640
assert vf.shape[1] == 1280
assert all(np.isfinite(v).all() for v in (v0, v1, vf))

print("\nFrame-stacking check: PASS")

Channel 0: shape=(309, 640), finite=True
Channel 1: shape=(309, 640), finite=True
Early fusion: shape=(309, 1280), finite=True

Frame-stacking check: PASS

In [63]:

from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")
files_to_check = [
    repo / "datasets" / "dcase_dcase202x_t2_loader.py",
    repo / "networks" / "base_model.py",
    repo / "networks" / "dcase2023t2_ae" / "dcase2023t2_ae.py",
    repo / "networks" / "dcase2023t2_ae" / "network.py",
]

terms = (
    "input_dim",
    "self.data",
    "self.model =",
    "AENet(",
    "def init_model",
    "def forward",
    "def file_to_vectors",
)

for path in files_to_check:
    print(f"\n{'=' * 16} {path.relative_to(repo)} {'=' * 16}")

    lines = path.read_text(encoding="utf-8").splitlines()
    hits = [
        i for i, line in enumerate(lines)
        if any(term in line for term in terms)
    ]

    shown = set()
    for i in hits:
        start, end = max(0, i - 2), min(len(lines), i + 5)
        if any(j in shown for j in range(start, end)):
            continue

        print(f"\n--- lines {start + 1}-{end} ---")
        for j in range(start, end):
            print(f"{j + 1}: {lines[j]}")
            shown.add(j)

================ datasets/dcase_dcase202x_t2_loader.py ================

--- lines 128-134 ---
128:             idx_list = list(range(len(self.condition)))
129:         idx_list_2 = [i//self.n_vectors_ea_file for i in idx_list[::self.n_vectors_ea_file]]
130:         self.data = self.data[idx_list]
131:         if len(self.y_true) > 0:
132:             self.y_true = self.y_true[idx_list_2]
133:         self.condition = self.condition[idx_list]
134:         self.basenames = [self.basenames[i] for i in idx_list_2]

--- lines 135-141 ---
135:
136:         # getitem method setting
137:         self.frame_idx_list = list(range(len(self.data)))
138:         self.dataset_len = len(self.frame_idx_list)
139:         self.getitem_fn = self.default_item
140:
141:     def load_pre_process(

--- lines 200-206 ---
200:             n_files_ea_section = []
201:
202:             self.data = np.empty((0, frames * n_mels), float)
203:             self.y_true = np.empty(0, float)
204:             self.condition = np.empty((0, n_sections), float)
205:             self.basenames = []
206:             for section_idx, section_name in enumerate(unique_section_names):

--- lines 230-236 ---
230:                                         win_length=win_length,
231:                                         mono=mono)
232:                 self.data = np.append(self.data, data_ea_section, axis=0)
233:                 if self.mode or train:
234:                     self.y_true = np.append(self.y_true, y_true, axis=0)
235:                 for i in range(len(data_ea_section) // len(files)):
236:                     self.condition = np.append(self.condition, condition, axis=0)

--- lines 245-251 ---
245:             n_all_files = sum(n_files_ea_section)
246:             # number of vectors for each wave file
247:             self.n_vectors_ea_file = int(self.data.shape[0] / n_all_files)
248:
249:             # save dataset to pickle
250:             with open(pickle_path, 'wb') as f:
251:                 pickle.dump((

--- lines 286-292 ---
286:         try:
287:             with open(pickle_path, 'rb') as f:
288:                 self.data, self.y_true, self.condition, self.n_vectors_ea_file, self.basenames = pickle.load(f)
289:         except FileNotFoundError:
290:             print(f"{datetime.datetime.now()}\tFileNotFoundError: can not load pickle.")
291:             time.sleep(retry_delay_time)
292:             print(f"retry load pickle : {retry_count+1}/{retry_lim}")

--- lines 312-318 ---
312:
313:     def default_item(self, index):
314:         data = self.data[index]
315:         y_true = self.y_true[index//self.n_vectors_ea_file] if len(self.y_true) > 0 else -1
316:         condition = self.condition[index]
317:         basename = self.basenames[index//self.n_vectors_ea_file]
318:         return data, y_true, condition, basename, index

--- lines 319-325 ---
319:
320:     def __len__(self):
321:         return self.dataset_len
322:
323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,

================ networks/base_model.py ================

--- lines 20-26 ---
20:         print(self.device)
21:         try:
22:             self.data = Datasets(self.args.dataset).data(self.args)
23:         except Exception as e:
24:             print('dataset "{}" is not supported'.format(self.args.dataset))
25:             print("please set another name \n{}".format(Datasets.show_list()))
26:             raise e

--- lines 27-33 ---
27:         self.train_loader = self.data.train_loader
28:         self.valid_loader = self.data.valid_loader
29:         self.test_loader = self.data.test_loader
30:
31:         self.epoch = 0
32:         self.model = self.init_model()
33:

--- lines 97-103 ---
97:             frames=args.frames,
98:             frame_hop_length=args.frame_hop_length,
99:             shape=(self.data.channel, self.data.width, self.data.height)
100:         )
101:
102:         self.result_column_dict = {
103:             "single_domain":["section", "AUC", "pAUC", "precision", "recall", "F1 score"],

--- lines 114-120 ---
114:         tf.close()
115:
116:     def init_model(self):
117:         pass
118:
119:     def get_log_header(self):
120:         return "loss,loss_var,time"

================ networks/dcase2023t2_ae/dcase2023t2_ae.py ================

--- lines 29-35 ---
29:
30:
31:     def init_model(self):
32:         self.block_size = self.data.height
33:         return AENet(input_dim=self.data.input_dim, block_size=self.block_size)
34:
35:     def get_log_header(self):

--- lines 278-284 ---
278:         # "development": mode == True
279:         # "evaluation": mode == False
280:         mode = self.data.mode
281:
282:         # initialize lines in csv for AUC and pAUC
283:         csv_lines = []
284:

--- lines 306-312 ---
306:         )
307:         for idx, test_loader_tmp in enumerate(self.test_loader):
308:             section_name = f"section_{self.data.section_id_list[idx]}"
309:             result_dir = self.result_dir if self.args.dev else self.eval_data_result_dir
310:
311:             # setup anomaly score file path
312:             anomaly_score_csv = result_dir/f"anomaly_score_{self.args.dataset}_{section_name}_{dir_name}_seed{self.args.seed}{self.model_name_suffix}{self.eval_suffix}.csv"

================ networks/dcase2023t2_ae/network.py ================

--- lines 2-8 ---
2: from torch import nn
3:
4: class AENet(nn.Module):
5:     def __init__(self,input_dim, block_size):
6:         super(AENet,self).__init__()
7:         self.input_dim = input_dim
8:         self.cov_source = nn.Parameter(torch.zeros(block_size, block_size), requires_grad=False)

--- lines 10-16 ---
10:
11:         self.encoder = nn.Sequential(
12:             nn.Linear(self.input_dim,128),
13:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
14:             nn.ReLU(),
15:             nn.Linear(128,128),
16:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),

--- lines 40-46 ---
40:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
41:             nn.ReLU(),
42:             nn.Linear(128,self.input_dim)
43:         )
44:
45:     def forward(self, x):
46:         z = self.encoder(x.view(-1,self.input_dim))

In [64]:

from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for relative_path in [
    "datasets/datasets.py",
    "datasets/dcase_dcase202x_t2_loader.py",
    "networks/base_model.py",
    "networks/dcase2023t2_ae/network.py",
]:
    path = repo / relative_path
    lines = path.read_text(encoding="utf-8").splitlines()

    print(f"\n{'=' * 14} {relative_path} {'=' * 14}")

    if relative_path.endswith("datasets.py"):
        terms = ("input_dim", "def data(", "def __init__")
    elif relative_path.endswith("dcase_dcase202x_t2_loader.py"):
        terms = ("self.input_dim", "self.width", "self.height",
                 "n_mels =", "frames =", "def __init__")
    elif relative_path.endswith("base_model.py"):
        terms = ("self.data.input_dim", "self.data.width",
                 "self.data.height", "shape=(")
    else:
        terms = ("nn.Linear(", "def forward", "self.input_dim")

    hits = [i for i, line in enumerate(lines)
            if any(term in line for term in terms)]

    shown = set()
    for i in hits:
        start, end = max(0, i - 2), min(len(lines), i + 5)
        if any(j in shown for j in range(start, end)):
            continue
        print(f"\n--- lines {start + 1}-{end} ---")
        for j in range(start, end):
            print(f"{j + 1}: {lines[j]}")
            shown.add(j)

============== datasets/datasets.py ==============

--- lines 8-14 ---
8:
9: class DCASE202XT2(object):
10:     def __init__(self, args):
11:         self.width   = args.frames
12:         self.height  = args.n_mels
13:         self.channel = 1
14:         self.input_dim = self.width*self.height*self.channel

--- lines 16-22 ---
16:         batch_sampler = None
17:         batch_size = args.batch_size
18:         print("input dim: %d" % (self.input_dim))
19:
20:         dataset_name = args.dataset[:11]
21:         machine_type = args.dataset[11:]
22:         if args.eval:

--- lines 186-192 ---
186:     }
187:
188:     def __init__(self,datasets_str):
189:         self.data = Datasets.DatasetsDic[datasets_str]
190:
191:     def show_list():
192:         return Datasets.DatasetsDic.keys()

============== datasets/dcase_dcase202x_t2_loader.py ==============

--- lines 12-18 ---
12:
13: class DCASE202XT2Loader(torch.utils.data.Dataset):
14:     def __init__(self,
15:                 root:str,
16:                 dataset_name,
17:                 section_keyword,
18:                 machine_type:str="ToyCar",

============== networks/base_model.py ==============

--- lines 97-103 ---
97:             frames=args.frames,
98:             frame_hop_length=args.frame_hop_length,
99:             shape=(self.data.channel, self.data.width, self.data.height)
100:         )
101:
102:         self.result_column_dict = {
103:             "single_domain":["section", "AUC", "pAUC", "precision", "recall", "F1 score"],

============== networks/dcase2023t2_ae/network.py ==============

--- lines 5-11 ---
5:     def __init__(self,input_dim, block_size):
6:         super(AENet,self).__init__()
7:         self.input_dim = input_dim
8:         self.cov_source = nn.Parameter(torch.zeros(block_size, block_size), requires_grad=False)
9:         self.cov_target = nn.Parameter(torch.zeros(block_size, block_size), requires_grad=False)
10:
11:         self.encoder = nn.Sequential(

--- lines 13-19 ---
13:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
14:             nn.ReLU(),
15:             nn.Linear(128,128),
16:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
17:             nn.ReLU(),
18:             nn.Linear(128,128),
19:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),

--- lines 22-28 ---
22:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
23:             nn.ReLU(),
24:             nn.Linear(128,8),
25:             nn.BatchNorm1d(8,momentum=0.01, eps=1e-03),
26:             nn.ReLU(),
27:         )
28:

--- lines 31-37 ---
31:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
32:             nn.ReLU(),
33:             nn.Linear(128,128),
34:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
35:             nn.ReLU(),
36:             nn.Linear(128,128),
37:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),

--- lines 40-46 ---
40:             nn.BatchNorm1d(128,momentum=0.01, eps=1e-03),
41:             nn.ReLU(),
42:             nn.Linear(128,self.input_dim)
43:         )
44:
45:     def forward(self, x):
46:         z = self.encoder(x.view(-1,self.input_dim))

In [65]:

from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for name in [
    "baseline.yaml",
    "train_ae.sh",
    "01_train_2026t2.sh",
]:
    path = repo / name
    print(f"\n{'=' * 16} {name} {'=' * 16}")

    if not path.exists():
        print("Not found at repository root.")
        continue

    lines = path.read_text(encoding="utf-8").splitlines()

    if name == "baseline.yaml":
        for i, line in enumerate(lines, 1):
            if line.strip() and not line.lstrip().startswith("#"):
                print(f"{i}: {line}")
    else:
        for i, line in enumerate(lines, 1):
            if any(term in line for term in (
                "train.py", "--config", "baseline.yaml",
                "--dataset", "--dev", "--mono",
                "python", "use_ids", "train_only"
            )):
                print(f"{i}: {line}")

print("\nDataset directory exists:",
      (repo / "data/dcase2026t2/dev_data/raw/bearingEmu").exists())
print("Original train files:",
      len(list(Path("/content/AURIX_data/bearingEmu/train").glob("*.wav"))))
print("Original test files:",
      len(list(Path("/content/AURIX_data/bearingEmu/test").glob("*.wav"))))

================ baseline.yaml ================
1: --dataset_directory: ./data
2: --result_directory: ./results
3: --export_dir: baseline
5: --use_cuda: True
6: --log_interval: 100
7: --model: DCASE2023T2-AE
8: --score: MSE
9: --seed: 13711
10: --is_auto_download: False
12: --max_fpr: 0.1
13: --decision_threshold: 0.9
16: --n_mels: 128
17: --frames: 5
18: --frame_hop_length: 1
19: --n_fft: 1024
20: --hop_length: 512
21: --power: 2.0
22: --fmin: 0.0
23: --fmax: null
24: --win_length: null
27: --batch_size: 256
28: --epochs: 100
29: -lr: 0.001
30: --shuffle: True
31: --validation_split: 0.1

================ train_ae.sh ================
23: python3 train.py \
24:     --dataset=${dataset} \
27:     --use_ids ${id} \
28:     --train_only \
29:     --mono=${mono} \

================ 01_train_2026t2.sh ================
12:     && [ "${dev_eval}" != "--dev" ] \
16:     echo -e "usage\t: $0 ['-d' | '--dev' | '-e' | '--eval']"
18:     echo -e "\tchoice from ['-d' | '--dev' | '-e' | '--eval']."
19:     echo -e "\t\t-d, --dev\t: Using Development dataset. "
30: if [ "${dev_eval}" = "-d" ] || [ "${dev_eval}" = "--dev" ]

Dataset directory exists: True
Original train files: 1000
Original test files: 200

In [66]:

from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for filename in ["train.py", "train_ae.sh"]:
    path = repo / filename
    print(f"\n{'=' * 16} {filename} {'=' * 16}")

    if not path.exists():
        print("FILE NOT FOUND")
        continue

    lines = path.read_text(encoding="utf-8").splitlines()

    if filename == "train.py":
        for i, line in enumerate(lines, 1):
            if any(term in line for term in (
                "ArgumentParser", "parse_args", "config",
                "yaml", "epochs", "train_only",
                "use_cuda", "def main", "if __name__"
            )):
                print(f"{i}: {line}")
    else:
        for i, line in enumerate(lines, 1):
            print(f"{i}: {line}")

================ train.py ================
10: # load parameter.yaml
12: param = com.yaml_load()
15: def main():
17:     # read parameters from yaml
19:     args = parser.parse_args(args=flat_param)
21:     args = parser.parse_args(namespace=args)
24:     if args.train_only and args.test_only:
25:         raise ValueError("--train_only and --test_only cannot be used together.")
26:     elif args.train_only:
36:     args.cuda = args.use_cuda and torch.cuda.is_available()
59:         for epoch in range(1, args.epochs + 2):
66: if __name__ == "__main__":

================ train_ae.sh ================
1: echo $*
2:
3: dataset=$1
4: dev_eval=$2
5: mono=$3
6: id_1=$4
7: id_2=$5
8: id_3=$6
9: id_4=$7
10:
11: id="$id_1 $id_2 $id_3 $id_4"
12:
13: echo dataset ${dataset}
14: echo dev_eval ${dev_eval}
15: echo id ${id}
16:
17: tag="id("
18: for i in ${id}; do
19: tag="${tag}${i}_"
20: done
21: tag="${tag})"
22:
23: python3 train.py \
24:     --dataset=${dataset} \
25:     ${dev_eval} \
26:     -tag=${tag} \
27:     --use_ids ${id} \
28:     --train_only \
29:     --mono=${mono} \

In [67]:

from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

checks = {
    "train.py": [(1, 70)],
    "networks/dcase2023t2_ae/dcase2023t2_ae.py": [(1, 90)],
    "common.py": [(1, 100)],
}

for filename, ranges in checks.items():
    path = repo / filename
    print(f"\n{'=' * 14} {filename} {'=' * 14}")

    if not path.exists():
        print("FILE NOT FOUND")
        continue

    lines = path.read_text(encoding="utf-8").splitlines()

    for start, end in ranges:
        for i in range(start - 1, min(end, len(lines))):
            print(f"{i + 1}: {lines[i]}")

============== train.py ==============
1: import random
2: import numpy as np
3: import torch
4:
5: # original lib
6: import common as com
7: from networks.models import Models
8:
9: ########################################################################
10: # load parameter.yaml
11: ########################################################################
12: param = com.yaml_load()
13: ########################################################################
14:
15: def main():
16:     parser = com.get_argparse()
17:     # read parameters from yaml
18:     flat_param = com.param_to_args_list(params=param)
19:     args = parser.parse_args(args=flat_param)
20:     # read parameters from command line
21:     args = parser.parse_args(namespace=args)
22:     print(args)
23:
24:     if args.train_only and args.test_only:
25:         raise ValueError("--train_only and --test_only cannot be used together.")
26:     elif args.train_only:
27:         train = True
28:         test = False
29:     elif args.test_only:
30:         train = False
31:         test = True
32:     else:
33:         train = True
34:         test = True
35:
36:     args.cuda = args.use_cuda and torch.cuda.is_available()
37:
38:     # Python random
39:     random.seed(args.seed)
40:     # Numpy
41:     np.random.seed(args.seed)
42:     # Pytorch
43:     torch.manual_seed(args.seed)
44:     torch.cuda.manual_seed(args.seed)
45:     torch.backends.cudnn.deterministic = True
46:     torch.use_deterministic_algorithms = True
47:
48:     net = Models(args.model).net(
49:         args=args,
50:         train=train,
51:         test=test
52:     )
53:
54:
55:     print(args.model)
56:
57:     print("============== BEGIN TRAIN ==============")
58:     if train:
59:         for epoch in range(1, args.epochs + 2):
60:             net.train(epoch)
61:     print("============ END OF TRAIN ============")
62:
63:     if test:
64:         net.test()
65:
66: if __name__ == "__main__":
67:     main()

============== networks/dcase2023t2_ae/dcase2023t2_ae.py ==============
1: import os
2: import sys
3: import torch
4: from torch import optim
5: import torch.nn.functional as F
6: import numpy as np
7: import scipy
8: from sklearn import metrics
9: import csv
10: from tqdm import tqdm
11:
12: from networks.base_model import BaseModel
13: from networks.dcase2023t2_ae.network import AENet
14: from networks.criterion.mahala import cov_v, loss_function_mahala, calc_inv_cov
15: from tools.plot_anm_score import AnmScoreFigData
16: from tools.plot_loss_curve import csv_to_figdata
17:
18: class DCASE2023T2AE(BaseModel):
19:     def __init__(self, args, train, test):
20:         super().__init__(
21:             args=args,
22:             train=train,
23:             test=test
24:         )
25:         parameter_list = [{"params":self.model.parameters()}]
26:         self.optimizer = optim.Adam(parameter_list, lr=self.args.learning_rate)
27:         self.mse_score_distr_file_path = self.model_dir/f"score_distr_{self.args.model}_{self.args.dataset}{self.model_name_suffix}{self.eval_suffix}_seed{self.args.seed}_mse.pickle"
28:         self.mahala_score_distr_file_path = self.model_dir/f"score_distr_{self.args.model}_{self.args.dataset}{self.model_name_suffix}{self.eval_suffix}_seed{self.args.seed}_mahala.pickle"
29:
30:
31:     def init_model(self):
32:         self.block_size = self.data.height
33:         return AENet(input_dim=self.data.input_dim, block_size=self.block_size)
34:
35:     def get_log_header(self):
36:         self.column_heading_list=[
37:                 ["loss"],
38:                 ["val_loss"],
39:                 ["recon_loss"],
40:                 ["recon_loss_source", "recon_loss_target"],
41:         ]
42:         return "loss,val_loss,recon_loss,recon_loss_source,recon_loss_target"
43:
44:     def train(self, epoch):
45:         if epoch <= self.epoch:
46:             return
47:         torch.autograd.set_detect_anomaly(True)
48:         train_loss = 0
49:         train_recon_loss = 0
50:         train_recon_loss_source = 0
51:         train_recon_loss_target = 0
52:         y_pred = []
53:
54:         train_loader = self.train_loader
55:
56:         if epoch == self.args.epochs + 1:
57:             print("\n============== CALCULATE COVARIANCE ==============")
58:             is_calc_cov = True
59:             self.model.eval()
60:             torch.set_grad_enabled(False)
61:             # initialize mahalanobis param
62:             cov_x_source = np.zeros((self.block_size, self.block_size))
63:             cov_x_source = torch.from_numpy(cov_x_source)
64:             cov_x_source = cov_x_source.to(self.device).float()
65:             cov_x_target = cov_x_source.clone().detach()
66:             num_source = 0
67:             num_target = 0
68:             epoch = self.args.epochs
69:         else:
70:             self.model.train()
71:             is_calc_cov = False
72:
73:         for batch_idx, batch in enumerate(tqdm(train_loader)):
74:             data = batch[0]
75:             data = data.to(self.device).float()
76:             if data.shape[0] <= 1:
77:                 continue
78:             data_name_list = batch[3]
79:             machine_id = torch.argmax(batch[2], dim=1).long()
80:             machine_id = machine_id.to(self.device)
81:
82:             is_target_list = ["target" in data_name for data_name in data_name_list]
83:             is_source_list = np.logical_not(is_target_list).tolist()
84:             n_source = is_source_list.count(True)
85:             n_target = is_target_list.count(True)
86:
87:             if not is_calc_cov:
88:                 self.optimizer.zero_grad()
89:             recon_batch, z = self.model(data)
90:

============== common.py ==============
1: import yaml
2: import itertools
3: import argparse
4:
5: ########################################################################
6: # load parameter.yaml
7: ########################################################################
8: def yaml_load():
9:     with open("baseline.yaml") as stream:
10:         param = yaml.safe_load(stream)
11:     return param
12:
13: def param_to_args_list(params):
14:     params = list(itertools.chain.from_iterable(zip(params.keys(), params.values())))
15:     args_list = []
16:     for param in params:
17:         if type(param) is list:
18:             args_list.extend([str(p) for p in param])
19:         else:
20:             args_list.append(str(param))
21:     return args_list
22:
23: ########################################################################
24: # argparse setting
25: ########################################################################
26: def str2bool(v):
27:     if v.lower() in ['true', 1]:
28:         return True
29:     elif v.lower() in ['false', 0]:
30:         return False
31:     else:
32:         raise argparse.ArgumentTypeError('Boolean value expected.')
33:
34: def float_or_None(v):
35:     if v.lower() in ["none", "null"]:
36:         return None
37:     return float(v)
38:
39: def get_argparse():
40:     parser = argparse.ArgumentParser(
41:             description='Main function to call training for different AutoEncoders')
42:     parser.add_argument('--model', type=str, default='DCASE2023T2-AE', metavar='N',
43:                         help='train model name')
44:     parser.add_argument('--score', type=str, default="MSE", choices=["MSE", "MAHALA"])
45:     parser.add_argument('--seed', type=int, default=39876401, metavar='S',
46:                         help='random seed (default: 39876401)')
47:
48:     parser.add_argument('--use_cuda', type=str2bool, default=True,
49:                         help='enables CUDA training')
50:     parser.add_argument('--gpu_id',type=int, nargs='*', default=[0,],
51:                         help='Specify GPU id')
52:     parser.add_argument('--log_interval', type=int, default=100, metavar='N',
53:                         help='how many batches to wait before logging training status')
54:
55:     parser.add_argument('--decision_threshold', type=float, default=0.9)
56:     parser.add_argument('--max_fpr', type=float, default=0.1)
57:
58:     # feature
59:     parser.add_argument('--n_mels',type=int, default=128,
60:                         help='Length of the melfilter bank')
61:     parser.add_argument('--frames',type=int, default=5,
62:                         help='Number of frames in a feature vector')
63:     parser.add_argument('--frame_hop_length',type=int, default=1,
64:                         help='number of frames between successive feature')
65:     parser.add_argument('--n_fft',type=int, default=1024,
66:                         help='length of the FFT window')
67:     parser.add_argument('--hop_length',type=int, default=512,
68:                         help='number of samples between successive frames')
69:     parser.add_argument('--power', type=float, default=2.0)
70:     parser.add_argument('--fmin', type=float, default=0.0)
71:     parser.add_argument('--fmax', type=float_or_None, default=None)
72:     parser.add_argument('--win_length', type=float_or_None, default=None)
73:
74:     # fit
75:     parser.add_argument('--batch_size', type=int, default=512, metavar='N',
76:                         help='input batch size for training (default: 512)')
77:     parser.add_argument('--epochs', type=int, default=10, metavar='N',
78:                         help='number of epochs to train (default: 10)')
79:     parser.add_argument('-lr', '--learning_rate', default=0.03, type=float,
80:                         help='learning rate (default: 0.03)')
81:     parser.add_argument('--shuffle', type=str, default="full",
82:                         help='shuffle type (full , simple)')
83:     parser.add_argument('--validation_split', type=float, default=0.1)
84:
85:     # dataset
86:     parser.add_argument('--dataset_directory', type=str, default='data',
87:                         help='Where to parent dataset dir')
88:     parser.add_argument('--dataset', type=str, default='DCASE2023T2ToyCar', metavar='N',
89:                         help='dataset to use')
90:     parser.add_argument('-d', '--dev', action='store_true',
91:                         help='Use Development dataset')
92:     parser.add_argument('-e', '--eval', action='store_true',
93:                         help='Use Evaluation dataset')
94:     parser.add_argument('--use_ids', type=int, nargs='*', default=[],
95:                     help='Machine ID to be treated as nml data')
96:     parser.add_argument('--is_auto_download', type=str2bool, default=False,
97:                         help="Download dataset if not exist")
98:     parser.add_argument("--mono", type=str2bool, default=True,
99:                         help="Load input audio as monaural. DCASE2020T2-2025T2 are monaural, DCASE2026T2 is stereo")
100:

In [68]:

from pathlib import Path
import subprocess
import sys

repo = Path("/content/dcase2026_baseline_ae")
assert (repo / "train.py").exists()
assert (repo / "baseline.yaml").exists()

command = [
    sys.executable, "train.py",
    "--dataset=DCASE2026T2bearingEmu",
    "--dev",
    "--train_only",
    "--mono=False",
    "--use_cuda=False",
    "--epochs=2",
    "--batch_size=64",
    "--log_interval=1",
]

print("Working directory:", repo)
print("Command:", " ".join(command))
print("This run uses training data only; test evaluation is disabled.")

result = subprocess.run(
    command,
    cwd=repo,
    text=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    timeout=600,
)

print("\nExit code:", result.returncode)
print("\nLast 100 output lines:")
print("\n".join(result.stdout.splitlines()[-100:]))

if result.returncode != 0:
    print("\nTraining smoke test failed. Do not launch a longer run yet.")
else:
    print("\nTraining smoke test process completed.")

Working directory: /content/dcase2026_baseline_ae
Command: /usr/bin/python3 train.py --dataset=DCASE2026T2bearingEmu --dev --train_only --mono=False --use_cuda=False --epochs=2 --batch_size=64 --log_interval=1
This run uses training data only; test evaluation is disabled.

Exit code: 1

Last 100 output lines:
Traceback (most recent call last):
  File "/content/dcase2026_baseline_ae/train.py", line 7, in <module>
    from networks.models import Models
  File "/content/dcase2026_baseline_ae/networks/models.py", line 1, in <module>
    from networks.dcase2023t2_ae.dcase2023t2_ae import DCASE2023T2AE
  File "/content/dcase2026_baseline_ae/networks/dcase2023t2_ae/dcase2023t2_ae.py", line 12, in <module>
    from networks.base_model import BaseModel
  File "/content/dcase2026_baseline_ae/networks/base_model.py", line 12, in <module>
    from tools.plot_time_frequency import TimeFrequencyFigData
  File "/content/dcase2026_baseline_ae/tools/plot_time_frequency.py", line 4, in <module>
    from datasets.datasets import Datasets
ModuleNotFoundError: No module named 'datasets.datasets'

Training smoke test failed. Do not launch a longer run yet.

In [69]:
import os
import sys
import importlib.util
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

print("Current directory:", os.getcwd())
print("Python executable:", sys.executable)
print("Repository exists:", repo.exists())
print("datasets directory exists:", (repo / "datasets").is_dir())
print("datasets/__init__.py exists:", (repo / "datasets" / "__init__.py").exists())
print("datasets/datasets.py exists:", (repo / "datasets" / "datasets.py").exists())

print("\nPython import resolution:")
spec = importlib.util.find_spec("datasets")
print("datasets spec:", spec)
print("datasets origin:", spec.origin if spec else None)
print("datasets search locations:",
      list(spec.submodule_search_locations or []) if spec else None)

print("\nProject files:")
for name in ["train.py", "datasets", "networks", "baseline.yaml"]:
    path = repo / name
    print(f"{name}: {'FOUND' if path.exists() else 'MISSING'}")

Current directory: /content/AURIX.V1
Python executable: /usr/bin/python3
Repository exists: True
datasets directory exists: True
datasets/__init__.py exists: False
datasets/datasets.py exists: True

Python import resolution:
datasets spec: ModuleSpec(name='datasets', loader=<_frozen_importlib_external.SourceFileLoader object at 0x79800e33ed50>, origin='/usr/local/lib/python3.13/dist-packages/datasets/__init__.py', submodule_search_locations=['/usr/local/lib/python3.13/dist-packages/datasets'])
datasets origin: /usr/local/lib/python3.13/dist-packages/datasets/__init__.py
datasets search locations: ['/usr/local/lib/python3.13/dist-packages/datasets']

Project files:
train.py: FOUND
datasets: FOUND
networks: FOUND
baseline.yaml: FOUND

In [70]:
from pathlib import Path
import sys
import importlib.util

repo = Path("/content/dcase2026_baseline_ae").resolve()
datasets_dir = repo / "datasets"
init_file = datasets_dir / "__init__.py"

assert (repo / "train.py").exists()
assert (datasets_dir / "datasets.py").exists()

# Add the baseline repository to Python's import path.
repo_str = str(repo)
if repo_str in sys.path:
    sys.path.remove(repo_str)
sys.path.insert(0, repo_str)

# Make the local datasets directory an explicit Python package.
if not init_file.exists():
    init_file.touch()
    print("Created:", init_file)
else:
    print("__init__.py already exists.")

# Verify which package Python will import.
spec = importlib.util.find_spec("datasets")
print("Resolved datasets package:", spec.origin if spec else None)

assert spec is not None
assert Path(spec.origin).resolve() == init_file.resolve(), (
    "Python is still resolving the wrong datasets package."
)

print("Import path check: PASS")

Created: /content/dcase2026_baseline_ae/datasets/__init__.py
Resolved datasets package: /content/dcase2026_baseline_ae/datasets/__init__.py
Import path check: PASS

In [71]:
from pathlib import Path
import subprocess
import sys

repo = Path("/content/dcase2026_baseline_ae")

check_code = """
import datasets
import datasets.datasets
from networks.models import Models

print("datasets package:", datasets.__file__)
print("datasets.datasets:", datasets.datasets.__file__)
print("Model import: PASS")
"""

result = subprocess.run(
    [sys.executable, "-c", check_code],
    cwd=str(repo),
    text=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
)

print(result.stdout)
print("Exit code:", result.returncode)

Traceback (most recent call last):
  File "<string>", line 3, in <module>
    import datasets.datasets
  File "/content/dcase2026_baseline_ae/datasets/datasets.py", line 6, in <module>
    from datasets.loader_common import get_machine_type_dict
  File "/content/dcase2026_baseline_ae/datasets/loader_common.py", line 25, in <module>
    import fasteners
ModuleNotFoundError: No module named 'fasteners'

Exit code: 1

In [72]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for name in [
    "requirements.txt",
    "environment.yml",
    "pyproject.toml",
    "setup.py",
]:
    path = repo / name
    print(f"\n--- {name} ---")
    if path.exists():
        print(path.read_text()[:12000])
    else:
        print("Not found")

--- requirements.txt ---
scipy
librosa
matplotlib
tqdm
seaborn
fasteners

# Included in docker image
torch==2.6.0+cu118
torchvision==0.21.0+cu118
PyYAML==6.0.2


--- environment.yml ---
Not found

--- pyproject.toml ---
Not found

--- setup.py ---
Not found

In [73]:
%pip install fasteners

Collecting fasteners
  Downloading fasteners-0.20-py3-none-any.whl.metadata (4.8 kB)
Downloading fasteners-0.20-py3-none-any.whl (18 kB)
Installing collected packages: fasteners
Successfully installed fasteners-0.20

In [74]:
from pathlib import Path
import subprocess
import sys

repo = Path("/content/dcase2026_baseline_ae")

code = """
import fasteners
import datasets.datasets
from networks.models import Models

print("fasteners: PASS")
print("datasets.datasets: PASS")
print("Model imports: PASS")
"""

result = subprocess.run(
    [sys.executable, "-c", code],
    cwd=str(repo),
    text=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
)

print(result.stdout)
print("Exit code:", result.returncode)

fasteners: PASS
datasets.datasets: PASS
Model imports: PASS

Exit code: 0

In [75]:
from pathlib import Path
import soundfile as sf
import numpy as np

data_dir = Path(
    "/content/dcase2026_baseline_ae/data/"
    "dcase2026t2/dev_data/raw/bearingEmu/train"
)

files = sorted(data_dir.glob("*.wav"))

print("Training directory exists:", data_dir.is_dir())
print("Number of training WAV files:", len(files))

assert len(files) == 1000, (
    f"Expected 1000 training files, found {len(files)}"
)

# Verify one source-normal and one target-normal training recording.
selected = [
    next(p for p in files if "source_train_normal" in p.name),
    next(p for p in files if "target_train_normal" in p.name),
]

for path in selected:
    info = sf.info(str(path))
    audio, sr = sf.read(str(path), dtype="float32")

    print(f"\nFile: {path.name}")
    print("Sample rate:", sr)
    print("Shape:", audio.shape)
    print("Channels:", info.channels)
    print("Finite values:", bool(np.isfinite(audio).all()))

    assert sr == 16000
    assert audio.shape == (160000, 2)
    assert np.isfinite(audio).all()

print("\nTraining data integrity check: PASS")

Training directory exists: True
Number of training WAV files: 0

AssertionError: Expected 1000 training files, found 0

In [76]:
from pathlib import Path

roots = [
    Path("/content/AURIX_data/bearingEmu"),
    Path("/content/dcase2026_baseline_ae/data"),
]

for root in roots:
    print(f"\n{'=' * 55}")
    print("Root:", root)
    print("Exists:", root.exists())

    if not root.exists():
        continue

    for folder in [root, *list(root.iterdir())]:
        if not folder.is_dir():
            continue

        wav_count = sum(1 for _ in folder.rglob("*.wav"))
        print(f"{folder} -> {wav_count} WAV files")

        if folder != root:
            for subfolder in folder.iterdir():
                if subfolder.is_dir():
                    count = sum(1 for _ in subfolder.glob("*.wav"))
                    print(f"    {subfolder.name}/ -> {count} WAV files")

=======================================================
Root: /content/AURIX_data/bearingEmu
Exists: True
/content/AURIX_data/bearingEmu -> 1200 WAV files
/content/AURIX_data/bearingEmu/test -> 200 WAV files
/content/AURIX_data/bearingEmu/train -> 1000 WAV files

=======================================================
Root: /content/dcase2026_baseline_ae/data
Exists: True
/content/dcase2026_baseline_ae/data -> 1200 WAV files
/content/dcase2026_baseline_ae/data/dcase2021t2 -> 0 WAV files
    dev_data/ -> 0 WAV files
    eval_data/ -> 0 WAV files
/content/dcase2026_baseline_ae/data/dcase2024t2 -> 0 WAV files
    dev_data/ -> 0 WAV files
    eval_data/ -> 0 WAV files
/content/dcase2026_baseline_ae/data/dcase2020t2 -> 0 WAV files
    dev_data/ -> 0 WAV files
    eval_data/ -> 0 WAV files
/content/dcase2026_baseline_ae/data/dcase2023t2 -> 0 WAV files
    dev_data/ -> 0 WAV files
    eval_data/ -> 0 WAV files
/content/dcase2026_baseline_ae/data/dcase2025t2 -> 0 WAV files
    dev_data/ -> 0 WAV files
    eval_data/ -> 0 WAV files
/content/dcase2026_baseline_ae/data/dcase2022t2 -> 0 WAV files
    dev_data/ -> 0 WAV files
    eval_data/ -> 0 WAV files
/content/dcase2026_baseline_ae/data/dcase2026t2 -> 1200 WAV files
    dev_data/ -> 0 WAV files
    eval_data/ -> 0 WAV files

In [77]:
from pathlib import Path
import os

root = Path("/content/dcase2026_baseline_ae/data/dcase2026t2")

print("WAV files under dcase2026t2:")
for p in list(root.rglob("*.wav"))[:5]:
    print("File:", p)
    print("Is symlink:", p.is_symlink())
    print("Resolved path:", p.resolve())
    print()

print("Directories under dcase2026t2:")
for p in root.rglob("*"):
    if p.is_dir() and p.parent == root:
        print(p, "->", list(p.iterdir())[:5])

WAV files under dcase2026t2:
File: /content/dcase2026_baseline_ae/data/dcase2026t2/dev_data/raw/bearingEmu/train/section_00/section_00_source_train_normal_0067_noAttribute.wav
Is symlink: True
Resolved path: /content/AURIX_data/bearingEmu/train/section_00_source_train_normal_0067_noAttribute.wav

File: /content/dcase2026_baseline_ae/data/dcase2026t2/dev_data/raw/bearingEmu/train/section_00/section_00_source_train_normal_0810_noAttribute.wav
Is symlink: True
Resolved path: /content/AURIX_data/bearingEmu/train/section_00_source_train_normal_0810_noAttribute.wav

File: /content/dcase2026_baseline_ae/data/dcase2026t2/dev_data/raw/bearingEmu/train/section_00/section_00_source_train_normal_0327_noAttribute.wav
Is symlink: True
Resolved path: /content/AURIX_data/bearingEmu/train/section_00_source_train_normal_0327_noAttribute.wav

File: /content/dcase2026_baseline_ae/data/dcase2026t2/dev_data/raw/bearingEmu/train/section_00/section_00_source_train_normal_0074_noAttribute.wav
Is symlink: True
Resolved path: /content/AURIX_data/bearingEmu/train/section_00_source_train_normal_0074_noAttribute.wav

File: /content/dcase2026_baseline_ae/data/dcase2026t2/dev_data/raw/bearingEmu/train/section_00/section_00_source_train_normal_0132_noAttribute.wav
Is symlink: True
Resolved path: /content/AURIX_data/bearingEmu/train/section_00_source_train_normal_0132_noAttribute.wav

Directories under dcase2026t2:
/content/dcase2026_baseline_ae/data/dcase2026t2/dev_data -> [PosixPath('/content/dcase2026_baseline_ae/data/dcase2026t2/dev_data/raw'), PosixPath('/content/dcase2026_baseline_ae/data/dcase2026t2/dev_data/processed')]
/content/dcase2026_baseline_ae/data/dcase2026t2/eval_data -> [PosixPath('/content/dcase2026_baseline_ae/data/dcase2026t2/eval_data/raw'), PosixPath('/content/dcase2026_baseline_ae/data/dcase2026t2/eval_data/processed')]

In [78]:
from pathlib import Path
import soundfile as sf
import numpy as np

data_dir = Path(
    "/content/dcase2026_baseline_ae/data/"
    "dcase2026t2/dev_data/raw/bearingEmu/train/section_00"
)

files = sorted(data_dir.glob("*.wav"))

print("Training section exists:", data_dir.is_dir())
print("WAV files in section_00:", len(files))

assert len(files) == 1000, (
    f"Expected 1000 WAV files in section_00, found {len(files)}"
)

selected = [
    next(p for p in files if "source_train_normal" in p.name),
    next(p for p in files if "target_train_normal" in p.name),
]

for path in selected:
    audio, sr = sf.read(str(path), dtype="float32")

    print(f"\nFile: {path.name}")
    print("Sample rate:", sr)
    print("Shape:", audio.shape)
    print("Finite values:", bool(np.isfinite(audio).all()))

    assert sr == 16000
    assert audio.shape == (160000, 2)
    assert np.isfinite(audio).all()

print("\nTraining data integrity check: PASS")

Training section exists: True
WAV files in section_00: 1000

File: section_00_source_train_normal_0000_noAttribute.wav
Sample rate: 16000
Shape: (160000, 2)
Finite values: True

File: section_00_target_train_normal_0000_noAttribute.wav
Sample rate: 16000
Shape: (160000, 2)
Finite values: True

Training data integrity check: PASS

In [79]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")
path = repo / "datasets" / "loader_common.py"
lines = path.read_text().splitlines()

for start, end in [(85, 135), (135, 205)]:
    print(f"\n{'=' * 20} lines {start}-{end} {'=' * 20}")
    for i in range(start - 1, min(end, len(lines))):
        print(f"{i + 1}: {lines[i]}")

==================== lines 85-135 ====================
85:
86:
87: ########################################################################
88: # file I/O
89: ########################################################################
90: # wav file input
91: def file_load(wav_name, mono=False):
92:     """
93:     load .wav file.
94:
95:     wav_name : str
96:         target .wav file
97:     mono : boolean
98:         When load a multi channels file and this param True, the returned data will be merged for mono data
99:
100:     return : numpy.array( float )
101:     """
102:     info = sf.info(wav_name)
103:     ch = info.channels
104:     assert any([
105:         mono and ch == 1,
106:         not mono and ch > 1,
107:     ]), f"Channel mismatch: The file is {ch=}, but {mono=} is specified."
108:
109:     try:
110:         if mono:
111:             return librosa.load(wav_name, sr=None, mono=mono)
112:         else:
113:             y, sr = librosa.load(wav_name, sr=None, mono=mono)
114:             return y[0], sr
115:     except:
116:         logger.error("file_broken or not exists!! : {}".format(wav_name))
117:
118:
119: ########################################################################
120:
121:
122: ########################################################################
123: # feature extractor
124: ########################################################################
125: def file_to_vectors(file_name,
126:                     n_mels=64,
127:                     n_frames=5,
128:                     n_fft=1024,
129:                     hop_length=512,
130:                     power=2.0,
131:                     fmax=None,
132:                     fmin=None,
133:                     win_length=None,
134:                     mono=True):
135:     """

==================== lines 135-205 ====================
135:     """
136:     convert file_name to a vector array.
137:
138:     file_name : str
139:         target .wav file
140:
141:     return : numpy.array( numpy.array( float ) )
142:         vector array
143:         * dataset.shape = (dataset_size, feature_vector_length)
144:     """
145:     # calculate the number of dimensions
146:     dims = n_mels * n_frames
147:
148:     # generate melspectrogram using librosa
149:     y, sr = file_load(file_name, mono=mono)
150:
151:     mel_spectrogram = librosa.feature.melspectrogram(y=y,
152:                                                         sr=sr,
153:                                                         n_fft=n_fft,
154:                                                         hop_length=hop_length,
155:                                                         n_mels=n_mels,
156:                                                         power=power,
157:                                                         fmax=fmax,
158:                                                         fmin=fmin,
159:                                                         win_length=win_length)
160:
161:     # convert melspectrogram to log mel energies
162:     log_mel_spectrogram = 20.0 / power * np.log10(np.maximum(mel_spectrogram, sys.float_info.epsilon))
163:
164:     # calculate total vector size
165:     n_vectors = log_mel_spectrogram.shape[-1] - n_frames + 1
166:
167:     # skip too short clips
168:     if n_vectors < 1:
169:         return np.empty((0, dims))
170:
171:     # generate feature vectors by concatenating multi frames
172:     vectors = np.zeros((n_vectors, dims))
173:     for t in range(n_frames):
174:         vectors[:, n_mels * t : n_mels * (t + 1)] = log_mel_spectrogram[:, t : t + n_vectors].T
175:
176:     return vectors
177:
178:
179: ########################################################################
180:
181:
182: ########################################################################
183: # get directory paths according to mode
184: ########################################################################
185: def select_dirs(param, mode):
186:     """
187:     param : dict
188:         baseline.yaml data
189:
190:     return :
191:         if active type the development :
192:             dirs :  list [ str ]
193:                 load base directory list of dev_data
194:         if active type the evaluation :
195:             dirs : list [ str ]
196:                 load base directory list of eval_data
197:     """
198:     if mode:
199:         logger.info("load_directory <- development")
200:         query = os.path.abspath("{base}/*".format(base=param["dev_directory"]))
201:     else:
202:         logger.info("load_directory <- evaluation")
203:         query = os.path.abspath("{base}/*".format(base=param["eval_directory"]))
204:     dirs = sorted(glob.glob(query))
205:     dirs = [f for f in dirs if os.path.isdir(f)]

In [80]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")
targets = [
    repo / "datasets" / "datasets.py",
    repo / "datasets" / "dcase_dcase202x_t2_loader.py",
]

for path in targets:
    print(f"\n{'=' * 65}\nFILE: {path.name}\n{'=' * 65}")

    if not path.exists():
        print("File not found")
        continue

    lines = path.read_text().splitlines()

    for i, line in enumerate(lines):
        if any(term in line for term in [
            "class DCASE2026XT2",
            "class DCASE202XT2",
            "file_to_vectors",
            "source_domain",
            "target_domain",
            "train_loader",
            "DataLoader",
            "section_00",
        ]):
            start = max(0, i - 4)
            end = min(len(lines), i + 9)
            print(f"\n--- lines {start + 1}-{end} ---")
            for j in range(start, end):
                print(f"{j + 1}: {lines[j]}")

=================================================================
FILE: datasets.py
=================================================================

--- lines 5-17 ---
5:
6: from datasets.loader_common import get_machine_type_dict
7: from datasets.dcase_dcase202x_t2_loader import DCASE202XT2Loader
8:
9: class DCASE202XT2(object):
10:     def __init__(self, args):
11:         self.width   = args.frames
12:         self.height  = args.n_mels
13:         self.channel = 1
14:         self.input_dim = self.width*self.height*self.channel
15:         shuffle = args.shuffle
16:         batch_sampler = None
17:         batch_size = args.batch_size

--- lines 59-71 ---
59:                 )
60:
61:         train_index, valid_index = train_test_split(range(len(train_data)), test_size=args.validation_split)
62:         self.train_dataset = Subset(train_data, train_index)
63:         self.train_loader = torch.utils.data.DataLoader(
64:             self.train_dataset,
65:             batch_size=batch_size, shuffle=shuffle, batch_sampler=batch_sampler,
66:         )
67:         self.valid_dataset   = Subset(train_data, valid_index)
68:         self.valid_loader = torch.utils.data.DataLoader(
69:             self.valid_dataset,
70:             batch_size=batch_size, shuffle=False, batch_sampler=batch_sampler,
71:         )

--- lines 64-76 ---
64:             self.train_dataset,
65:             batch_size=batch_size, shuffle=shuffle, batch_sampler=batch_sampler,
66:         )
67:         self.valid_dataset   = Subset(train_data, valid_index)
68:         self.valid_loader = torch.utils.data.DataLoader(
69:             self.valid_dataset,
70:             batch_size=batch_size, shuffle=False, batch_sampler=batch_sampler,
71:         )
72:
73:         self.test_loader = []
74:         if args.train_only:
75:             return
76:         for id in self.section_id_list:

--- lines 95-107 ---
95:                 mono=args.mono,
96:            )
97:
98:            self.test_loader.append(
99:                 torch.utils.data.DataLoader(
100:                     _test_loader,
101:                     batch_size=_test_loader.n_vectors_ea_file, shuffle=False
102:                 )
103:            )
104:            self.mode = args.dev or _test_loader.mode
105:
106:
107: class Datasets:

=================================================================
FILE: dcase_dcase202x_t2_loader.py
=================================================================

--- lines 9-21 ---
9: import datetime
10:
11: from datasets import loader_common as com
12:
13: class DCASE202XT2Loader(torch.utils.data.Dataset):
14:     def __init__(self,
15:                 root:str,
16:                 dataset_name,
17:                 section_keyword,
18:                 machine_type:str="ToyCar",
19:                 section_ids=[],
20:                 train=True,
21:                 n_mels=128,

--- lines 27-39 ---
27:                 fmin=None,
28:                 win_length=None,
29:                 power=2.0,
30:                 data_type = "dev",
31:                 source_domain="mix",
32:                 use_id = [],
33:                 is_auto_download=False,
34:                 mono=True,
35:     ):
36:         super().__init__()
37:
38:         self.use_id = use_id
39:         self.section_ids = section_ids

--- lines 99-111 ---
99:             os.makedirs(self.log_melspectrogram_dir, exist_ok=True)
100:         pickle_name = section_keyword
101:         for section_id in section_ids:
102:             pickle_name = f"{pickle_name}_{section_id}"
103:         pickle_name = f"{pickle_name}_{source_domain}_TF{frames}-{frame_hop_length}_mel{n_fft}-{hop_length}"
104:         pickle_path = os.path.abspath(f"{self.log_melspectrogram_dir}/{pickle_name}.pickle")
105:
106:         self.load_pre_process(
107:             pickle_name=pickle_name,
108:             target_dir=target_dir,
109:             pickle_path=pickle_path,
110:             n_sections=n_sections,
111:             unique_section_names=unique_section_names,

--- lines 350-362 ---
350:     dims = n_mels * n_frames
351:
352:     # iterate file_to_vector_array()
353:     for idx in tqdm(range(len(file_list)), desc=msg):
354:         vectors = com.file_to_vectors(file_list[idx],
355:                                                 n_mels=n_mels,
356:                                                 n_frames=n_frames,
357:                                                 n_fft=n_fft,
358:                                                 hop_length=hop_length,
359:                                                 power=power,
360:                                                 fmax=fmax,
361:                                                 fmin=fmin,
362:                                                 win_length=win_length,

In [81]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")
checks = {
    "datasets.py": [
        (20, 75),
    ],
    "dcase_dcase202x_t2_loader.py": [
        (120, 220),
        (280, 370),
    ],
}

for filename, ranges in checks.items():
    path = repo / "datasets" / filename
    lines = path.read_text().splitlines()

    for start, end in ranges:
        print(f"\n{'=' * 65}")
        print(f"{filename}: lines {start}-{end}")
        print("=" * 65)

        for i in range(start - 1, min(end, len(lines))):
            print(f"{i + 1}: {lines[i]}")

=================================================================
datasets.py: lines 20-75
=================================================================
20:         dataset_name = args.dataset[:11]
21:         machine_type = args.dataset[11:]
22:         if args.eval:
23:             data_path = f'{args.dataset_directory}/{dataset_name.lower()}/eval_data/'
24:             data_type = "eval"
25:         elif args.dev:
26:             data_path = f'{args.dataset_directory}/{dataset_name.lower()}/dev_data/'
27:             data_type = "dev"
28:         else:
29:             print("incorrect argument")
30:             print("please set option argument '--dev' or '--eval'")
31:             sys.exit()
32:
33:         self.machine_type_dict = get_machine_type_dict(dataset_name, mode=args.dev)["machine_type"]
34:         self.section_id_list = self.machine_type_dict[machine_type][data_type]
35:         self.num_classes = len(self.section_id_list)
36:         print("num classes: %d" % (self.num_classes))
37:         self.id_list = [int(machine_id) for machine_id in self.section_id_list]
38:         section_keyword = get_machine_type_dict(dataset_name, mode=args.dev)["section_keyword"]
39:         train_data = DCASE202XT2Loader(
40:                 data_path,
41:                 dataset_name=dataset_name,
42:                 section_keyword=section_keyword,
43:                 machine_type=machine_type,
44:                 train=True,
45:                 section_ids=self.section_id_list,
46:                 frames=args.frames,
47:                 n_mels=args.n_mels,
48:                 frame_hop_length=args.frame_hop_length,
49:                 n_fft=args.n_fft,
50:                 hop_length=args.hop_length,
51:                 power=args.power,
52:                 fmax=args.fmax,
53:                 fmin=args.fmin,
54:                 win_length=args.win_length,
55:                 data_type=data_type,
56:                 use_id=args.use_ids,
57:                 is_auto_download=args.is_auto_download,
58:                 mono=args.mono,
59:                 )
60:
61:         train_index, valid_index = train_test_split(range(len(train_data)), test_size=args.validation_split)
62:         self.train_dataset = Subset(train_data, train_index)
63:         self.train_loader = torch.utils.data.DataLoader(
64:             self.train_dataset,
65:             batch_size=batch_size, shuffle=shuffle, batch_sampler=batch_sampler,
66:         )
67:         self.valid_dataset   = Subset(train_data, valid_index)
68:         self.valid_loader = torch.utils.data.DataLoader(
69:             self.valid_dataset,
70:             batch_size=batch_size, shuffle=False, batch_sampler=batch_sampler,
71:         )
72:
73:         self.test_loader = []
74:         if args.train_only:
75:             return

=================================================================
dcase_dcase202x_t2_loader.py: lines 120-220
=================================================================
120:             fmax=fmax,
121:             fmin=fmin,
122:             win_length=win_length,
123:             mono=mono,
124:         )
125:         if len(self.use_id) > 0:
126:             idx_list = [i for i, n in enumerate(np.argmax(self.condition, axis=1)) if int(section_ids[n]) in self.use_id]
127:         else:
128:             idx_list = list(range(len(self.condition)))
129:         idx_list_2 = [i//self.n_vectors_ea_file for i in idx_list[::self.n_vectors_ea_file]]
130:         self.data = self.data[idx_list]
131:         if len(self.y_true) > 0:
132:             self.y_true = self.y_true[idx_list_2]
133:         self.condition = self.condition[idx_list]
134:         self.basenames = [self.basenames[i] for i in idx_list_2]
135:
136:         # getitem method setting
137:         self.frame_idx_list = list(range(len(self.data)))
138:         self.dataset_len = len(self.frame_idx_list)
139:         self.getitem_fn = self.default_item
140:
141:     def load_pre_process(
142:             self,
143:             pickle_name,
144:             target_dir,
145:             pickle_path,
146:             n_sections,
147:             unique_section_names,
148:             dir_name,
149:             train,
150:             n_mels,
151:             frames,
152:             frame_hop_length,
153:             n_fft,
154:             hop_length,
155:             power,
156:             fmax,
157:             fmin,
158:             win_length,
159:             mono=True,
160:         ):
161:
162:         pickle_lockfile_path = os.path.abspath(f"{self.log_melspectrogram_dir}/{pickle_name}_lockfile")
163:         if os.path.isfile(pickle_path) and not os.path.isfile(pickle_lockfile_path):
164:             print("Setup has already been completed.")
165:             print(f"{pickle_path} is exists.")
166:             self.load_pickle(pickle_path=pickle_path)
167:             return
168:         else:
169:             pickle_lock = fasteners.InterProcessReaderWriterLock(pickle_lockfile_path)
170:             dataset_dir_lockfile_path = com.get_lockfile_path(target_dir=target_dir)
171:             is_enabled_dataset_dir_lock = os.path.isfile(dataset_dir_lockfile_path)
172:             if is_enabled_dataset_dir_lock:
173:                 dataset_dir_lock = fasteners.InterProcessReaderWriterLock(dataset_dir_lockfile_path)
174:             try:
175:                 pickle_lock.acquire_write_lock()
176:             except:
177:                 print(f"{datetime.datetime.now()}\tcan not lock {pickle_lockfile_path}.")
178:                 print(f"{pickle_path} is exists.")
179:                 self.load_pickle(pickle_path=pickle_path)
180:                 return
181:
182:             if os.path.exists(pickle_path):
183:                 print(f"{pickle_path} is exists.")
184:                 com.release_write_lock(
185:                     lock=pickle_lock,
186:                     lock_file_path=pickle_lockfile_path
187:                 )
188:                 self.load_pickle(pickle_path=pickle_path)
189:                 return
190:
191:             if is_enabled_dataset_dir_lock:
192:                 try:
193:                     dataset_dir_lock.acquire_read_lock()
194:                 except:
195:                     print(f"can not lock {dataset_dir_lockfile_path}.")
196:                     is_enabled_dataset_dir_lock = False
197:
198:             # number of wave files in each section
199:             # required for calculating y_pred for each wave file
200:             n_files_ea_section = []
201:
202:             self.data = np.empty((0, frames * n_mels), float)
203:             self.y_true = np.empty(0, float)
204:             self.condition = np.empty((0, n_sections), float)
205:             self.basenames = []
206:             for section_idx, section_name in enumerate(unique_section_names):
207:
208:                 # get file list for all sections
209:                 # all values of y_true are zero in training
210:                 files, y_true, condition = com.file_list_generator(target_dir=target_dir,
211:                                                         section_name=section_name,
212:                                                         unique_section_names=unique_section_names,
213:                                                         dir_name=dir_name,
214:                                                         mode=self.mode,
215:                                                         train=train)
216:                 n_files_ea_section.append(len(files))
217:                 for file in files:
218:                     self.basenames.append(os.path.basename(file))
219:
220:                 data_ea_section = file_list_to_data(files,

=================================================================
dcase_dcase202x_t2_loader.py: lines 280-370
=================================================================
280:                 return
281:             com.release_read_lock(
282:                 lock=pickle_lock,
283:                 lock_file_path=pickle_lock_file,
284:             )
285:         print(f"load pickle : {pickle_path}")
286:         try:
287:             with open(pickle_path, 'rb') as f:
288:                 self.data, self.y_true, self.condition, self.n_vectors_ea_file, self.basenames = pickle.load(f)
289:         except FileNotFoundError:
290:             print(f"{datetime.datetime.now()}\tFileNotFoundError: can not load pickle.")
291:             time.sleep(retry_delay_time)
292:             print(f"retry load pickle : {retry_count+1}/{retry_lim}")
293:             self.load_pickle(
294:                 pickle_path=pickle_path,
295:                 pickle_lock=pickle_lock,
296:                 pickle_lock_file=pickle_lock_file,
297:                 retry_count=retry_count+1,
298:                 retry_lim=retry_lim,
299:                 retry_delay_time=retry_delay_time+1,
300:             )
301:
302:     def __getitem__(self, index):
303:         """
304:         Returns:
305:             Tensor: input data
306:             Tensor: anomaly label
307:             Tensor: one-hot vector for conditioning (section id)
308:             int: start index
309:             str: file basename
310:         """
311:         return self.getitem_fn(index)
312:
313:     def default_item(self, index):
314:         data = self.data[index]
315:         y_true = self.y_true[index//self.n_vectors_ea_file] if len(self.y_true) > 0 else -1
316:         condition = self.condition[index]
317:         basename = self.basenames[index//self.n_vectors_ea_file]
318:         return data, y_true, condition, basename, index
319:
320:     def __len__(self):
321:         return self.dataset_len
322:
323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,
326:                         n_frames=5,
327:                         n_hop_frames=1,
328:                         n_fft=1024,
329:                         hop_length=512,
330:                         power=2.0,
331:                         fmax=None,
332:                         fmin=None,
333:                         win_length=None,
334:                         mono=True):
335:     """
336:     convert the file_list to a vector array.
337:     file_to_vector_array() is iterated, and the output vector array is concatenated.
338:
339:     file_list : list [ str ]
340:         .wav filename list of dataset
341:     msg : str ( default = "calc..." )
342:         description for tqdm.
343:         this parameter will be input into "desc" param at tqdm.
344:
345:     return : numpy.array( numpy.array( float ) )
346:         data for training (this function is not used for test.)
347:         * dataset.shape = (number of feature vectors, dimensions of feature vectors)
348:     """
349:     # calculate the number of dimensions
350:     dims = n_mels * n_frames
351:
352:     # iterate file_to_vector_array()
353:     for idx in tqdm(range(len(file_list)), desc=msg):
354:         vectors = com.file_to_vectors(file_list[idx],
355:                                                 n_mels=n_mels,
356:                                                 n_frames=n_frames,
357:                                                 n_fft=n_fft,
358:                                                 hop_length=hop_length,
359:                                                 power=power,
360:                                                 fmax=fmax,
361:                                                 fmin=fmin,
362:                                                 win_length=win_length,
363:                                                 mono=mono)
364:         vectors = vectors[: : n_hop_frames, :]
365:         if idx == 0:
366:             data = np.zeros((len(file_list) * vectors.shape[0], dims), float)
367:         if len(file_list) * vectors.shape[0] > data.shape[0]:
368:             tmp_data = np.zeros((len(file_list) * vectors.shape[0], dims), float)
369:             tmp_data[:data.shape[0], :] = data
370:             data = tmp_data

In [82]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")
cache_root = repo / "data" / "dcase2026t2" / "dev_data" / "processed"
train_dir = repo / "data" / "dcase2026t2" / "dev_data" / "raw" / "bearingEmu" / "train"

print("=== Feature cache ===")
print("Cache directory exists:", cache_root.exists())

if cache_root.exists():
    cache_files = [
        p for p in cache_root.rglob("*")
        if p.is_file() and p.suffix in {".pickle", ".pkl"}
    ]
    print("Cached feature files:", len(cache_files))
    for p in cache_files[:10]:
        print(p)

print("\n=== Recording-level split audit ===")
files = sorted(train_dir.rglob("*.wav"))
source_files = [p for p in files if "source_train_normal" in p.name]
target_files = [p for p in files if "target_train_normal" in p.name]

print("Total recordings:", len(files))
print("Source-normal recordings:", len(source_files))
print("Target-normal recordings:", len(target_files))
print("Example source:", source_files[0].name if source_files else "NONE")
print("Example target:", target_files[0].name if target_files else "NONE")

=== Feature cache ===
Cache directory exists: True
Cached feature files: 0

=== Recording-level split audit ===
Total recordings: 1000
Source-normal recordings: 990
Target-normal recordings: 10
Example source: section_00_source_train_normal_0000_noAttribute.wav
Example target: section_00_target_train_normal_0000_noAttribute.wav

In [83]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")
path = repo / "datasets" / "loader_common.py"
lines = path.read_text().splitlines()

terms = [
    "def file_list_generator",
    "source_domain",
    "target_domain",
    "source",
    "target",
    "def get_machine_type_dict",
]

matches = [
    i for i, line in enumerate(lines)
    if any(term in line for term in terms)
]

shown = set()
for i in matches:
    start = max(0, i - 5)
    end = min(len(lines), i + 14)

    if any(j in shown for j in range(start, end)):
        continue

    shown.update(range(start, end))
    print(f"\n--- lines {start + 1}-{end} ---")
    for j in range(start, end):
        print(f"{j + 1}: {lines[j]}")

--- lines 91-109 ---
91: def file_load(wav_name, mono=False):
92:     """
93:     load .wav file.
94:
95:     wav_name : str
96:         target .wav file
97:     mono : boolean
98:         When load a multi channels file and this param True, the returned data will be merged for mono data
99:
100:     return : numpy.array( float )
101:     """
102:     info = sf.info(wav_name)
103:     ch = info.channels
104:     assert any([
105:         mono and ch == 1,
106:         not mono and ch > 1,
107:     ]), f"Channel mismatch: The file is {ch=}, but {mono=} is specified."
108:
109:     try:

--- lines 134-152 ---
134:                     mono=True):
135:     """
136:     convert file_name to a vector array.
137:
138:     file_name : str
139:         target .wav file
140:
141:     return : numpy.array( numpy.array( float ) )
142:         vector array
143:         * dataset.shape = (dataset_size, feature_vector_length)
144:     """
145:     # calculate the number of dimensions
146:     dims = n_mels * n_frames
147:
148:     # generate melspectrogram using librosa
149:     y, sr = file_load(file_name, mono=mono)
150:
151:     mel_spectrogram = librosa.feature.melspectrogram(y=y,
152:                                                         sr=sr,

--- lines 210-228 ---
210:
211:
212: ########################################################################
213: # get machine IDs
214: ########################################################################
215: def get_section_names(target_dir,
216:                       dir_name,
217:                       ext="wav"):
218:     """
219:     target_dir : str
220:         base directory path
221:     dir_name : str
222:         sub directory name
223:     ext : str (default="wav)
224:         file extension of audio files
225:
226:     return :
227:         section_names : list [ str ]
228:             list of section names extracted from the names of audio files

--- lines 240-258 ---
240:
241:
242: ########################################################################
243: # get the list of wave file paths
244: ########################################################################
245: def file_list_generator(target_dir,
246:                         section_name,
247:                         unique_section_names,
248:                         dir_name,
249:                         mode,
250:                         train,
251:                         prefix_normal="normal",
252:                         prefix_anomaly="anomaly",
253:                         ext="wav"):
254:     """
255:     target_dir : str
256:         base directory path
257:     section_name : str
258:         section name of audio file in <<dir_name>> directory

--- lines 274-292 ---
274:                 * normal/anomaly = 0/1
275:         if the mode is "evaluation":
276:             files : list [ str ]
277:                 audio file list
278:     """
279:     logger.info("target_dir : {}".format(target_dir + "_" + section_name))
280:     condition_array = np.eye(len(unique_section_names))
281:
282:     # development
283:     if mode:
284:         query = os.path.abspath("{target_dir}/{dir_name}/{section_name}_*_{prefix_normal}_*.{ext}".format(target_dir=target_dir,
285:                                                                                                      dir_name=dir_name,
286:                                                                                                      section_name=section_name,
287:                                                                                                      prefix_normal=prefix_normal,
288:                                                                                                      ext=ext))
289:         normal_files = sorted(glob.glob(query))
290:         if len(normal_files) == 0:
291:             normal_files = sorted(
292:                 glob.glob("{dir}/{dir_name}/{prefix_normal}_{id_name}*.{ext}".format(dir=target_dir,

--- lines 294-312 ---
294:                                                                                         prefix_normal=prefix_normal,
295:                                                                                         id_name=section_name,
296:                                                                                         ext=ext)))
297:         normal_labels = np.zeros(len(normal_files))
298:
299:         query = os.path.abspath("{target_dir}/{dir_name}/{section_name}_*_{prefix_normal}_*.{ext}".format(target_dir=target_dir,
300:                                                                                                      dir_name=dir_name,
301:                                                                                                      section_name=section_name,
302:                                                                                                      prefix_normal=prefix_anomaly,
303:                                                                                                      ext=ext))
304:         anomaly_files = sorted(glob.glob(query))
305:         if len(anomaly_files) == 0:
306:             anomaly_files = sorted(
307:                 glob.glob("{dir}/{dir_name}/{prefix_anomaly}_{id_name}*.{ext}".format(dir=target_dir,
308:                                                                                         dir_name=dir_name,
309:                                                                                         prefix_anomaly=prefix_anomaly,
310:                                                                                         id_name=section_name,
311:                                                                                         ext=ext)))
312:         anomaly_labels = np.ones(len(anomaly_files))

--- lines 319-337 ---
319:             logger.exception("no_wav_file!!")
320:         print("\n========================================")
321:
322:     # evaluation
323:     else:
324:         query = os.path.abspath("{target_dir}/{dir_name}/*{section_name}_*.{ext}".format(target_dir=target_dir,
325:                                                                                                      dir_name=dir_name,
326:                                                                                                      section_name=section_name,
327:                                                                                                      ext=ext))
328:         files = sorted(glob.glob(query))
329:         if train:
330:             normal_files = sorted(glob.glob(query))
331:             labels = np.zeros(len(normal_files))
332:         else:
333:             labels = None
334:         logger.info("#files : {num}".format(num=len(files)))
335:         if len(files) == 0:
336:             logger.exception("no_wav_file!!")
337:         print("\n=========================================")

--- lines 344-362 ---
344:
345:     return files, labels, condition
346: ########################################################################
347:
348: def download_raw_data(
349:     target_dir,
350:     dir_name,
351:     machine_type,
352:     data_type,
353:     dataset,
354:     root
355: ):
356:     if dataset == "DCASE2026T2":
357:         download_path_yaml = DOWNLOAD_PATH_YAML_DICT["DCASE2026T2"]
358:     elif dataset == "DCASE2025T2":
359:         download_path_yaml = DOWNLOAD_PATH_YAML_DICT["DCASE2025T2"]
360:     elif dataset == "DCASE2024T2":
361:         download_path_yaml = DOWNLOAD_PATH_YAML_DICT["DCASE2024T2"]
362:     elif dataset == "DCASE2023T2":

--- lines 363-381 ---
363:         download_path_yaml = DOWNLOAD_PATH_YAML_DICT["DCASE2023T2"]
364:     else:
365:         download_path_yaml = DOWNLOAD_PATH_YAML_DICT["legacy"]
366:
367:     if not os.path.exists(target_dir):
368:         os.makedirs(target_dir, exist_ok=True)
369:
370:     with open(download_path_yaml, "r") as f:
371:         file_url = yaml.safe_load(f)[dataset]
372:
373:     lock_file_path = get_lockfile_path(target_dir=target_dir)
374:     if os.path.exists(f"{target_dir}/{dir_name}") and not os.path.isfile(lock_file_path):
375:         print(f"{target_dir}/{dir_name} is already downloaded")
376:         return
377:     print(f"{target_dir}/{dir_name} is not directory.\nperform dataset download.")
378:
379:     lock = fasteners.InterProcessReaderWriterLock(lock_file_path)
380:     try:
381:         lock.acquire_write_lock()

--- lines 382-400 ---
382:     except:
383:         print(f"{target_dir}/{dir_name} is already downloaded")
384:         return
385:
386:     if os.path.exists(f"{target_dir}/{dir_name}"):
387:         print(f"{target_dir}/{dir_name} is already downloaded")
388:         release_write_lock(
389:             lock=lock,
390:             lock_file_path=lock_file_path,
391:         )
392:         return
393:
394:     for i in np.arange(len(file_url[machine_type][data_type])):
395:         zip_file_basename = os.path.basename(file_url[machine_type][data_type][i])
396:         zip_file_path = f"{target_dir}/../{zip_file_basename}"
397:         try:
398:             if not zipfile.is_zipfile(zip_file_path):
399:                 print(f"Downloading...\n\tURL: {file_url[machine_type][data_type][i]}\r\tDownload: {zip_file_path}")
400:                 urllib.request.urlretrieve(

--- lines 404-422 ---
404:                 )
405:         except urllib.error.URLError as e:
406:             print(e)
407:             print("retry dataset download")
408:             download_raw_data(
409:                 target_dir,
410:                 dir_name,
411:                 machine_type,
412:                 data_type,
413:                 dataset,
414:                 root
415:             )
416:             return
417:
418:         with zipfile.ZipFile(zip_file_path, "r") as obj_zip:
419:             zip_infos = obj_zip.infolist()
420:             for zip_info in zip_infos:
421:                 if zip_info.is_dir():
422:                     os.makedirs(f"{target_dir}/../{zip_info.filename}", exist_ok=True)

--- lines 424-442 ---
424:                     sys.stdout.write(f"\runzip: {target_dir}/../{zip_info.filename}")
425:                     obj_zip.extract(zip_info, f"{target_dir}/../")
426:             print("\n")
427:
428:     if dataset == "DCASE2021T2":
429:         test_data_path = f"{target_dir}/test"
430:         split_data_path_list = [
431:             f"{target_dir}/source_test",
432:             f"{target_dir}/target_test",
433:         ]
434:         os.makedirs(test_data_path, exist_ok=True)
435:         for split_data_path in split_data_path_list:
436:             shutil.copytree(split_data_path, test_data_path, dirs_exist_ok=True)
437:
438:     if data_type == "eval" and dir_name == "test":
439:         rename_wav(
440:             dataset_parent_dir=root,
441:             dataset_type=dataset,
442:         )

--- lines 449-467 ---
449:
450: def urllib_progress (block_count, block_size, total_size):
451:     progress_value = block_count * block_size / total_size * 100
452:     sys.stdout.write(f"\r{block_count*block_size/(1024**2):.2f}MB / {total_size/(1024**2):.2f}MB ({progress_value:.2f}%%)")
453:
454: def get_lockfile_path(target_dir):
455:     return f"{target_dir}/lockfile"
456:
457: def release_write_lock(lock, lock_file_path):
458:     print(f"{datetime.datetime.now()}\trelease write lock : {lock_file_path}")
459:     lock.release_write_lock()
460:     if os.path.isfile(lock_file_path):
461:         try:
462:             os.remove(lock_file_path)
463:         except OSError:
464:             print(f"can not remove {lock_file_path}")
465:
466: def release_read_lock(lock, lock_file_path):
467:     print(f"{datetime.datetime.now()}\trelease read lock : {lock_file_path}")

--- lines 494-512 ---
494:     "DCASE2025T2_eval":"datasets/machine_type_2025_eval.yaml",
495:     "DCASE2026T2_dev":"datasets/machine_type_2026_dev.yaml",
496:     "DCASE2026T2_eval":"datasets/machine_type_2026_eval.yaml",
497: }
498:
499: def get_machine_type_dict(dataset_name, mode=True):
500:     if dataset_name in ["DCASE2020T2", "DCASE2021T2", "DCASE2022T2"]:
501:         yaml_path = YAML_PATH["legacy"]
502:     elif dataset_name == "DCASE2023T2" and mode:
503:         yaml_path = YAML_PATH["DCASE2023T2_dev"]
504:     elif dataset_name == "DCASE2023T2" and not mode:
505:         yaml_path = YAML_PATH["DCASE2023T2_eval"]
506:     elif dataset_name == "DCASE2024T2" and mode:
507:         yaml_path = YAML_PATH["DCASE2024T2_dev"]
508:     elif dataset_name == "DCASE2024T2" and not mode:
509:         yaml_path = YAML_PATH["DCASE2024T2_eval"]
510:     elif dataset_name == "DCASE2025T2" and mode:
511:         yaml_path = YAML_PATH["DCASE2025T2_dev"]
512:     elif dataset_name == "DCASE2025T2" and not mode:

In [84]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

for filename in [
    "datasets/machine_type_2026_dev.yaml",
    "baseline.yaml",
]:
    path = repo / filename
    print(f"\n{'=' * 60}\n{filename}\n{'=' * 60}")

    if not path.exists():
        print("File not found")
        continue

    lines = path.read_text().splitlines()

    if "machine_type" in filename:
        matches = [
            i for i, line in enumerate(lines)
            if "bearingEmu" in line or "section_keyword" in line
        ]
        for i in matches:
            start = max(0, i - 5)
            end = min(len(lines), i + 12)
            for j in range(start, end):
                print(f"{j + 1}: {lines[j]}")
            print()
    else:
        print(path.read_text())

============================================================
datasets/machine_type_2026_dev.yaml
============================================================
4:       dev:
5:         - "00"
6:     ToyCar:
7:       dev:
8:         - "00"
9:     bearingEmu:
10:       dev:
11:         - "00"
12:     fan:
13:       dev:
14:         - "00"
15:     gearboxEmu:
16:       dev:
17:         - "00"
18:     sliderEmu:
19:       dev:
20:         - "00"

19:       dev:
20:         - "00"
21:     valveEmu:
22:       dev:
23:         - "00"
24:   section_keyword: section


============================================================
baseline.yaml
============================================================
--dataset_directory: ./data
--result_directory: ./results
--export_dir: baseline

--use_cuda: True
--log_interval: 100
--model: DCASE2023T2-AE
--score: MSE
--seed: 13711
--is_auto_download: False

--max_fpr: 0.1
--decision_threshold: 0.9

# feature
--n_mels: 128
--frames: 5
--frame_hop_length: 1
--n_fft: 1024
--hop_length: 512
--power: 2.0
--fmin: 0.0
--fmax: null
--win_length: null

# fit
--batch_size: 256
--epochs: 100
-lr: 0.001
--shuffle: True
--validation_split: 0.1

In [85]:
from pathlib import Path
import numpy as np
import librosa
import soundfile as sf

wav_path = Path(
    "/content/AURIX_data/bearingEmu/train/"
    "section_00_source_train_normal_0000_noAttribute.wav"
)

audio, sr = sf.read(str(wav_path), dtype="float32")
assert audio.ndim == 2 and audio.shape[1] == 2
assert sr == 16000

def log_mel(channel_audio, sr, n_mels=128, n_fft=1024, hop_length=512):
    mel = librosa.feature.melspectrogram(
        y=channel_audio,
        sr=sr,
        n_mels=n_mels,
        n_fft=n_fft,
        hop_length=hop_length,
        power=2.0,
        fmin=0.0,
        fmax=None,
    )
    return 10.0 * np.log10(np.maximum(mel, np.finfo(float).eps))

mel0 = log_mel(audio[:, 0], sr)
mel1 = log_mel(audio[:, 1], sr)
fused = np.concatenate([mel0, mel1], axis=0)

for name, features in [
    ("Channel 0", mel0),
    ("Channel 1", mel1),
    ("Early fusion", fused),
]:
    print(
        f"{name}: shape={features.shape}, "
        f"finite={np.isfinite(features).all()}, "
        f"mean={features.mean():.4f}, std={features.std():.4f}"
    )

assert mel0.shape == mel1.shape
assert fused.shape[0] == 2 * mel0.shape[0]
assert all(np.isfinite(x).all() for x in [mel0, mel1, fused])

print("\nThree-view feature extraction: PASS")

Channel 0: shape=(128, 313), finite=True, mean=-29.6354, std=6.3221
Channel 1: shape=(128, 313), finite=True, mean=-29.4439, std=6.8433
Early fusion: shape=(256, 313), finite=True, mean=-29.5396, std=6.5886

Three-view feature extraction: PASS

In [86]:
from pathlib import Path

repo = Path("/content/dcase2026_baseline_ae")

print("=== AURIX experiment status ===")

for rel in [
    "train.py",
    "baseline.yaml",
    "datasets/datasets.py",
    "datasets/dcase_dcase202x_t2_loader.py",
]:
    p = repo / rel
    print(f"{'FOUND' if p.exists() else 'MISSING'}: {rel}")

for rel in ["results", "baseline"]:
    p = repo / rel
    if p.exists():
        files = [x for x in p.rglob("*") if x.is_file()]
        print(f"\n{rel}: {len(files)} files")
        for x in files[:10]:
            print(" ", x.relative_to(repo))
    else:
        print(f"\n{rel}: directory not found")

print("\nNo training started by this cell.")

=== AURIX experiment status ===
FOUND: train.py
FOUND: baseline.yaml
FOUND: datasets/datasets.py
FOUND: datasets/dcase_dcase202x_t2_loader.py

results: 2 files
  results/dev_data/.gitignore
  results/eval_data/.gitignore

baseline: directory not found

No training started by this cell.

In [87]:
from pathlib import Path

p = Path("/content/dcase2026_baseline_ae/datasets/datasets.py")
lines = p.read_text().splitlines()

for i, line in enumerate(lines):
    if "train_test_split" in line or "validation_split" in line:
        start = max(0, i - 12)
        end = min(len(lines), i + 13)
        print(f"\n--- {p.name}: lines {start+1}-{end} ---")
        for j in range(start, end):
            print(f"{j+1}: {lines[j]}")

--- datasets.py: lines 1-15 ---
1: import torch
2: from torch.utils.data.dataset import Subset
3: from sklearn.model_selection import train_test_split
4: import sys
5:
6: from datasets.loader_common import get_machine_type_dict
7: from datasets.dcase_dcase202x_t2_loader import DCASE202XT2Loader
8:
9: class DCASE202XT2(object):
10:     def __init__(self, args):
11:         self.width   = args.frames
12:         self.height  = args.n_mels
13:         self.channel = 1
14:         self.input_dim = self.width*self.height*self.channel
15:         shuffle = args.shuffle

--- datasets.py: lines 49-73 ---
49:                 n_fft=args.n_fft,
50:                 hop_length=args.hop_length,
51:                 power=args.power,
52:                 fmax=args.fmax,
53:                 fmin=args.fmin,
54:                 win_length=args.win_length,
55:                 data_type=data_type,
56:                 use_id=args.use_ids,
57:                 is_auto_download=args.is_auto_download,
58:                 mono=args.mono,
59:                 )
60:
61:         train_index, valid_index = train_test_split(range(len(train_data)), test_size=args.validation_split)
62:         self.train_dataset = Subset(train_data, train_index)
63:         self.train_loader = torch.utils.data.DataLoader(
64:             self.train_dataset,
65:             batch_size=batch_size, shuffle=shuffle, batch_sampler=batch_sampler,
66:         )
67:         self.valid_dataset   = Subset(train_data, valid_index)
68:         self.valid_loader = torch.utils.data.DataLoader(
69:             self.valid_dataset,
70:             batch_size=batch_size, shuffle=False, batch_sampler=batch_sampler,
71:         )
72:
73:         self.test_loader = []

In [88]:
from pathlib import Path

p = Path("/content/dcase2026_baseline_ae/datasets/dcase_dcase202x_t2_loader.py")
lines = p.read_text().splitlines()

for i, line in enumerate(lines):
    if "def __getitem__" in line or "def __len__" in line or "def file_list_to_data" in line:
        start = max(0, i - 5)
        end = min(len(lines), i + 35)
        print(f"\n--- {p.name}: lines {start+1}-{end} ---")
        for j in range(start, end):
            print(f"{j+1}: {lines[j]}")

--- dcase_dcase202x_t2_loader.py: lines 297-336 ---
297:                 retry_count=retry_count+1,
298:                 retry_lim=retry_lim,
299:                 retry_delay_time=retry_delay_time+1,
300:             )
301:
302:     def __getitem__(self, index):
303:         """
304:         Returns:
305:             Tensor: input data
306:             Tensor: anomaly label
307:             Tensor: one-hot vector for conditioning (section id)
308:             int: start index
309:             str: file basename
310:         """
311:         return self.getitem_fn(index)
312:
313:     def default_item(self, index):
314:         data = self.data[index]
315:         y_true = self.y_true[index//self.n_vectors_ea_file] if len(self.y_true) > 0 else -1
316:         condition = self.condition[index]
317:         basename = self.basenames[index//self.n_vectors_ea_file]
318:         return data, y_true, condition, basename, index
319:
320:     def __len__(self):
321:         return self.dataset_len
322:
323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,
326:                         n_frames=5,
327:                         n_hop_frames=1,
328:                         n_fft=1024,
329:                         hop_length=512,
330:                         power=2.0,
331:                         fmax=None,
332:                         fmin=None,
333:                         win_length=None,
334:                         mono=True):
335:     """
336:     convert the file_list to a vector array.

--- dcase_dcase202x_t2_loader.py: lines 315-354 ---
315:         y_true = self.y_true[index//self.n_vectors_ea_file] if len(self.y_true) > 0 else -1
316:         condition = self.condition[index]
317:         basename = self.basenames[index//self.n_vectors_ea_file]
318:         return data, y_true, condition, basename, index
319:
320:     def __len__(self):
321:         return self.dataset_len
322:
323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,
326:                         n_frames=5,
327:                         n_hop_frames=1,
328:                         n_fft=1024,
329:                         hop_length=512,
330:                         power=2.0,
331:                         fmax=None,
332:                         fmin=None,
333:                         win_length=None,
334:                         mono=True):
335:     """
336:     convert the file_list to a vector array.
337:     file_to_vector_array() is iterated, and the output vector array is concatenated.
338:
339:     file_list : list [ str ]
340:         .wav filename list of dataset
341:     msg : str ( default = "calc..." )
342:         description for tqdm.
343:         this parameter will be input into "desc" param at tqdm.
344:
345:     return : numpy.array( numpy.array( float ) )
346:         data for training (this function is not used for test.)
347:         * dataset.shape = (number of feature vectors, dimensions of feature vectors)
348:     """
349:     # calculate the number of dimensions
350:     dims = n_mels * n_frames
351:
352:     # iterate file_to_vector_array()
353:     for idx in tqdm(range(len(file_list)), desc=msg):
354:         vectors = com.file_to_vectors(file_list[idx],

--- dcase_dcase202x_t2_loader.py: lines 318-357 ---
318:         return data, y_true, condition, basename, index
319:
320:     def __len__(self):
321:         return self.dataset_len
322:
323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,
326:                         n_frames=5,
327:                         n_hop_frames=1,
328:                         n_fft=1024,
329:                         hop_length=512,
330:                         power=2.0,
331:                         fmax=None,
332:                         fmin=None,
333:                         win_length=None,
334:                         mono=True):
335:     """
336:     convert the file_list to a vector array.
337:     file_to_vector_array() is iterated, and the output vector array is concatenated.
338:
339:     file_list : list [ str ]
340:         .wav filename list of dataset
341:     msg : str ( default = "calc..." )
342:         description for tqdm.
343:         this parameter will be input into "desc" param at tqdm.
344:
345:     return : numpy.array( numpy.array( float ) )
346:         data for training (this function is not used for test.)
347:         * dataset.shape = (number of feature vectors, dimensions of feature vectors)
348:     """
349:     # calculate the number of dimensions
350:     dims = n_mels * n_frames
351:
352:     # iterate file_to_vector_array()
353:     for idx in tqdm(range(len(file_list)), desc=msg):
354:         vectors = com.file_to_vectors(file_list[idx],
355:                                                 n_mels=n_mels,
356:                                                 n_frames=n_frames,
357:                                                 n_fft=n_fft,

In [90]:
from pathlib import Path

p = Path("/content/dcase2026_baseline_ae/train.py")
lines = p.read_text().splitlines()

for i, line in enumerate(lines):
    if "train_loader" in line or "valid_loader" in line or "valid_dataset" in line:
        start = max(0, i - 8)
        end = min(len(lines), i + 13)
        print(f"\n--- train.py: lines {start+1}-{end} ---")
        for j in range(start, end):
            print(f"{j+1}: {lines[j]}")

In [91]:
from pathlib import Path

p = Path("/content/dcase2026_baseline_ae/train.py")

if not p.exists():
    print("ERROR: train.py not found")
else:
    lines = p.read_text().splitlines()
    print(f"train.py — {len(lines)} lines total\n")

    start = max(0, len(lines) - 100)
    for i in range(start, len(lines)):
        print(f"{i+1}: {lines[i]}")

train.py — 67 lines total

1: import random
2: import numpy as np
3: import torch
4:
5: # original lib
6: import common as com
7: from networks.models import Models
8:
9: ########################################################################
10: # load parameter.yaml
11: ########################################################################
12: param = com.yaml_load()
13: ########################################################################
14:
15: def main():
16:     parser = com.get_argparse()
17:     # read parameters from yaml
18:     flat_param = com.param_to_args_list(params=param)
19:     args = parser.parse_args(args=flat_param)
20:     # read parameters from command line
21:     args = parser.parse_args(namespace=args)
22:     print(args)
23:
24:     if args.train_only and args.test_only:
25:         raise ValueError("--train_only and --test_only cannot be used together.")
26:     elif args.train_only:
27:         train = True
28:         test = False
29:     elif args.test_only:
30:         train = False
31:         test = True
32:     else:
33:         train = True
34:         test = True
35:
36:     args.cuda = args.use_cuda and torch.cuda.is_available()
37:
38:     # Python random
39:     random.seed(args.seed)
40:     # Numpy
41:     np.random.seed(args.seed)
42:     # Pytorch
43:     torch.manual_seed(args.seed)
44:     torch.cuda.manual_seed(args.seed)
45:     torch.backends.cudnn.deterministic = True
46:     torch.use_deterministic_algorithms = True
47:
48:     net = Models(args.model).net(
49:         args=args,
50:         train=train,
51:         test=test
52:     )
53:
54:
55:     print(args.model)
56:
57:     print("============== BEGIN TRAIN ==============")
58:     if train:
59:         for epoch in range(1, args.epochs + 2):
60:             net.train(epoch)
61:     print("============ END OF TRAIN ============")
62:
63:     if test:
64:         net.test()
65:
66: if __name__ == "__main__":
67:     main()

In [92]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")
matches = list(root.glob("networks/**/base_model.py"))

print("Files found:", len(matches))
for p in matches:
    lines = p.read_text().splitlines()
    print(f"\nFILE: {p}")
    for i, line in enumerate(lines):
        if "def train(" in line:
            start = max(0, i - 5)
            end = min(len(lines), i + 75)
            for j in range(start, end):
                print(f"{j+1}: {lines[j]}")
            break

Files found: 1

FILE: /content/dcase2026_baseline_ae/networks/base_model.py
146:             shape_hat, loc_hat, scale_hat = pickle.load(f)
147:
148:         # determine threshold for decision
149:         return scipy.stats.gamma.ppf(q=self.args.decision_threshold, a=shape_hat, loc=loc_hat, scale=scale_hat)
150:
151:     def train(self, epoch):
152:         pass
153:
154:     def test(self):
155:         pass
156:
157:     def copy_eval_data_score(self, decision_result_csv_path, anomaly_score_csv_path):
158:         eval_data_decision_result_csv_path = self.eval_data_result_dir / os.path.basename(decision_result_csv_path).replace(self.model_name_suffix, "")
159:         print(f"copy decision result: {decision_result_csv_path}\n\t->{eval_data_decision_result_csv_path}")
160:         shutil.copyfile(decision_result_csv_path, eval_data_decision_result_csv_path)
161:
162:         eval_data_anomaly_score_csv_path = self.eval_data_result_dir / os.path.basename(anomaly_score_csv_path).replace(self.model_name_suffix, "")
163:         print(f"copy anomaly score: {anomaly_score_csv_path}\n\t->{eval_data_anomaly_score_csv_path}")
164:         shutil.copyfile(anomaly_score_csv_path, eval_data_anomaly_score_csv_path)

In [93]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae/networks")

for p in root.rglob("*.py"):
    content = p.read_text(errors="replace")
    if "def train(self, epoch)" in content:
        lines = content.splitlines()
        print(f"\nFILE: {p}")
        for i, line in enumerate(lines):
            if "def train(self, epoch)" in line:
                start = max(0, i - 5)
                end = min(len(lines), i + 100)
                for j in range(start, end):
                    print(f"{j+1}: {lines[j]}")
                break

FILE: /content/dcase2026_baseline_ae/networks/base_model.py
146:             shape_hat, loc_hat, scale_hat = pickle.load(f)
147:
148:         # determine threshold for decision
149:         return scipy.stats.gamma.ppf(q=self.args.decision_threshold, a=shape_hat, loc=loc_hat, scale=scale_hat)
150:
151:     def train(self, epoch):
152:         pass
153:
154:     def test(self):
155:         pass
156:
157:     def copy_eval_data_score(self, decision_result_csv_path, anomaly_score_csv_path):
158:         eval_data_decision_result_csv_path = self.eval_data_result_dir / os.path.basename(decision_result_csv_path).replace(self.model_name_suffix, "")
159:         print(f"copy decision result: {decision_result_csv_path}\n\t->{eval_data_decision_result_csv_path}")
160:         shutil.copyfile(decision_result_csv_path, eval_data_decision_result_csv_path)
161:
162:         eval_data_anomaly_score_csv_path = self.eval_data_result_dir / os.path.basename(anomaly_score_csv_path).replace(self.model_name_suffix, "")
163:         print(f"copy anomaly score: {anomaly_score_csv_path}\n\t->{eval_data_anomaly_score_csv_path}")
164:         shutil.copyfile(anomaly_score_csv_path, eval_data_anomaly_score_csv_path)

FILE: /content/dcase2026_baseline_ae/networks/dcase2023t2_ae/dcase2023t2_ae.py
39:                 ["recon_loss"],
40:                 ["recon_loss_source", "recon_loss_target"],
41:         ]
42:         return "loss,val_loss,recon_loss,recon_loss_source,recon_loss_target"
43:
44:     def train(self, epoch):
45:         if epoch <= self.epoch:
46:             return
47:         torch.autograd.set_detect_anomaly(True)
48:         train_loss = 0
49:         train_recon_loss = 0
50:         train_recon_loss_source = 0
51:         train_recon_loss_target = 0
52:         y_pred = []
53:
54:         train_loader = self.train_loader
55:
56:         if epoch == self.args.epochs + 1:
57:             print("\n============== CALCULATE COVARIANCE ==============")
58:             is_calc_cov = True
59:             self.model.eval()
60:             torch.set_grad_enabled(False)
61:             # initialize mahalanobis param
62:             cov_x_source = np.zeros((self.block_size, self.block_size))
63:             cov_x_source = torch.from_numpy(cov_x_source)
64:             cov_x_source = cov_x_source.to(self.device).float()
65:             cov_x_target = cov_x_source.clone().detach()
66:             num_source = 0
67:             num_target = 0
68:             epoch = self.args.epochs
69:         else:
70:             self.model.train()
71:             is_calc_cov = False
72:
73:         for batch_idx, batch in enumerate(tqdm(train_loader)):
74:             data = batch[0]
75:             data = data.to(self.device).float()
76:             if data.shape[0] <= 1:
77:                 continue
78:             data_name_list = batch[3]
79:             machine_id = torch.argmax(batch[2], dim=1).long()
80:             machine_id = machine_id.to(self.device)
81:
82:             is_target_list = ["target" in data_name for data_name in data_name_list]
83:             is_source_list = np.logical_not(is_target_list).tolist()
84:             n_source = is_source_list.count(True)
85:             n_target = is_target_list.count(True)
86:
87:             if not is_calc_cov:
88:                 self.optimizer.zero_grad()
89:             recon_batch, z = self.model(data)
90:
91:             if is_calc_cov:
92:                 score_2d, cov_diff_source, cov_diff_target = loss_function_mahala(
93:                     recon_x=recon_batch,
94:                     x=data,
95:                     block_size=self.block_size,
96:                     update_cov=True,
97:                     reduction=False,
98:                     is_source_list=is_source_list,
99:                     is_target_list=is_target_list
100:                 )
101:                 cov_x_source_batch = cov_v(
102:                     diff=cov_diff_source,
103:                     num=1
104:                 )
105:                 cov_x_source += cov_x_source_batch.clone().detach()
106:                 num_source += n_source
107:                 if n_target > 0:
108:                     cov_x_target_batch = cov_v(
109:                         diff=cov_diff_target,
110:                         num=1
111:                     )
112:                     cov_x_target += cov_x_target_batch.clone().detach()
113:                     num_target += n_target
114:             else:
115:                 score_2d = self.loss_fn(
116:                     recon_batch,
117:                     data
118:                 )
119:
120:             # loss reduction
121:             n_loss = len(score_2d)
122:             score = self.loss_reduction_1d(score=score_2d)
123:
124:             recon_loss = self.loss_reduction(score=score, n_loss=n_loss)
125:             recon_loss_source = self.loss_reduction(score=score[is_source_list], n_loss=n_source)
126:             if n_target > 0:
127:                 recon_loss_target = self.loss_reduction(score=score[is_target_list], n_loss=n_target)
128:             else:
129:                 recon_loss_target = 0
130:
131:             self.loss = recon_loss
132:             if not is_calc_cov:
133:                 self.loss.backward()
134:                 self.optimizer.step()
135:             train_loss += float(self.loss)
136:             train_recon_loss += float(recon_loss)
137:             train_recon_loss_source += float(recon_loss_source)
138:             train_recon_loss_target += float(recon_loss_target)
139:
140:
141:             # calculate y_pred for fitting anomaly score distribution
142:             y_pred.append(self.loss.item())
143:

In [94]:
from pathlib import Path

p = Path(
    "/content/dcase2026_baseline_ae/networks/"
    "dcase2023t2_ae/dcase2023t2_ae.py"
)
lines = p.read_text().splitlines()

for i in range(135, min(len(lines), 245)):
    print(f"{i+1}: {lines[i]}")

136:             train_recon_loss += float(recon_loss)
137:             train_recon_loss_source += float(recon_loss_source)
138:             train_recon_loss_target += float(recon_loss_target)
139:
140:
141:             # calculate y_pred for fitting anomaly score distribution
142:             y_pred.append(self.loss.item())
143:
144:             if batch_idx % self.args.log_interval == 0 and not is_calc_cov:
145:                 print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
146:                     epoch, batch_idx * len(data), len(train_loader.dataset),
147:                     100. * batch_idx / len(train_loader),
148:                     self.loss.item()))
149:
150:         if is_calc_cov:
151:             # save cov_x
152:             cov_x_source /= num_source - 1
153:             if num_target == 0:
154:                 cov_x_target = cov_x_source.clone().detach()
155:             else:
156:                 cov_x_target /= num_target - 1
157:             self.model.cov_source.data = cov_x_source
158:             self.model.cov_target.data = cov_x_target
159:
160:             inv_cov_source, inv_cov_target = calc_inv_cov(
161:                 model=self.model,
162:                 device=self.device
163:             )
164:             y_pred_mahala = []
165:             for batch_idx, batch in enumerate(tqdm(train_loader)):
166:                 y_pred_mahala = self.calc_valid_mahala_score(
167:                     data=batch[0],
168:                     y_pred=y_pred_mahala,
169:                     inv_cov_source=inv_cov_source,
170:                     inv_cov_target=inv_cov_target,
171:                 )
172:             for batch_idx, batch in enumerate(self.valid_loader):
173:                 y_pred_mahala = self.calc_valid_mahala_score(
174:                     data=batch[0],
175:                     y_pred=y_pred_mahala,
176:                     inv_cov_source=inv_cov_source,
177:                     inv_cov_target=inv_cov_target,
178:                 )
179:             self.fit_anomaly_score_distribution(
180:                 y_pred=y_pred_mahala,
181:                 score_distr_file_path=self.mahala_score_distr_file_path
182:             )
183:
184:         # validation test
185:         val_loss = 0
186:         with torch.no_grad():
187:             self.model.eval()
188:             for batch_idx, batch in enumerate(self.valid_loader):
189:                 data = batch[0]
190:                 data = data.to(self.device).float()
191:
192:                 recon_batch, _ = self.model(data)
193:                 score = self.loss_fn(
194:                     recon_batch,
195:                     data
196:                 )
197:                 loss = score.mean()
198:
199:                 val_loss += float(loss)
200:
201:                 # calculate y_pred for fitting anomaly score distribution
202:                 y_pred.append(loss.item())
203:
204:         if not is_calc_cov:
205:             # plot train log
206:             print('====> Epoch: {} Average loss: {:.4f} Validation loss: {:.4f}'.format(
207:                   epoch,
208:                   train_loss / len(train_loader),
209:                   val_loss / len(self.valid_loader)))
210:             with open(self.log_path, 'a') as log:
211:                 np.savetxt(log,["{0},{1},{2},{3},{4}".format(
212:                     train_loss / len(train_loader),
213:                     val_loss / len(self.valid_loader),
214:                     train_recon_loss / len(train_loader),
215:                     train_recon_loss_source / len(train_loader),
216:                     train_recon_loss_target / len(train_loader),
217:                     )],fmt="%s")
218:             csv_to_figdata(
219:                 file_path=self.log_path,
220:                 column_heading_list=self.column_heading_list,
221:                 ylabel="loss",
222:                 fig_count=len(self.column_heading_list),
223:                 cut_first_epoch=True
224:             )
225:             self.fit_anomaly_score_distribution(
226:                 y_pred=y_pred,
227:                 score_distr_file_path=self.mse_score_distr_file_path
228:             )
229:
230:         # save model
231:         torch.save(self.model.state_dict(), self.model_path)
232:         torch.save({
233:             'epoch':epoch,
234:             'model_state_dict':self.model.state_dict(),
235:             'optimizer_state_dict':self.optimizer.state_dict(),
236:             'loss':self.loss
237:         }, self.checkpoint_path)
238:
239:     def calc_valid_mahala_score(self, data, y_pred, inv_cov_source, inv_cov_target):
240:         data = data.to(self.device).float()
241:         recon_data, _ = self.model(data)
242:         loss_source, num = loss_function_mahala(
243:             recon_x=recon_data,
244:             x=data,
245:             block_size=self.block_size,

In [95]:

from pathlib import Path
import csv
import random

data_dir = Path("/content/AURIX_data/bearingEmu/train")
out_dir = Path("/content/AURIX.V1/experiments")
manifest = out_dir / "recording_split_seed13711.csv"
seed = 13711

if not data_dir.exists():
    raise FileNotFoundError(f"Training directory not found: {data_dir}")

files = sorted(data_dir.glob("*.wav"))
if len(files) != 1000:
    raise ValueError(f"Expected 1000 training WAVs, found {len(files)}")

# Confirm that this experiment uses normal training recordings only.
if any("_anomaly_" in f.name.lower() for f in files):
    raise ValueError("Anomaly recording found in training directory.")

groups = {"source": [], "target": []}

for f in files:
    name = f.name.lower()
    if "_source_train_normal_" in name:
        groups["source"].append(f.name)
    elif "_target_train_normal_" in name:
        groups["target"].append(f.name)
    else:
        raise ValueError(f"Unrecognized training filename: {f.name}")

if len(groups["source"]) != 990 or len(groups["target"]) != 10:
    raise ValueError(
        f"Unexpected domain counts: "
        f"source={len(groups['source'])}, target={len(groups['target'])}"
    )

# Keep the split deterministic and separate by domain.
rng = random.Random(seed)
rows = []

for domain, names in groups.items():
    names = names.copy()
    rng.shuffle(names)

    # 10% source validation; 2 of the 10 target recordings for validation.
    n_valid = round(0.10 * len(names))
    if domain == "target":
        n_valid = 2

    valid_names = set(names[:n_valid])

    for name in sorted(names):
        rows.append({
            "filename": name,
            "domain": domain,
            "split": "validation" if name in valid_names else "train",
            "label": "normal",
            "seed": seed,
        })

# Verify no recording can occur in both splits.
train_names = {r["filename"] for r in rows if r["split"] == "train"}
valid_names = {r["filename"] for r in rows if r["split"] == "validation"}

assert train_names.isdisjoint(valid_names)
assert len(train_names) + len(valid_names) == 1000
assert len(valid_names) == 101
assert sum(r["split"] == "validation" and r["domain"] == "target"
           for r in rows) == 2

out_dir.mkdir(parents=True, exist_ok=True)

if manifest.exists():
    # Preserve an existing experiment artifact rather than silently replacing it.
    with manifest.open(newline="", encoding="utf-8") as f:
        existing = list(csv.DictReader(f))
    if len(existing) != 1000:
        raise ValueError(f"Existing manifest has {len(existing)} rows; inspect it before replacing.")
    print(f"Existing manifest preserved: {manifest}")
else:
    with manifest.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f, fieldnames=["filename", "domain", "split", "label", "seed"]
        )
        writer.writeheader()
        writer.writerows(rows)
    print(f"Created manifest: {manifest}")

print("\nExpected split:")
print(f"Train:      {len(train_names)} recordings")
print(f"Validation: {len(valid_names)} recordings")
print(f"Source validation: 99")
print(f"Target validation: 2")
print("Test files accessed: 0")
print("Recording-level overlap: 0")

Created manifest: /content/AURIX.V1/experiments/recording_split_seed13711.csv

Expected split:
Train:      899 recordings
Validation: 101 recordings
Source validation: 99
Target validation: 2
Test files accessed: 0
Recording-level overlap: 0

In [96]:

from pathlib import Path
import csv
import numpy as np
import soundfile as sf
import librosa

root = Path("/content/AURIX_data/bearingEmu/train")
manifest = Path("/content/AURIX.V1/experiments/recording_split_seed13711.csv")

with manifest.open(newline="", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))

train_rows = [r for r in rows if r["split"] == "train"]
valid_rows = [r for r in rows if r["split"] == "validation"]

assert len(rows) == 1000
assert not ({r["filename"] for r in train_rows}
            & {r["filename"] for r in valid_rows})

def extract_views(path):
    audio, sr = sf.read(str(path), dtype="float32")
    assert sr == 16000 and audio.ndim == 2 and audio.shape[1] == 2

    views = []
    for channel in (0, 1):
        mel = librosa.feature.melspectrogram(
            y=audio[:, channel],
            sr=sr,
            n_mels=128,
            n_fft=1024,
            hop_length=512,
            power=2.0,
        )
        log_mel = 10 * np.log10(np.maximum(mel, np.finfo(np.float32).eps))
        views.append(log_mel)

    assert views[0].shape == views[1].shape
    fused = np.concatenate(views, axis=0)

    return views[0], views[1], fused

samples = [
    ("train", train_rows[0]),
    ("train", train_rows[1]),
    ("validation", valid_rows[0]),
    ("validation", valid_rows[1]),
]

for split, row in samples:
    path = root / row["filename"]
    if not path.is_file():
        raise FileNotFoundError(path)

    ch0, ch1, fused = extract_views(path)

    print(
        f"{split:10s} | {row['domain']:6s} | {path.name}\n"
        f"  ch0={ch0.shape}, ch1={ch1.shape}, fusion={fused.shape}\n"
        f"  finite={all(np.isfinite(x).all() for x in (ch0, ch1, fused))}"
    )

print("\nManifest and multi-recording feature smoke test: PASS")
print("No model training performed.")

train      | source | section_00_source_train_normal_0000_noAttribute.wav
  ch0=(128, 313), ch1=(128, 313), fusion=(256, 313)
  finite=True
train      | source | section_00_source_train_normal_0001_noAttribute.wav
  ch0=(128, 313), ch1=(128, 313), fusion=(256, 313)
  finite=True
validation | source | section_00_source_train_normal_0006_noAttribute.wav
  ch0=(128, 313), ch1=(128, 313), fusion=(256, 313)
  finite=True
validation | source | section_00_source_train_normal_0012_noAttribute.wav
  ch0=(128, 313), ch1=(128, 313), fusion=(256, 313)
  finite=True

Manifest and multi-recording feature smoke test: PASS
No model training performed.

In [97]:

from pathlib import Path
import csv, json, random
import numpy as np
import soundfile as sf
import librosa
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

SEED = 13711
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.set_num_threads(2)
device = torch.device("cpu")

data_dir = Path("/content/AURIX_data/bearingEmu/train")
exp_dir = Path("/content/AURIX.V1/experiments")
manifest = exp_dir / "recording_split_seed13711.csv"
exp_dir.mkdir(parents=True, exist_ok=True)

with manifest.open(newline="", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))

train_rows = [
    r for r in rows
    if r["split"] == "train" and r["domain"] == "source"
]
valid_rows = [
    r for r in rows
    if r["split"] == "validation" and r["domain"] == "source"
]

rng = random.Random(SEED)
rng.shuffle(train_rows)
rng.shuffle(valid_rows)
train_rows = train_rows[:20]
valid_rows = valid_rows[:5]

def channel0_vectors(filename):
    path = data_dir / filename
    audio, sr = sf.read(str(path), dtype="float32")
    if sr != 16000 or audio.ndim != 2 or audio.shape[1] != 2:
        raise ValueError(f"Unexpected audio format: {filename}")

    mel = librosa.feature.melspectrogram(
        y=audio[:, 0], sr=sr, n_mels=128,
        n_fft=1024, hop_length=512, power=2.0
    )
    log_mel = 10 * np.log10(
        np.maximum(mel, np.finfo(np.float32).eps)
    )

    # Each example contains 5 consecutive frames: 128 x 5 = 640.
    windows = np.stack(
        [log_mel[:, i:i+5].reshape(-1)
         for i in range(log_mel.shape[1] - 4)],
        axis=0
    )
    return windows.astype(np.float32)

print("Extracting pilot training features...")
train_arrays = [channel0_vectors(r["filename"]) for r in train_rows]
print("Extracting pilot validation features...")
valid_arrays = [channel0_vectors(r["filename"]) for r in valid_rows]

# Normalize using training data only to avoid validation leakage.
train_raw = np.concatenate(train_arrays)
mean = train_raw.mean(axis=0, keepdims=True)
std = train_raw.std(axis=0, keepdims=True)
std[std < 1e-6] = 1.0

train_x = (train_raw - mean) / std
valid_x = [(x - mean) / std for x in valid_arrays]

train_tensor = torch.from_numpy(train_x)
loader = DataLoader(
    TensorDataset(train_tensor),
    batch_size=256,
    shuffle=True,
    generator=torch.Generator().manual_seed(SEED)
)

model = nn.Sequential(
    nn.Linear(640, 128),
    nn.ReLU(),
    nn.Linear(128, 32),
    nn.ReLU(),
    nn.Linear(32, 128),
    nn.ReLU(),
    nn.Linear(128, 640)
).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.MSELoss()

model.train()
batch_losses = []
for (batch,) in loader:
    optimizer.zero_grad()
    reconstructed = model(batch)
    loss = criterion(reconstructed, batch)
    loss.backward()
    optimizer.step()
    batch_losses.append(loss.item())

model.eval()
record_scores = []
with torch.no_grad():
    for row, x in zip(valid_rows, valid_x):
        x_tensor = torch.from_numpy(x)
        pred = model(x_tensor)
        score = ((pred - x_tensor) ** 2).mean(dim=1).mean().item()
        record_scores.append({
            "filename": row["filename"],
            "domain": row["domain"],
            "split": "validation",
            "label": "normal",
            "mean_reconstruction_error": score
        })

tag = "pilot_channel0_seed13711"
torch.save({
    "model_state_dict": model.state_dict(),
    "normalization_mean": mean,
    "normalization_std": std,
    "input_dim": 640,
    "seed": SEED,
    "train_recordings": [r["filename"] for r in train_rows],
    "validation_recordings": [r["filename"] for r in valid_rows],
}, exp_dir / f"{tag}.pt")

with (exp_dir / f"{tag}_validation_scores.csv").open(
    "w", newline="", encoding="utf-8"
) as f:
    writer = csv.DictWriter(f, fieldnames=list(record_scores[0].keys()))
    writer.writeheader()
    writer.writerows(record_scores)

summary = {
    "experiment": tag,
    "device": str(device),
    "epochs": 1,
    "train_recordings": len(train_rows),
    "validation_recordings": len(valid_rows),
    "train_feature_vectors": int(len(train_x)),
    "mean_train_batch_mse": float(np.mean(batch_losses)),
    "mean_validation_recording_error": float(
        np.mean([r["mean_reconstruction_error"] for r in record_scores])
    ),
    "warning": "Pilot only; not a final anomaly-detection result."
}
with (exp_dir / f"{tag}_summary.json").open("w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2)

print("\nPILOT TRAINING COMPLETE")
print(json.dumps(summary, indent=2))
print("Saved artifacts in:", exp_dir)

Extracting pilot training features...
Extracting pilot validation features...

PILOT TRAINING COMPLETE
{
  "experiment": "pilot_channel0_seed13711",
  "device": "cpu",
  "epochs": 1,
  "train_recordings": 20,
  "validation_recordings": 5,
  "train_feature_vectors": 6180,
  "mean_train_batch_mse": 0.8511655712127686,
  "mean_validation_recording_error": 0.6928335309028626,
  "warning": "Pilot only; not a final anomaly-detection result."
}
Saved artifacts in: /content/AURIX.V1/experiments

In [98]:
from pathlib import Path

folder = Path("/content/AURIX.V1/experiments")

print("Files saved in experiments:")
for file in sorted(folder.iterdir()):
    print(file.name)

Files saved in experiments:
pilot_channel0_seed13711.pt
pilot_channel0_seed13711_summary.json
pilot_channel0_seed13711_validation_scores.csv
recording_split_seed13711.csv

In [99]:

from pathlib import Path
import json

folder = Path("/content/AURIX.V1/experiments")

summary_file = folder / "pilot_channel0_seed13711_summary.json"
model_file = folder / "pilot_channel0_seed13711.pt"
split_file = folder / "recording_split_seed13711.csv"

for path in [summary_file, model_file, split_file]:
    print(f"{path.name}: {' موجود ✅' if path.exists() else 'مش موجود ❌'}")

print("\n--- Pilot summary ---")
if summary_file.exists():
    print(json.dumps(json.loads(summary_file.read_text()), indent=2, ensure_ascii=False))

pilot_channel0_seed13711_summary.json:  موجود ✅
pilot_channel0_seed13711.pt:  موجود ✅
recording_split_seed13711.csv:  موجود ✅

--- Pilot summary ---
{
  "experiment": "pilot_channel0_seed13711",
  "device": "cpu",
  "epochs": 1,
  "train_recordings": 20,
  "validation_recordings": 5,
  "train_feature_vectors": 6180,
  "mean_train_batch_mse": 0.8511655712127686,
  "mean_validation_recording_error": 0.6928335309028626,
  "warning": "Pilot only; not a final anomaly-detection result."
}

In [101]:
import torch
from pathlib import Path

p = Path("/content/AURIX.V1/experiments/pilot_channel0_seed13711.pt")
checkpoint = torch.load(p, map_location="cpu", weights_only=False)

print("Checkpoint type:", type(checkpoint).__name__)

if isinstance(checkpoint, dict):
    print("Checkpoint keys:", list(checkpoint.keys()))

    state = checkpoint.get("state_dict", checkpoint.get("model_state_dict", checkpoint))

    if isinstance(state, dict):
        print("\nModel parameter shapes:")
        for name, value in state.items():
            if torch.is_tensor(value):
                print(f"{name}: {tuple(value.shape)}")
else:
    print(checkpoint)

Checkpoint type: dict
Checkpoint keys: ['model_state_dict', 'normalization_mean', 'normalization_std', 'input_dim', 'seed', 'train_recordings', 'validation_recordings']

Model parameter shapes:
0.weight: (128, 640)
0.bias: (128,)
2.weight: (32, 128)
2.bias: (32,)
4.weight: (128, 32)
4.bias: (128,)
6.weight: (640, 128)
6.bias: (640,)

In [102]:

from pathlib import Path

project = Path("/content/AURIX.V1")

# Search the existing notebook for the pilot's original training code
notebooks = list(project.glob("*.ipynb"))

for notebook in notebooks:
    print(f"Notebook found: {notebook.name}")

print("\nProject folder:", project.exists())
print("Pilot model:", (project / "experiments/pilot_channel0_seed13711.pt").exists())

Notebook found: AURIX.ipynb

Project folder: True
Pilot model: True

In [104]:

import json
from pathlib import Path

notebook = Path("/content/AURIX.V1/AURIX.ipynb")
data = json.loads(notebook.read_text(encoding="utf-8"))

for i, cell in enumerate(data.get("cells", [])):
    if cell.get("cell_type") != "code":
        continue

    source = "".join(cell.get("source", []))
    keywords = (
        "pilot_channel0_seed13711",
        "mean_train_batch_mse",
        "normalization_mean",
        "melspectrogram",
        "def extract_views",
    )

    if any(word in source for word in keywords):
        print(f"\n{'=' * 20} CELL {i} {'=' * 20}")
        print(source[:9000])

In [106]:
from pathlib import Path

root = Path("/content/AURIX.V1")

for p in sorted(root.glob("**/*.py")):
    if any(word in str(p).lower() for word in ("pilot", "train", "model")):
        print(p)

In [107]:
from pathlib import Path
import json

p = Path("/content/AURIX.V1/experiments/pilot_channel0_seed13711.pt")
checkpoint = __import__("torch").load(
    p, map_location="cpu", weights_only=False
)

print("Model input dimension:", checkpoint["input_dim"])
print("Saved training recordings:", checkpoint["train_recordings"])
print("Saved validation recordings:", checkpoint["validation_recordings"])
print("Normalization mean shape:", tuple(checkpoint["normalization_mean"].shape))
print("Normalization std shape:", tuple(checkpoint["normalization_std"].shape))
print("Original model remains saved:", p.exists())

Model input dimension: 640
Saved training recordings: ['section_00_source_train_normal_0837_noAttribute.wav', 'section_00_source_train_normal_0377_noAttribute.wav', 'section_00_source_train_normal_0312_noAttribute.wav', 'section_00_source_train_normal_0859_noAttribute.wav', 'section_00_source_train_normal_0445_noAttribute.wav', 'section_00_source_train_normal_0986_noAttribute.wav', 'section_00_source_train_normal_0577_noAttribute.wav', 'section_00_source_train_normal_0372_noAttribute.wav', 'section_00_source_train_normal_0191_noAttribute.wav', 'section_00_source_train_normal_0519_noAttribute.wav', 'section_00_source_train_normal_0397_noAttribute.wav', 'section_00_source_train_normal_0316_noAttribute.wav', 'section_00_source_train_normal_0935_noAttribute.wav', 'section_00_source_train_normal_0954_noAttribute.wav', 'section_00_source_train_normal_0947_noAttribute.wav', 'section_00_source_train_normal_0556_noAttribute.wav', 'section_00_source_train_normal_0816_noAttribute.wav', 'section_00_source_train_normal_0290_noAttribute.wav', 'section_00_source_train_normal_0158_noAttribute.wav', 'section_00_source_train_normal_0015_noAttribute.wav']
Saved validation recordings: ['section_00_source_train_normal_0386_noAttribute.wav', 'section_00_source_train_normal_0023_noAttribute.wav', 'section_00_source_train_normal_0029_noAttribute.wav', 'section_00_source_train_normal_0820_noAttribute.wav', 'section_00_source_train_normal_0278_noAttribute.wav']
Normalization mean shape: (1, 640)
Normalization std shape: (1, 640)
Original model remains saved: True

In [108]:

from pathlib import Path
import json
import random

import numpy as np
import soundfile as sf
import librosa
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

# AURIX: channel 1 pilot, preserving the original channel 0 artifacts
SEED = 13711
ROOT = Path("/content/AURIX_data/bearingEmu/train")
OUT = Path("/content/AURIX.V1/experiments")
ORIGINAL = OUT / "pilot_channel0_seed13711.pt"
NEW_MODEL = OUT / "pilot_channel1_seed13711.pt"
NEW_SUMMARY = OUT / "pilot_channel1_seed13711_summary.json"
NEW_SCORES = OUT / "pilot_channel1_seed13711_validation_scores.csv"

assert ORIGINAL.is_file(), "Original pilot checkpoint is missing."
assert ROOT.is_dir(), "Training audio folder is missing."
assert not NEW_MODEL.exists(), "Channel 1 pilot already exists; refusing to overwrite it."

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
device = torch.device("cpu")

old = torch.load(ORIGINAL, map_location="cpu", weights_only=False)
train_names = old["train_recordings"]
valid_names = old["validation_recordings"]
assert len(train_names) == 20 and len(valid_names) == 5
assert not set(train_names) & set(valid_names)

def features(filename):
    audio, sr = sf.read(str(ROOT / filename), dtype="float32")
    assert sr == 16000 and audio.ndim == 2 and audio.shape[1] == 2

    # Channel 1 (second audio channel), same feature dimensions as pilot
    y = audio[:, 1]
    mel = librosa.feature.melspectrogram(
        y=y, sr=sr, n_mels=128, n_fft=1024,
        hop_length=512, power=2.0
    )
    logmel = 10 * np.log10(np.maximum(mel, np.finfo(np.float32).eps))

    # Stack five consecutive frames: 128 x 5 = 640 features
    x = np.stack(
        [logmel[:, i:i+5].T.reshape(-1)
         for i in range(logmel.shape[1] - 4)],
        axis=0
    ).astype(np.float32)
    assert x.shape[1] == 640 and np.isfinite(x).all()
    return x

print("Extracting channel 1 pilot training features...")
train_arrays = [features(n) for n in train_names]
print("Extracting channel 1 pilot validation features...")
valid_arrays = [features(n) for n in valid_names]

# Fit normalization using training recordings only
mean = np.concatenate(train_arrays, axis=0).mean(axis=0, keepdims=True)
std = np.concatenate(train_arrays, axis=0).std(axis=0, keepdims=True)
std = np.maximum(std, 1e-6)

train_x = np.concatenate([(x - mean) / std for x in train_arrays], axis=0)
valid_x = [(x - mean) / std for x in a] if False else [
    (x - mean).astype(np.float32) / std for x in valid_arrays
]
train_x = torch.from_numpy(train_x.astype(np.float32))
train_loader = DataLoader(
    TensorDataset(train_x), batch_size=256, shuffle=True,
    generator=torch.Generator().manual_seed(SEED)
)

model = nn.Sequential(
    nn.Linear(640, 128), nn.ReLU(),
    nn.Linear(128, 32), nn.ReLU(),
    nn.Linear(32, 128), nn.ReLU(),
    nn.Linear(128, 640)
).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()
model.train()
batch_losses = []

for (batch,) in train_loader:
    optimizer.zero_grad()
    loss = criterion(model(batch), batch)
    loss.backward()
    optimizer.step()
    batch_losses.append(loss.item())

model.eval()
recording_errors = []
with torch.no_grad():
    for name, x in zip(valid_names, valid_x):
        xt = torch.from_numpy(x)
        errors = ((model(xt) - xt) ** 2).mean(dim=1)
        recording_errors.append(float(errors.mean().item()))

torch.save({
    "model_state_dict": model.state_dict(),
    "normalization_mean": torch.from_numpy(mean.astype(np.float32)),
    "normalization_std": torch.from_numpy(std.astype(np.float32)),
    "input_dim": 640,
    "seed": SEED,
    "train_recordings": train_names,
    "validation_recordings": valid_names,
    "channel": 1,
    "epochs": 1,
}, NEW_MODEL)

summary = {
    "experiment": "pilot_channel1_seed13711",
    "device": "cpu",
    "epochs": 1,
    "train_recordings": len(train_names),
    "validation_recordings": len(valid_names),
    "train_feature_vectors": int(len(train_x)),
    "mean_train_batch_mse": float(np.mean(batch_losses)),
    "mean_validation_recording_error": float(np.mean(recording_errors)),
    "warning": "Pilot only; not a final anomaly-detection result."
}
NEW_SUMMARY.write_text(json.dumps(summary, indent=2), encoding="utf-8")

with NEW_SCORES.open("w", encoding="utf-8") as f:
    f.write("filename,validation_recording_error\n")
    for name, score in zip(valid_names, recording_errors):
        f.write(f"{name},{score:.8f}\n")

print("\nCHANNEL 1 PILOT COMPLETE")
print(json.dumps(summary, indent=2))
print("Saved:", NEW_MODEL.name)
print("Original channel 0 model preserved:", ORIGINAL.exists())

Extracting channel 1 pilot training features...
Extracting channel 1 pilot validation features...

CHANNEL 1 PILOT COMPLETE
{
  "experiment": "pilot_channel1_seed13711",
  "device": "cpu",
  "epochs": 1,
  "train_recordings": 20,
  "validation_recordings": 5,
  "train_feature_vectors": 6180,
  "mean_train_batch_mse": 0.8469390082359314,
  "mean_validation_recording_error": 0.6784438729286194,
  "warning": "Pilot only; not a final anomaly-detection result."
}
Saved: pilot_channel1_seed13711.pt
Original channel 0 model preserved: True

In [109]:

from pathlib import Path
import json
import random

import numpy as np
import soundfile as sf
import librosa
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

SEED = 13711
ROOT = Path("/content/AURIX_data/bearingEmu/train")
OUT = Path("/content/AURIX.V1/experiments")

SOURCE_MODEL = OUT / "pilot_channel0_seed13711.pt"
SOURCE_MODEL_1 = OUT / "pilot_channel1_seed13711.pt"
NEW_MODEL = OUT / "pilot_earlyfusion_seed13711.pt"
NEW_SUMMARY = OUT / "pilot_earlyfusion_seed13711_summary.json"
NEW_SCORES = OUT / "pilot_earlyfusion_seed13711_validation_scores.csv"

assert SOURCE_MODEL.is_file() and SOURCE_MODEL_1.is_file()
assert not NEW_MODEL.exists(), "Early-fusion pilot already exists; refusing to overwrite."

old = torch.load(SOURCE_MODEL, map_location="cpu", weights_only=False)
train_names = old["train_recordings"]
valid_names = old["validation_recordings"]
assert len(train_names) == 20 and len(valid_names) == 5
assert not set(train_names) & set(valid_names)

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

def extract_fusion(filename):
    audio, sr = sf.read(str(ROOT / filename), dtype="float32")
    assert sr == 16000 and audio.ndim == 2 and audio.shape[1] == 2

    channel_features = []
    for channel in (0, 1):
        mel = librosa.feature.melspectrogram(
            y=audio[:, channel], sr=sr, n_mels=128,
            n_fft=1024, hop_length=512, power=2.0
        )
        logmel = 10 * np.log10(
            np.maximum(mel, np.finfo(np.float32).eps)
        )
        channel_features.append(logmel)

    assert channel_features[0].shape == channel_features[1].shape
    both = np.concatenate(channel_features, axis=0)  # 256 x frames

    # Five consecutive frames, flattened to 256 * 5 = 1280
    x = np.stack([
        both[:, i:i+5].T.reshape(-1)
        for i in range(both.shape[1] - 4)
    ]).astype(np.float32)

    assert x.shape[1] == 1280 and np.isfinite(x).all()
    return x

print("Extracting early-fusion training features...")
train_arrays = [extract_fusion(n) for n in train_names]
print("Extracting early-fusion validation features...")
valid_arrays = [extract_fusion(n) for n in valid_names]

# Fit normalization on training recordings only
mean = np.concatenate(train_arrays, axis=0).mean(axis=0, keepdims=True)
std = np.concatenate(train_arrays, axis=0).std(axis=0, keepdims=True)
std = np.maximum(std, 1e-6)

train_x = np.concatenate([(x - mean) / std for x in train_arrays], axis=0)
valid_x = [(x - mean) / std for x in valid_arrays]

train_x = torch.from_numpy(train_x.astype(np.float32))
loader = DataLoader(
    TensorDataset(train_x), batch_size=256, shuffle=True,
    generator=torch.Generator().manual_seed(SEED)
)

# Same hidden/latent dimensions; input/output adapted for two channels
model = nn.Sequential(
    nn.Linear(1280, 128), nn.ReLU(),
    nn.Linear(128, 32), nn.ReLU(),
    nn.Linear(32, 128), nn.ReLU(),
    nn.Linear(128, 1280)
)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()
batch_losses = []

model.train()
for (batch,) in loader:
    optimizer.zero_grad()
    loss = criterion(model(batch), batch)
    loss.backward()
    optimizer.step()
    batch_losses.append(loss.item())

model.eval()
recording_errors = []
with torch.no_grad():
    for x in valid_x:
        xt = torch.from_numpy(x.astype(np.float32))
        errors = ((model(xt) - xt) ** 2).mean(dim=1)
        recording_errors.append(float(errors.mean().item()))

torch.save({
    "model_state_dict": model.state_dict(),
    "normalization_mean": torch.from_numpy(mean.astype(np.float32)),
    "normalization_std": torch.from_numpy(std.astype(np.float32)),
    "input_dim": 1280,
    "seed": SEED,
    "train_recordings": train_names,
    "validation_recordings": valid_names,
    "fusion": "early",
    "epochs": 1
}, NEW_MODEL)

summary = {
    "experiment": "pilot_earlyfusion_seed13711",
    "device": "cpu",
    "epochs": 1,
    "train_recordings": len(train_names),
    "validation_recordings": len(valid_names),
    "train_feature_vectors": int(len(train_x)),
    "mean_train_batch_mse": float(np.mean(batch_losses)),
    "mean_validation_recording_error": float(np.mean(recording_errors)),
    "warning": "Pilot only; not a final anomaly-detection result."
}
NEW_SUMMARY.write_text(json.dumps(summary, indent=2), encoding="utf-8")

with NEW_SCORES.open("w", encoding="utf-8") as f:
    f.write("filename,validation_recording_error\n")
    for name, score in zip(valid_names, recording_errors):
        f.write(f"{name},{score:.8f}\n")

print("\nEARLY-FUSION PILOT COMPLETE")
print(json.dumps(summary, indent=2))
print("Saved:", NEW_MODEL.name)
print("Previous models preserved:", SOURCE_MODEL.exists() and SOURCE_MODEL_1.exists())

Extracting early-fusion training features...
Extracting early-fusion validation features...

EARLY-FUSION PILOT COMPLETE
{
  "experiment": "pilot_earlyfusion_seed13711",
  "device": "cpu",
  "epochs": 1,
  "train_recordings": 20,
  "validation_recordings": 5,
  "train_feature_vectors": 6180,
  "mean_train_batch_mse": 0.8520696973800659,
  "mean_validation_recording_error": 0.6852970361709595,
  "warning": "Pilot only; not a final anomaly-detection result."
}
Saved: pilot_earlyfusion_seed13711.pt
Previous models preserved: True

In [110]:

from pathlib import Path

root = Path("/content/AURIX_data/bearingEmu")

for folder in (root / "test", root / "train"):
    print(f"\n{folder}:")
    if folder.exists():
        files = sorted(folder.iterdir())
        print("Entries:", len(files))
        for p in files[:5]:
            print(" ", p.name)
    else:
        print("Folder not found")

print("\nSaved pilot models:")
for p in sorted(Path("/content/AURIX.V1/experiments").glob("pilot_*.pt")):
    print(" ", p.name)

/content/AURIX_data/bearingEmu/test:
Entries: 200
  section_00_source_test_anomaly_0000_noAttribute.wav
  section_00_source_test_anomaly_0001_noAttribute.wav
  section_00_source_test_anomaly_0002_noAttribute.wav
  section_00_source_test_anomaly_0003_noAttribute.wav
  section_00_source_test_anomaly_0004_noAttribute.wav

/content/AURIX_data/bearingEmu/train:
Entries: 1000
  section_00_source_train_normal_0000_noAttribute.wav
  section_00_source_train_normal_0001_noAttribute.wav
  section_00_source_train_normal_0002_noAttribute.wav
  section_00_source_train_normal_0003_noAttribute.wav
  section_00_source_train_normal_0004_noAttribute.wav

Saved pilot models:
  pilot_channel0_seed13711.pt
  pilot_channel1_seed13711.pt
  pilot_earlyfusion_seed13711.pt

In [111]:

from pathlib import Path
import csv
import json

import numpy as np
import soundfile as sf
import librosa
import torch
from torch import nn
from sklearn.metrics import roc_auc_score, average_precision_score

ROOT = Path("/content/AURIX_data/bearingEmu")
OUT = Path("/content/AURIX.V1/experiments")
TEST = ROOT / "test"

MODELS = {
    "channel0": OUT / "pilot_channel0_seed13711.pt",
    "channel1": OUT / "pilot_channel1_seed13711.pt",
    "early_fusion": OUT / "pilot_earlyfusion_seed13711.pt",
}

def extract_features(path, mode):
    audio, sr = sf.read(str(path), dtype="float32")
    assert sr == 16000 and audio.ndim == 2 and audio.shape[1] == 2

    channels = (0,) if mode == "channel0" else (1,) if mode == "channel1" else (0, 1)
    mels = []

    for channel in channels:
        mel = librosa.feature.melspectrogram(
            y=audio[:, channel], sr=sr, n_mels=128,
            n_fft=1024, hop_length=512, power=2.0
        )
        mels.append(10 * np.log10(np.maximum(mel, np.finfo(np.float32).eps)))

    spec = mels[0] if len(mels) == 1 else np.concatenate(mels, axis=0)
    return np.stack([
        spec[:, i:i+5].T.reshape(-1)
        for i in range(spec.shape[1] - 4)
    ]).astype(np.float32)

def build_model(input_dim):
    if input_dim == 640:
        return nn.Sequential(
            nn.Linear(640, 128), nn.ReLU(),
            nn.Linear(128, 32), nn.ReLU(),
            nn.Linear(32, 128), nn.ReLU(),
            nn.Linear(128, 640)
        )
    return nn.Sequential(
        nn.Linear(1280, 128), nn.ReLU(),
        nn.Linear(128, 32), nn.ReLU(),
        nn.Linear(32, 128), nn.ReLU(),
        nn.Linear(128, 1280)
    )

torch.set_num_threads(2)
results = []

test_files = sorted(TEST.glob("*.wav"))
assert len(test_files) == 200

for model_name, model_path in MODELS.items():
    checkpoint = torch.load(model_path, map_location="cpu", weights_only=False)
    model = build_model(checkpoint["input_dim"])
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    mean = checkpoint["normalization_mean"].numpy()
    std = checkpoint["normalization_std"].numpy()

    rows = []
    for path in test_files:
        features = extract_features(path, model_name)
        x = torch.from_numpy(((features - mean) / std).astype(np.float32))

        with torch.no_grad():
            error = ((model(x) - x) ** 2).mean(dim=1).mean().item()

        name = path.name.lower()
        label = 1 if "_anomaly_" in name else 0
        domain = "target" if "_target_" in name else "source"

        rows.append({
            "filename": path.name,
            "domain": domain,
            "label": label,
            "anomaly_score": error
        })

    csv_path = OUT / f"pilot_{model_name}_test_scores.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    for domain in ("source", "target", "all"):
        subset = rows if domain == "all" else [r for r in rows if r["domain"] == domain]
        y = np.array([r["label"] for r in subset])
        scores = np.array([r["anomaly_score"] for r in subset])

        results.append({
            "model": model_name,
            "domain": domain,
            "n": len(subset),
            "roc_auc": float(roc_auc_score(y, scores)),
            "pauc_max_fpr_0.1": float(roc_auc_score(y, scores, max_fpr=0.1)),
            "average_precision": float(average_precision_score(y, scores))
        })

report = OUT / "pilot_test_metrics_exploratory.json"
report.write_text(json.dumps(results, indent=2), encoding="utf-8")

print("EXPLORATORY PILOT TEST EVALUATION COMPLETE")
for row in results:
    print(
        f"{row['model']:12s} | {row['domain']:6s} | "
        f"n={row['n']:3d} | ROC-AUC={row['roc_auc']:.4f} | "
        f"pAUC={row['pauc_max_fpr_0.1']:.4f} | "
        f"AP={row['average_precision']:.4f}"
    )

print("\nSaved exploratory metrics:", report.name)
print("No model training performed.")
print("IMPORTANT: These test metrics are exploratory, not final independent results.")

AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

In [112]:

from pathlib import Path
import csv
import json

import numpy as np
import soundfile as sf
import librosa
import torch
from torch import nn
from sklearn.metrics import roc_auc_score, average_precision_score

ROOT = Path("/content/AURIX_data/bearingEmu")
OUT = Path("/content/AURIX.V1/experiments")
TEST = ROOT / "test"

MODELS = {
    "channel0": OUT / "pilot_channel0_seed13711.pt",
    "channel1": OUT / "pilot_channel1_seed13711.pt",
    "early_fusion": OUT / "pilot_earlyfusion_seed13711.pt",
}

# Reconstruct the exact model architecture used by each saved pilot.
def build_model(input_dim):
    if input_dim == 640:
        return nn.Sequential(
            nn.Linear(640, 128), nn.ReLU(),
            nn.Linear(128, 32), nn.ReLU(),
            nn.Linear(32, 128), nn.ReLU(),
            nn.Linear(128, 640)
        )
    elif input_dim == 1280:
        return nn.Sequential(
            nn.Linear(1280, 128), nn.ReLU(),
            nn.Linear(128, 32), nn.ReLU(),
            nn.Linear(32, 128), nn.ReLU(),
            nn.Linear(128, 1280)
        )
    raise ValueError(f"Unexpected input dimension: {input_dim}")

def extract_features(path, mode):
    audio, sr = sf.read(str(path), dtype="float32")
    assert sr == 16000 and audio.ndim == 2 and audio.shape[1] == 2

    channels = (0,) if mode == "channel0" else (1,) if mode == "channel1" else (0, 1)
    mels = []

    for channel in channels:
        mel = librosa.feature.melspectrogram(
            y=audio[:, channel],
            sr=sr,
            n_mels=128,
            n_fft=1024,
            hop_length=512,
            power=2.0
        )
        logmel = 10 * np.log10(
            np.maximum(mel, np.finfo(np.float32).eps)
        )
        mels.append(logmel)

    spec = mels[0] if len(mels) == 1 else np.concatenate(mels, axis=0)

    features = np.stack([
        spec[:, i:i+5].T.reshape(-1)
        for i in range(spec.shape[1] - 4)
    ]).astype(np.float32)

    expected_dim = 640 if mode in ("channel0", "channel1") else 1280
    assert features.shape[1] == expected_dim
    assert np.isfinite(features).all()
    return features

torch.set_num_threads(2)

test_files = sorted(TEST.glob("*.wav"))
assert len(test_files) == 200, f"Expected 200 test files, found {len(test_files)}"

results = []

for model_name, model_path in MODELS.items():
    assert model_path.is_file(), f"Missing model file: {model_path.name}"
    print(f"\nEvaluating {model_name}...")

    checkpoint = torch.load(
        model_path, map_location="cpu", weights_only=False
    )

    model = build_model(int(checkpoint["input_dim"]))
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    # Handle either NumPy arrays or PyTorch tensors safely.
    mean = np.asarray(
        checkpoint["normalization_mean"].cpu().numpy()
        if torch.is_tensor(checkpoint["normalization_mean"])
        else checkpoint["normalization_mean"],
        dtype=np.float32
    )
    std = np.asarray(
        checkpoint["normalization_std"].cpu().numpy()
        if torch.is_tensor(checkpoint["normalization_std"])
        else checkpoint["normalization_std"],
        dtype=np.float32
    )
    std = np.maximum(std, 1e-6)

    rows = []

    for i, path in enumerate(test_files, start=1):
        features = extract_features(path, model_name)
        x = torch.from_numpy(((features - mean) / std).astype(np.float32))

        with torch.no_grad():
            score = float(((model(x) - x) ** 2).mean(dim=1).mean().item())

        filename = path.name.lower()
        label = 1 if "_anomaly_" in filename else 0
        domain = "target" if "_target_" in filename else "source"

        rows.append({
            "filename": path.name,
            "domain": domain,
            "label": label,
            "anomaly_score": score
        })

        if i % 50 == 0:
            print(f"  Scored {i}/{len(test_files)} recordings")

    score_file = OUT / f"pilot_{model_name}_test_scores.csv"
    with score_file.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "filename", "domain", "label", "anomaly_score"
        ])
        writer.writeheader()
        writer.writerows(rows)

    for domain in ("source", "target", "all"):
        subset = rows if domain == "all" else [
            r for r in rows if r["domain"] == domain
        ]

        y = np.array([r["label"] for r in subset], dtype=int)
        scores = np.array([r["anomaly_score"] for r in subset], dtype=float)

        if len(np.unique(y)) != 2:
            raise ValueError(f"Both classes are required for {domain} metrics.")

        results.append({
            "model": model_name,
            "domain": domain,
            "n": len(subset),
            "normal_count": int(np.sum(y == 0)),
            "anomaly_count": int(np.sum(y == 1)),
            "roc_auc": float(roc_auc_score(y, scores)),
            "pauc_max_fpr_0.1": float(
                roc_auc_score(y, scores, max_fpr=0.1)
            ),
            "average_precision": float(
                average_precision_score(y, scores)
            )
        })

report = OUT / "pilot_test_metrics_exploratory.json"
report.write_text(json.dumps(results, indent=2), encoding="utf-8")

print("\n" + "=" * 72)
print("EXPLORATORY PILOT TEST EVALUATION COMPLETE")
print("=" * 72)

for r in results:
    print(
        f"{r['model']:12s} | {r['domain']:6s} | n={r['n']:3d} | "
        f"ROC-AUC={r['roc_auc']:.4f} | "
        f"pAUC={r['pauc_max_fpr_0.1']:.4f} | "
        f"AP={r['average_precision']:.4f}"
    )

print("\nSaved metrics:", report)
print("Original model checkpoints were not modified.")
print("IMPORTANT: These are exploratory pilot results, not final independent results.")

Evaluating channel0...
  Scored 50/200 recordings
  Scored 100/200 recordings
  Scored 150/200 recordings
  Scored 200/200 recordings

Evaluating channel1...
  Scored 50/200 recordings
  Scored 100/200 recordings
  Scored 150/200 recordings
  Scored 200/200 recordings

Evaluating early_fusion...
  Scored 50/200 recordings
  Scored 100/200 recordings
  Scored 150/200 recordings
  Scored 200/200 recordings

========================================================================
EXPLORATORY PILOT TEST EVALUATION COMPLETE
========================================================================
channel0     | source | n=100 | ROC-AUC=0.5496 | pAUC=0.5221 | AP=0.5690
channel0     | target | n=100 | ROC-AUC=0.5572 | pAUC=0.5495 | AP=0.5885
channel0     | all    | n=200 | ROC-AUC=0.5523 | pAUC=0.5263 | AP=0.5669
channel1     | source | n=100 | ROC-AUC=0.5348 | pAUC=0.5074 | AP=0.5330
channel1     | target | n=100 | ROC-AUC=0.4924 | pAUC=0.4905 | AP=0.4998
channel1     | all    | n=200 | ROC-AUC=0.5134 | pAUC=0.4953 | AP=0.5084
early_fusion | source | n=100 | ROC-AUC=0.5572 | pAUC=0.5347 | AP=0.5739
early_fusion | target | n=100 | ROC-AUC=0.5588 | pAUC=0.5074 | AP=0.5595
early_fusion | all    | n=200 | ROC-AUC=0.5583 | pAUC=0.5226 | AP=0.5621

Saved metrics: /content/AURIX.V1/experiments/pilot_test_metrics_exploratory.json
Original model checkpoints were not modified.
IMPORTANT: These are exploratory pilot results, not final independent results.

In [113]:

from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

for name in [
    "datasets/loader_common.py",
    "datasets/dcase_dcase202x_t2_loader.py",
    "networks/dcase2023t2_ae/dcase2023t2_ae.py",
]:
    p = root / name
    print(f"\n{'=' * 20} {name} {'=' * 20}")
    print("Exists:", p.exists())
    if p.exists():
        lines = p.read_text(encoding="utf-8").splitlines()
        keywords = (
            "power_to_db", "melspectrogram", "log",
            "normalization", "anomaly_score",
            "covariance", "mahalanobis", "mono"
        )
        matches = [
            (i, line) for i, line in enumerate(lines, 1)
            if any(k in line.lower() for k in keywords)
        ]
        for i, line in matches[:35]:
            print(f"{i}: {line[:220]}")

==================== datasets/loader_common.py ====================
Exists: True
41: Standard output is logged in "baseline.log".
43: import logging
45: logging.basicConfig(level=logging.DEBUG, filename="baseline.log")
46: logger = logging.getLogger(' ')
47: handler = logging.StreamHandler()
48: formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
50: logger.addHandler(handler)
91: def file_load(wav_name, mono=False):
97:     mono : boolean
98:         When load a multi channels file and this param True, the returned data will be merged for mono data
105:         mono and ch == 1,
106:         not mono and ch > 1,
107:     ]), f"Channel mismatch: The file is {ch=}, but {mono=} is specified."
110:         if mono:
111:             return librosa.load(wav_name, sr=None, mono=mono)
113:             y, sr = librosa.load(wav_name, sr=None, mono=mono)
116:         logger.error("file_broken or not exists!! : {}".format(wav_name))
134:                     mono=True):
148:     # generate melspectrogram using librosa
149:     y, sr = file_load(file_name, mono=mono)
151:     mel_spectrogram = librosa.feature.melspectrogram(y=y,
161:     # convert melspectrogram to log mel energies
162:     log_mel_spectrogram = 20.0 / power * np.log10(np.maximum(mel_spectrogram, sys.float_info.epsilon))
165:     n_vectors = log_mel_spectrogram.shape[-1] - n_frames + 1
174:         vectors[:, n_mels * t : n_mels * (t + 1)] = log_mel_spectrogram[:, t : t + n_vectors].T
199:         logger.info("load_directory <- development")
202:         logger.info("load_directory <- evaluation")
279:     logger.info("target_dir : {}".format(target_dir + "_" + section_name))
317:         logger.info("#files : {num}".format(num=len(files)))
319:             logger.exception("no_wav_file!!")
334:         logger.info("#files : {num}".format(num=len(files)))
336:             logger.exception("no_wav_file!!")

==================== datasets/dcase_dcase202x_t2_loader.py ====================
Exists: True
34:                 mono=True,
65:         self.log_melspectrogram_dir = os.path.abspath(
98:         if not os.path.exists(self.log_melspectrogram_dir):
99:             os.makedirs(self.log_melspectrogram_dir, exist_ok=True)
104:         pickle_path = os.path.abspath(f"{self.log_melspectrogram_dir}/{pickle_name}.pickle")
123:             mono=mono,
159:             mono=True,
162:         pickle_lockfile_path = os.path.abspath(f"{self.log_melspectrogram_dir}/{pickle_name}_lockfile")
231:                                         mono=mono)
334:                         mono=True):
363:                                                 mono=mono)

==================== networks/dcase2023t2_ae/dcase2023t2_ae.py ====================
Exists: True
35:     def get_log_header(self):
57:             print("\n============== CALCULATE COVARIANCE ==============")
61:             # initialize mahalanobis param
83:             is_source_list = np.logical_not(is_target_list).tolist()
144:             if batch_idx % self.args.log_interval == 0 and not is_calc_cov:
179:             self.fit_anomaly_score_distribution(
205:             # plot train log
210:             with open(self.log_path, 'a') as log:
211:                 np.savetxt(log,["{0},{1},{2},{3},{4}".format(
219:                 file_path=self.log_path,
225:             self.fit_anomaly_score_distribution(
312:             anomaly_score_csv = result_dir/f"anomaly_score_{self.args.dataset}_{section_name}_{dir_name}_seed{self.args.seed}{self.model_name_suffix}{self.eval_suffix}.csv"
313:             anomaly_score_list = []
329:                 y_pred, anomaly_score_list, decision_result_list, domain_list = self.eval(
332:                     anomaly_score_list=anomaly_score_list,
343:             save_csv(save_file_path=anomaly_score_csv, save_data=anomaly_score_list)
344:             print("anomaly score result ->  {}".format(anomaly_score_csv))
444:         anomaly_score_list,
486:             anomaly_score_list.append([basename, y_pred[-1]])
496:         return y_pred, anomaly_score_list, decision_result_list, domain_list

In [115]:

import sys
from pathlib import Path
import numpy as np
import soundfile as sf

BASELINE_ROOT = Path("/content/dcase2026_baseline_ae")
DATA_FILE = Path(
    "/content/AURIX_data/bearingEmu/train/"
    "section_00_source_train_normal_0067_noAttribute.wav"
)

sys.path.insert(0, str(BASELINE_ROOT))

from datasets.loader_common import file_to_vectors

assert DATA_FILE.exists(), f"Missing WAV: {DATA_FILE}"

# Official baseline preprocessing, selecting channel 0
official = file_to_vectors(
    str(DATA_FILE),
    n_mels=128,
    n_frames=5,
    n_fft=1024,
    hop_length=512,
    power=2.0,
    mono=False,
)

# Independent implementation of the same preprocessing
import librosa

audio, sr = sf.read(DATA_FILE, dtype="float32")
assert audio.ndim == 2 and audio.shape[1] == 2

mel = librosa.feature.melspectrogram(
    y=audio[:, 0],
    sr=sr,
    n_mels=128,
    n_fft=1024,
    hop_length=512,
    power=2.0,
)
log_mel = 10.0 * np.log10(
    np.maximum(mel, np.finfo(float).eps)
)

n_vectors = log_mel.shape[-1] - 5 + 1
custom = np.concatenate(
    [log_mel[:, i:i+n_vectors].T for i in range(5)],
    axis=1,
)

official = np.asarray(official)

print("Official shape:", official.shape)
print("Custom shape:  ", custom.shape)

if official.shape == custom.shape:
    diff = np.abs(official.astype(np.float64) - custom.astype(np.float64))
    print("Maximum absolute difference:", float(diff.max()))
    print("Mean absolute difference:   ", float(diff.mean()))
    print("Numerically equivalent:", bool(np.allclose(
        official, custom, rtol=1e-5, atol=1e-5
    )))
else:
    print("Shapes differ; inspect the official function's output format.")

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

In [116]:

import sys
from pathlib import Path
import numpy as np
import soundfile as sf
import librosa

BASELINE_ROOT = Path("/content/dcase2026_baseline_ae")
DATA_FILE = Path(
    "/content/AURIX_data/bearingEmu/train/"
    "section_00_source_train_normal_0067_noAttribute.wav"
)

sys.path.insert(0, str(BASELINE_ROOT))
from datasets.loader_common import file_to_vectors

assert DATA_FILE.exists(), f"Missing WAV: {DATA_FILE}"

# Match the baseline defaults explicitly, including fmax=None
official = file_to_vectors(
    str(DATA_FILE),
    n_mels=128,
    n_frames=5,
    n_fft=1024,
    hop_length=512,
    power=2.0,
    fmin=0.0,
    fmax=8000.0,
    win_length=None,
    mono=False,
)

# Independent extraction using the same frequency range
audio, sr = sf.read(DATA_FILE, dtype="float32")
assert audio.ndim == 2 and audio.shape[1] == 2
assert sr == 16000

mel = librosa.feature.melspectrogram(
    y=audio[:, 0],
    sr=sr,
    n_mels=128,
    n_fft=1024,
    hop_length=512,
    power=2.0,
    fmin=0.0,
    fmax=8000.0,
    win_length=None,
)

log_mel = 10.0 * np.log10(
    np.maximum(mel, np.finfo(float).eps)
)

n_vectors = log_mel.shape[-1] - 5 + 1
custom = np.concatenate(
    [log_mel[:, i:i+n_vectors].T for i in range(5)],
    axis=1,
)

official = np.asarray(official)

print("Official shape:", official.shape)
print("Custom shape:  ", custom.shape)

if official.shape == custom.shape:
    diff = np.abs(official.astype(np.float64) - custom.astype(np.float64))
    print("Maximum absolute difference:", float(diff.max()))
    print("Mean absolute difference:   ", float(diff.mean()))
    print(
        "Numerically equivalent:",
        bool(np.allclose(official, custom, rtol=1e-5, atol=1e-5))
    )
else:
    print("Output formats differ; comparison needs adjustment.")

Official shape: (309, 640)
Custom shape:   (309, 640)
Maximum absolute difference: 4.4752105878842485e-06
Mean absolute difference:    8.605814579155306e-07
Numerically equivalent: True

In [117]:

import ast
from pathlib import Path

p = Path("/content/dcase2026_baseline_ae/datasets/loader_common.py")
source = p.read_text()
tree = ast.parse(source)

for node in ast.walk(tree):
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        if node.name == "file_to_vectors":
            print("Function:", node.name)
            print("Arguments and defaults:")
            args = node.args
            defaults = args.defaults
            first_default = len(args.args) - len(defaults)
            for i, arg in enumerate(args.args):
                default = (
                    ast.unparse(defaults[i - first_default])
                    if i >= first_default else "(required)"
                )
                print(f"  {arg.arg} = {default}")
            print("\nRelevant implementation:")
            lines = source.splitlines()
            for i in range(node.lineno - 1, min(node.end_lineno, len(lines))):
                line = lines[i]
                if any(k in line for k in (
                    "def file_to_vectors", "fmax", "fmin", "melspectrogram",
                    "log_mel_spectrogram", "n_fft", "hop_length", "win_length"
                )):
                    print(f"{i+1}: {line}")
            break

Function: file_to_vectors
Arguments and defaults:
  file_name = (required)
  n_mels = 64
  n_frames = 5
  n_fft = 1024
  hop_length = 512
  power = 2.0
  fmax = None
  fmin = None
  win_length = None
  mono = True

Relevant implementation:
125: def file_to_vectors(file_name,
128:                     n_fft=1024,
129:                     hop_length=512,
131:                     fmax=None,
132:                     fmin=None,
133:                     win_length=None,
148:     # generate melspectrogram using librosa
151:     mel_spectrogram = librosa.feature.melspectrogram(y=y,
153:                                                         n_fft=n_fft,
154:                                                         hop_length=hop_length,
157:                                                         fmax=fmax,
158:                                                         fmin=fmin,
159:                                                         win_length=win_length)
161:     # convert melspectrogram to log mel energies
162:     log_mel_spectrogram = 20.0 / power * np.log10(np.maximum(mel_spectrogram, sys.float_info.epsilon))
165:     n_vectors = log_mel_spectrogram.shape[-1] - n_frames + 1
174:         vectors[:, n_mels * t : n_mels * (t + 1)] = log_mel_spectrogram[:, t : t + n_vectors].T

In [118]:

from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

targets = [
    root / "param.yaml",
    root / "config.yaml",
    root / "datasets" / "loader_common.py",
    root / "datasets" / "datasets.py",
    root / "datasets" / "dcase_dcase202x_t2_loader.py",
]

terms = (
    "fmax", "fmin", "mono", "file_to_vectors",
    "n_mels", "n_fft", "power", "hop_length",
    "bearingEmu", "validation_split"
)

for path in targets:
    if not path.exists():
        continue

    print(f"\n{'='*18} {path.relative_to(root)} {'='*18}")
    lines = path.read_text(errors="replace").splitlines()

    matches = [
        i for i, line in enumerate(lines)
        if any(term.lower() in line.lower() for term in terms)
    ]

    shown = set()
    for i in matches:
        for j in range(max(0, i-2), min(len(lines), i+3)):
            if j not in shown:
                print(f"{j+1}: {lines[j]}")
                shown.add(j)
        print()

================== datasets/loader_common.py ==================
89: ########################################################################
90: # wav file input
91: def file_load(wav_name, mono=False):
92:     """
93:     load .wav file.

95:     wav_name : str
96:         target .wav file
97:     mono : boolean
98:         When load a multi channels file and this param True, the returned data will be merged for mono data
99:

100:     return : numpy.array( float )

103:     ch = info.channels
104:     assert any([
105:         mono and ch == 1,
106:         not mono and ch > 1,
107:     ]), f"Channel mismatch: The file is {ch=}, but {mono=} is specified."

108:

109:     try:

110:         if mono:
111:             return librosa.load(wav_name, sr=None, mono=mono)
112:         else:

113:             y, sr = librosa.load(wav_name, sr=None, mono=mono)

114:             return y[0], sr
115:     except:

123: # feature extractor
124: ########################################################################
125: def file_to_vectors(file_name,
126:                     n_mels=64,
127:                     n_frames=5,

128:                     n_fft=1024,

129:                     hop_length=512,
130:                     power=2.0,

131:                     fmax=None,

132:                     fmin=None,

133:                     win_length=None,

134:                     mono=True):

135:     """
136:     convert file_name to a vector array.

144:     """
145:     # calculate the number of dimensions
146:     dims = n_mels * n_frames
147:
148:     # generate melspectrogram using librosa

149:     y, sr = file_load(file_name, mono=mono)
150:
151:     mel_spectrogram = librosa.feature.melspectrogram(y=y,

152:                                                         sr=sr,
153:                                                         n_fft=n_fft,
154:                                                         hop_length=hop_length,
155:                                                         n_mels=n_mels,

156:                                                         power=power,

157:                                                         fmax=fmax,

158:                                                         fmin=fmin,

159:                                                         win_length=win_length)

160:

161:     # convert melspectrogram to log mel energies
162:     log_mel_spectrogram = 20.0 / power * np.log10(np.maximum(mel_spectrogram, sys.float_info.epsilon))
163:
164:     # calculate total vector size

172:     vectors = np.zeros((n_vectors, dims))
173:     for t in range(n_frames):
174:         vectors[:, n_mels * t : n_mels * (t + 1)] = log_mel_spectrogram[:, t : t + n_vectors].T
175:
176:     return vectors


================== datasets/datasets.py ==================
10:     def __init__(self, args):
11:         self.width   = args.frames
12:         self.height  = args.n_mels
13:         self.channel = 1
14:         self.input_dim = self.width*self.height*self.channel

45:                 section_ids=self.section_id_list,
46:                 frames=args.frames,
47:                 n_mels=args.n_mels,
48:                 frame_hop_length=args.frame_hop_length,
49:                 n_fft=args.n_fft,

50:                 hop_length=args.hop_length,

51:                 power=args.power,

52:                 fmax=args.fmax,

53:                 fmin=args.fmin,

54:                 win_length=args.win_length,

55:                 data_type=data_type,

56:                 use_id=args.use_ids,
57:                 is_auto_download=args.is_auto_download,
58:                 mono=args.mono,
59:                 )
60:

61:         train_index, valid_index = train_test_split(range(len(train_data)), test_size=args.validation_split)
62:         self.train_dataset = Subset(train_data, train_index)
63:         self.train_loader = torch.utils.data.DataLoader(

83:                 section_ids=[id],
84:                 frames=args.frames,
85:                 n_mels=args.n_mels,
86:                 frame_hop_length=args.frame_hop_length,
87:                 n_fft=args.n_fft,

88:                 hop_length=args.hop_length,

89:                 power=args.power,

90:                 fmax=args.fmax,

91:                 fmin=args.fmin,

92:                 win_length=args.win_length,

93:                 data_type=data_type,

94:                 is_auto_download=args.is_auto_download,
95:                 mono=args.mono,
96:            )
97:

116:         'DCASE2026T2gearboxEmu':DCASE202XT2,
117:         'DCASE2026T2fan':DCASE202XT2,
118:         'DCASE2026T2bearingEmu':DCASE202XT2,
119:         'DCASE2026T2ToyCarEmu':DCASE202XT2,
120:         'DCASE2026T2ToyCar':DCASE202XT2,


================== datasets/dcase_dcase202x_t2_loader.py ==================
19:                 section_ids=[],
20:                 train=True,
21:                 n_mels=128,
22:                 frames=5,
23:                 frame_hop_length=1,

24:                 n_fft=1024,
25:                 hop_length=512,

26:                 fmax=None,

27:                 fmin=None,

28:                 win_length=None,

29:                 power=2.0,

30:                 data_type = "dev",
31:                 source_domain="mix",

32:                 use_id = [],
33:                 is_auto_download=False,
34:                 mono=True,
35:     ):
36:         super().__init__()

59:             )
60:         )
61:         if not (fmax or fmin):
62:             fmin_max = ""
63:         else:

64:             fmin_max = f"_f{fmin}-{fmax}"

65:         self.log_melspectrogram_dir = os.path.abspath(
66:             "{dir}/mels{n_mels}_fft{n_fft}_hop{hop_length}{fmin_max}".format(

67:                 dir=self.pickle_dir,
68:                 n_mels=n_mels,

69:                 n_fft=n_fft,
70:                 hop_length=hop_length,

71:                 fmin_max=fmin_max

72:             )

73:         )

101:         for section_id in section_ids:
102:             pickle_name = f"{pickle_name}_{section_id}"
103:         pickle_name = f"{pickle_name}_{source_domain}_TF{frames}-{frame_hop_length}_mel{n_fft}-{hop_length}"
104:         pickle_path = os.path.abspath(f"{self.log_melspectrogram_dir}/{pickle_name}.pickle")
105:

112:             dir_name=dir_name,
113:             train=train,
114:             n_mels=n_mels,
115:             frames=frames,
116:             frame_hop_length=frame_hop_length,

117:             n_fft=n_fft,
118:             hop_length=hop_length,

119:             power=power,

120:             fmax=fmax,

121:             fmin=fmin,

122:             win_length=win_length,

123:             mono=mono,

124:         )
125:         if len(self.use_id) > 0:

148:             dir_name,
149:             train,
150:             n_mels,
151:             frames,
152:             frame_hop_length,

153:             n_fft,
154:             hop_length,

155:             power,

156:             fmax,

157:             fmin,

158:             win_length,

159:             mono=True,

160:         ):
161:

200:             n_files_ea_section = []
201:
202:             self.data = np.empty((0, frames * n_mels), float)
203:             self.y_true = np.empty(0, float)
204:             self.condition = np.empty((0, n_sections), float)

220:                 data_ea_section = file_list_to_data(files,
221:                                         msg=f"generate {self.machine_type} section {self.section_ids[section_idx]} {dir_name} dataset",
222:                                         n_mels=n_mels,
223:                                         n_frames=frames,
224:                                         n_hop_frames=frame_hop_length,

225:                                         n_fft=n_fft,
226:                                         hop_length=hop_length,

227:                                         power=power,

228:                                         fmax=fmax,

229:                                         fmin=fmin,

230:                                         win_length=win_length,

231:                                         mono=mono)

232:                 self.data = np.append(self.data, data_ea_section, axis=0)
233:                 if self.mode or train:

323: def file_list_to_data(file_list,
324:                         msg="calc...",
325:                         n_mels=64,
326:                         n_frames=5,
327:                         n_hop_frames=1,

328:                         n_fft=1024,
329:                         hop_length=512,
330:                         power=2.0,

331:                         fmax=None,

332:                         fmin=None,

333:                         win_length=None,

334:                         mono=True):

335:     """
336:     convert the file_list to a vector array.

348:     """
349:     # calculate the number of dimensions
350:     dims = n_mels * n_frames
351:
352:     # iterate file_to_vector_array()

353:     for idx in tqdm(range(len(file_list)), desc=msg):
354:         vectors = com.file_to_vectors(file_list[idx],
355:                                                 n_mels=n_mels,
356:                                                 n_frames=n_frames,

357:                                                 n_fft=n_fft,

358:                                                 hop_length=hop_length,
359:                                                 power=power,

360:                                                 fmax=fmax,

361:                                                 fmin=fmin,

362:                                                 win_length=win_length,

363:                                                 mono=mono)

364:         vectors = vectors[: : n_hop_frames, :]
365:         if idx == 0:

In [119]:
from pathlib import Path
import json

ROOT = Path("/content/AURIX.V1")
EXP = ROOT / "experiments"

print("Project exists:", ROOT.exists())
print("Experiments folder exists:", EXP.exists())

if EXP.exists():
    for name in sorted(p.name for p in EXP.iterdir()):
        print(name)

Project exists: True
Experiments folder exists: True
pilot_channel0_seed13711.pt
pilot_channel0_seed13711_summary.json
pilot_channel0_seed13711_validation_scores.csv
pilot_channel0_test_scores.csv
pilot_channel1_seed13711.pt
pilot_channel1_seed13711_summary.json
pilot_channel1_seed13711_validation_scores.csv
pilot_channel1_test_scores.csv
pilot_early_fusion_test_scores.csv
pilot_earlyfusion_seed13711.pt
pilot_earlyfusion_seed13711_summary.json
pilot_earlyfusion_seed13711_validation_scores.csv
pilot_test_metrics_exploratory.json
recording_split_seed13711.csv

In [120]:
import json
from pathlib import Path

nb_path = Path("/content/AURIX.V1/AURIX.ipynb")

with nb_path.open("r", encoding="utf-8") as f:
    nb = json.load(f)

keywords = [
    "melspectrogram",
    "Autoencoder",
    "pilot_channel0",
    "early_fusion",
    "recording_split_seed13711",
    "train_test_split",
]

for i, cell in enumerate(nb.get("cells", [])):
    if cell.get("cell_type") != "code":
        continue

    source = "".join(cell.get("source", []))
    matched = [k for k in keywords if k.lower() in source.lower()]

    if matched:
        print(f"\n{'='*60}")
        print(f"Cell {i} | Matches: {', '.join(matched)}")
        print(source[:1800])

In [121]:
from pathlib import Path
import json

p = Path("/content/AURIX.V1/AURIX.ipynb")

print("Notebook exists:", p.exists())

if p.exists():
    nb = json.loads(p.read_text(encoding="utf-8"))
    cells = nb.get("cells", [])
    print("Total cells:", len(cells))

    for i, cell in enumerate(cells):
        if cell.get("cell_type") == "code":
            src = "".join(cell.get("source", []))
            print(f"Cell {i}: {len(src)} characters")

Notebook exists: True
Total cells: 3
Cell 1: 11 characters
Cell 2: 120 characters

In [122]:
import json
from pathlib import Path

p = Path(
    "/content/AURIX.V1/experiments/"
    "pilot_channel0_seed13711_summary.json"
)

with p.open("r", encoding="utf-8") as f:
    summary = json.load(f)

print(json.dumps(summary, indent=2))

{
  "experiment": "pilot_channel0_seed13711",
  "device": "cpu",
  "epochs": 1,
  "train_recordings": 20,
  "validation_recordings": 5,
  "train_feature_vectors": 6180,
  "mean_train_batch_mse": 0.8511655712127686,
  "mean_validation_recording_error": 0.6928335309028626,
  "warning": "Pilot only; not a final anomaly-detection result."
}

In [123]:
from pathlib import Path

root = Path("/content/AURIX_data/bearingEmu")

for split in ["train", "test"]:
    folder = root / split
    print(f"\n{split}: exists={folder.exists()}")

    if folder.exists():
        files = sorted(folder.glob("*.wav"))
        print("WAV files:", len(files))
        for f in files[:3]:
            print(" ", f.name)

train: exists=True
WAV files: 1000
  section_00_source_train_normal_0000_noAttribute.wav
  section_00_source_train_normal_0001_noAttribute.wav
  section_00_source_train_normal_0002_noAttribute.wav

test: exists=True
WAV files: 200
  section_00_source_test_anomaly_0000_noAttribute.wav
  section_00_source_test_anomaly_0001_noAttribute.wav
  section_00_source_test_anomaly_0002_noAttribute.wav

In [124]:
from pathlib import Path
import numpy as np
import librosa

audio_path = (
    Path("/content/AURIX_data/bearingEmu/train")
    / "section_00_source_train_normal_0000_noAttribute.wav"
)

# Read only channel 0: the same audio perspective used by our baseline
audio, sr = librosa.load(
    str(audio_path),
    sr=16000,
    mono=False
)

if audio.ndim == 2:
    channel0 = audio[0]
else:
    channel0 = audio

# Log-mel spectrogram: frequency structure over time
mel = librosa.feature.melspectrogram(
    y=channel0,
    sr=sr,
    n_fft=1024,
    hop_length=512,
    n_mels=128,
    power=2.0,
    fmin=0,
    fmax=8000
)

log_mel = 10 * np.log10(
    np.maximum(mel, np.finfo(np.float32).eps)
)

# Temporal representation: change between consecutive frames
temporal = np.diff(log_mel, axis=1)

print("Sample rate:", sr)
print("Audio samples:", len(channel0))
print("Audio duration (seconds):", round(len(channel0) / sr, 2))
print("Spectral representation:", log_mel.shape)
print("Temporal representation:", temporal.shape)
print("All spectral values finite:", np.isfinite(log_mel).all())
print("All temporal values finite:", np.isfinite(temporal).all())

Sample rate: 16000
Audio samples: 160000
Audio duration (seconds): 10.0
Spectral representation: (128, 313)
Temporal representation: (128, 312)
All spectral values finite: True
All temporal values finite: True

In [125]:
from pathlib import Path
import pandas as pd

project_dir = Path("/content/AURIX.V1")
data_dir = Path("/content/AURIX_data/bearingEmu/train")
experiments_dir = project_dir / "experiments"

split_path = experiments_dir / "recording_split_seed13711.csv"

assert split_path.exists(), f"Missing split file: {split_path}"
assert data_dir.exists(), f"Missing training directory: {data_dir}"

split_df = pd.read_csv(split_path)

print("Split file columns:", split_df.columns.tolist())
print("Number of split rows:", len(split_df))
print("\nFirst five rows:")
display(split_df.head())

Split file columns: ['filename', 'domain', 'split', 'label', 'seed']
Number of split rows: 1000

First five rows:

,filename,domain,split,label,seed
0,section_00_source_train_normal_0000_noAttribut...,source,train,normal,13711
1,section_00_source_train_normal_0001_noAttribut...,source,train,normal,13711
2,section_00_source_train_normal_0002_noAttribut...,source,train,normal,13711
3,section_00_source_train_normal_0003_noAttribut...,source,train,normal,13711
4,section_00_source_train_normal_0004_noAttribut...,source,train,normal,13711

In [126]:
from pathlib import Path
import numpy as np
import pandas as pd
import librosa

# Paths
project_dir = Path("/content/AURIX.V1")
data_dir = Path("/content/AURIX_data/bearingEmu/train")
experiments_dir = project_dir / "experiments"
split_path = experiments_dir / "recording_split_seed13711.csv"

# Load the existing recording-level split
df = pd.read_csv(split_path)
df = df[
    (df["domain"] == "source") &
    (df["label"] == "normal") &
    (df["seed"] == 13711)
].copy()

train_names = df.loc[df["split"] == "train", "filename"].tolist()
val_names = df.loc[df["split"] == "validation", "filename"].tolist()

# Use the same small pilot size, deterministically
train_names = sorted(train_names)[:20]
val_names = sorted(val_names)[:5]

assert len(train_names) == 20, f"Expected 20 training recordings, got {len(train_names)}"
assert len(val_names) == 5, f"Expected 5 validation recordings, got {len(val_names)}"

def extract_two_paths(filename):
    path = data_dir / filename
    if not path.exists():
        raise FileNotFoundError(path)

    audio, sr = librosa.load(str(path), sr=16000, mono=False)
    channel0 = audio[0] if audio.ndim == 2 else audio

    mel = librosa.feature.melspectrogram(
        y=channel0,
        sr=sr,
        n_fft=1024,
        hop_length=512,
        n_mels=128,
        power=2.0,
        fmin=0,
        fmax=8000
    )

    log_mel = 10 * np.log10(
        np.maximum(mel, np.finfo(np.float32).eps)
    ).astype(np.float32)

    # Spectral path: the spectrum at each time frame
    spectral = log_mel.T

    # Temporal path: frame-to-frame spectral changes
    temporal = np.diff(log_mel, axis=1).T

    return spectral, temporal

def build_features(filenames):
    spectral_parts = []
    temporal_parts = []

    for i, filename in enumerate(filenames, start=1):
        spectral, temporal = extract_two_paths(filename)
        spectral_parts.append(spectral)
        temporal_parts.append(temporal)

        if i % 5 == 0 or i == len(filenames):
            print(f"Processed {i}/{len(filenames)} recordings")

    return (
        np.concatenate(spectral_parts, axis=0),
        np.concatenate(temporal_parts, axis=0)
    )

print("Extracting training features...")
X_spec_train, X_temp_train = build_features(train_names)

print("\nExtracting validation features...")
X_spec_val, X_temp_val = build_features(val_names)

# Fit normalization on training data ONLY
spec_mean = X_spec_train.mean(axis=0, keepdims=True)
spec_std = X_spec_train.std(axis=0, keepdims=True)
spec_std[spec_std < 1e-6] = 1.0

temp_mean = X_temp_train.mean(axis=0, keepdims=True)
temp_std = X_temp_train.std(axis=0, keepdims=True)
temp_std[temp_std < 1e-6] = 1.0

X_spec_train_norm = (X_spec_train - spec_mean) / spec_std
X_spec_val_norm = (X_spec_val - spec_mean) / spec_std

X_temp_train_norm = (X_temp_train - temp_mean) / temp_std
X_temp_val_norm = (X_temp_val - temp_mean) / temp_std

# Save as a new artifact; do not overwrite previous experiments
out_path = experiments_dir / "aurix_specialized_features_pilot_seed13711.npz"

np.savez_compressed(
    out_path,
    X_spec_train=X_spec_train_norm.astype(np.float32),
    X_spec_val=X_spec_val_norm.astype(np.float32),
    X_temp_train=X_temp_train_norm.astype(np.float32),
    X_temp_val=X_temp_val_norm.astype(np.float32),
    train_filenames=np.array(train_names),
    val_filenames=np.array(val_names),
    spec_mean=spec_mean.astype(np.float32),
    spec_std=spec_std.astype(np.float32),
    temp_mean=temp_mean.astype(np.float32),
    temp_std=temp_std.astype(np.float32),
)

print("\n--- Results ---")
print("Spectral train:", X_spec_train_norm.shape)
print("Spectral validation:", X_spec_val_norm.shape)
print("Temporal train:", X_temp_train_norm.shape)
print("Temporal validation:", X_temp_val_norm.shape)
print("All normalized features finite:", all([
    np.isfinite(X_spec_train_norm).all(),
    np.isfinite(X_spec_val_norm).all(),
    np.isfinite(X_temp_train_norm).all(),
    np.isfinite(X_temp_val_norm).all()
]))
print("Saved:", out_path)

Extracting training features...
Processed 5/20 recordings
Processed 10/20 recordings
Processed 15/20 recordings
Processed 20/20 recordings

Extracting validation features...
Processed 5/5 recordings

--- Results ---
Spectral train: (6260, 128)
Spectral validation: (1565, 128)
Temporal train: (6240, 128)
Temporal validation: (1560, 128)
All normalized features finite: True
Saved: /content/AURIX.V1/experiments/aurix_specialized_features_pilot_seed13711.npz

In [127]:
from pathlib import Path
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

# Reproducibility and CPU-friendly pilot
SEED = 13711
torch.manual_seed(SEED)
np.random.seed(SEED)
device = torch.device("cpu")

project_dir = Path("/content/AURIX.V1")
experiments_dir = project_dir / "experiments"
features_path = experiments_dir / "aurix_specialized_features_pilot_seed13711.npz"

assert features_path.exists(), f"Feature file not found: {features_path}"

data = np.load(features_path)

X_spec_train = data["X_spec_train"]
X_spec_val = data["X_spec_val"]
X_temp_train = data["X_temp_train"]
X_temp_val = data["X_temp_val"]

# Small autoencoder for each specialized representation
class SmallAutoencoder(nn.Module):
    def __init__(self, input_dim=128, hidden_dim=32, bottleneck_dim=8):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, bottleneck_dim),
            nn.ReLU(),
            nn.Linear(bottleneck_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, input_dim),
        )

    def forward(self, x):
        return self.net(x)

def train_one_path(X_train, X_val, path_name):
    torch.manual_seed(SEED)

    train_tensor = torch.from_numpy(
        np.asarray(X_train, dtype=np.float32)
    )
    val_tensor = torch.from_numpy(
        np.asarray(X_val, dtype=np.float32)
    )

    loader = DataLoader(
        TensorDataset(train_tensor),
        batch_size=256,
        shuffle=True,
        generator=torch.Generator().manual_seed(SEED)
    )

    model = SmallAutoencoder().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    loss_fn = nn.MSELoss()

    # Short feasibility run, not final training
    epochs = 5

    for epoch in range(epochs):
        model.train()
        losses = []

        for (batch,) in loader:
            batch = batch.to(device)
            optimizer.zero_grad()
            reconstruction = model(batch)
            loss = loss_fn(reconstruction, batch)
            loss.backward()
            optimizer.step()
            losses.append(loss.item())

        print(
            f"{path_name} | Epoch {epoch + 1}/{epochs} "
            f"| mean train MSE: {np.mean(losses):.5f}"
        )

    model.eval()
    with torch.no_grad():
        val_reconstruction = model(val_tensor)
        val_errors = torch.mean(
            (val_reconstruction - val_tensor) ** 2,
            dim=1
        ).cpu().numpy()

    model_path = experiments_dir / f"aurix_{path_name}_pilot_seed13711.pt"
    torch.save(model.state_dict(), model_path)

    print(f"{path_name} model saved: {model_path}")
    print(f"{path_name} validation frame errors: {val_errors.shape}")
    print(f"{path_name} validation errors finite: {np.isfinite(val_errors).all()}")

    return model, val_errors

print("Training spectral pathway...")
spectral_model, spectral_val_errors = train_one_path(
    X_spec_train, X_spec_val, "spectral"
)

print("\nTraining temporal pathway...")
temporal_model, temporal_val_errors = train_one_path(
    X_temp_train, X_temp_val, "temporal"
)

print("\nPilot training finished.")

Training spectral pathway...
spectral | Epoch 1/5 | mean train MSE: 0.95855
spectral | Epoch 2/5 | mean train MSE: 0.82313
spectral | Epoch 3/5 | mean train MSE: 0.67822
spectral | Epoch 4/5 | mean train MSE: 0.60137
spectral | Epoch 5/5 | mean train MSE: 0.57422
spectral model saved: /content/AURIX.V1/experiments/aurix_spectral_pilot_seed13711.pt
spectral validation frame errors: (1565,)
spectral validation errors finite: True

Training temporal pathway...
temporal | Epoch 1/5 | mean train MSE: 1.00080
temporal | Epoch 2/5 | mean train MSE: 0.96733
temporal | Epoch 3/5 | mean train MSE: 0.94243
temporal | Epoch 4/5 | mean train MSE: 0.92134
temporal | Epoch 5/5 | mean train MSE: 0.90080
temporal model saved: /content/AURIX.V1/experiments/aurix_temporal_pilot_seed13711.pt
temporal validation frame errors: (1560,)
temporal validation errors finite: True

Pilot training finished.

In [128]:
from pathlib import Path
import numpy as np
import pandas as pd
import torch

experiments_dir = Path("/content/AURIX.V1/experiments")
data = np.load(
    experiments_dir / "aurix_specialized_features_pilot_seed13711.npz"
)

def reconstruction_errors(model, X):
    model.eval()
    tensor = torch.from_numpy(np.asarray(X, dtype=np.float32))
    with torch.no_grad():
        reconstructed = model(tensor)
        errors = ((reconstructed - tensor) ** 2).mean(dim=1)
    return errors.cpu().numpy()

# Calculate frame-level errors for normal training recordings
spec_train_errors = reconstruction_errors(
    spectral_model, data["X_spec_train"]
)
temp_train_errors = reconstruction_errors(
    temporal_model, data["X_temp_train"]
)

# Recalculate validation errors consistently
spec_val_errors = reconstruction_errors(
    spectral_model, data["X_spec_val"]
)
temp_val_errors = reconstruction_errors(
    temporal_model, data["X_temp_val"]
)

# Aggregate frames into one score per recording
def recording_means(frame_errors, frames_per_recording):
    assert len(frame_errors) % frames_per_recording == 0
    return frame_errors.reshape(-1, frames_per_recording).mean(axis=1)

spec_train_recording = recording_means(spec_train_errors, 313)
temp_train_recording = recording_means(temp_train_errors, 312)
spec_val_recording = recording_means(spec_val_errors, 313)
temp_val_recording = recording_means(temp_val_errors, 312)

# Calibrate the two score scales using training scores only.
# This is exploratory calibration, not final threshold selection.
def standardize_scores(scores, reference):
    mean = reference.mean()
    std = reference.std()
    if std < 1e-8:
        std = 1.0
    return (scores - mean) / std

spec_val_z = standardize_scores(spec_val_recording, spec_train_recording)
temp_val_z = standardize_scores(temp_val_recording, temp_train_recording)

# Equal-weight fusion for inspection only
fusion_val = (spec_val_z + temp_val_z) / 2

results = pd.DataFrame({
    "filename": data["val_filenames"],
    "label": "normal",
    "spectral_score": spec_val_recording,
    "temporal_score": temp_val_recording,
    "spectral_standardized": spec_val_z,
    "temporal_standardized": temp_val_z,
    "fusion_score_exploratory": fusion_val,
})

out_path = experiments_dir / "aurix_pathway_validation_scores_seed13711.csv"
results.to_csv(out_path, index=False)

print("Validation recordings:", len(results))
print("All scores finite:", np.isfinite(
    results.select_dtypes(include=[np.number]).to_numpy()
).all())
print("\nPer-recording scores:")
display(results.round(4))
print("\nSaved:", out_path)

Validation recordings: 5
All scores finite: True

Per-recording scores:

,filename,label,spectral_score,temporal_score,spectral_standardized,temporal_standardized,fusion_score_exploratory
0,section_00_source_train_normal_0006_noAttribut...,normal,0.5119,0.9183,-0.8993,1.1454,0.1231
1,section_00_source_train_normal_0012_noAttribut...,normal,0.5439,0.9122,-0.3553,0.8894,0.2670
2,section_00_source_train_normal_0017_noAttribut...,normal,0.6044,0.8563,0.6686,-1.4351,-0.3833
3,section_00_source_train_normal_0020_noAttribut...,normal,0.5477,0.9064,-0.2920,0.6500,0.1790
4,section_00_source_train_normal_0023_noAttribut...,normal,0.5986,0.9191,0.5702,1.1780,0.8741

Saved: /content/AURIX.V1/experiments/aurix_pathway_validation_scores_seed13711.csv

In [129]:
from pathlib import Path
import numpy as np
import pandas as pd
import librosa
import torch
from sklearn.metrics import roc_auc_score, average_precision_score

# Existing project files
exp = Path("/content/AURIX.V1/experiments")
test_dir = Path("/content/AURIX_data/bearingEmu/test")
data = np.load(exp / "aurix_specialized_features_pilot_seed13711.npz")

device = torch.device("cpu")

# Recreate the exact model architecture used during training
class SmallAutoencoder(torch.nn.Module):
    def __init__(self, input_dim=128, hidden_dim=32, bottleneck_dim=8):
        super().__init__()
        self.net = torch.nn.Sequential(
            torch.nn.Linear(input_dim, hidden_dim),
            torch.nn.ReLU(),
            torch.nn.Linear(hidden_dim, bottleneck_dim),
            torch.nn.ReLU(),
            torch.nn.Linear(bottleneck_dim, hidden_dim),
            torch.nn.ReLU(),
            torch.nn.Linear(hidden_dim, input_dim),
        )

    def forward(self, x):
        return self.net(x)

spectral_model = SmallAutoencoder()
spectral_model.load_state_dict(
    torch.load(exp / "aurix_spectral_pilot_seed13711.pt",
               map_location="cpu", weights_only=True)
)
spectral_model.eval()

temporal_model = SmallAutoencoder()
temporal_model.load_state_dict(
    torch.load(exp / "aurix_temporal_pilot_seed13711.pt",
               map_location="cpu", weights_only=True)
)
temporal_model.eval()

# Extract features and apply training-only normalization
def features_for_file(path):
    audio, sr = librosa.load(str(path), sr=16000, mono=False)
    ch0 = audio[0] if audio.ndim == 2 else audio

    mel = librosa.feature.melspectrogram(
        y=ch0, sr=sr, n_fft=1024, hop_length=512,
        n_mels=128, power=2.0, fmin=0, fmax=8000
    )
    log_mel = 10 * np.log10(
        np.maximum(mel, np.finfo(np.float32).eps)
    ).astype(np.float32)

    spectral = log_mel.T
    temporal = np.diff(log_mel, axis=1).T

    spectral = (spectral - data["spec_mean"]) / data["spec_std"]
    temporal = (temporal - data["temp_mean"]) / data["temp_std"]

    return spectral.astype(np.float32), temporal.astype(np.float32)

def frame_errors(model, X):
    with torch.no_grad():
        x = torch.from_numpy(X)
        reconstructed = model(x)
        return ((reconstructed - x) ** 2).mean(dim=1).numpy()

# Calibrate score scales using only the pilot's normal training recordings
spec_train_errors = frame_errors(spectral_model, data["X_spec_train"])
temp_train_errors = frame_errors(temporal_model, data["X_temp_train"])

spec_train_scores = spec_train_errors.reshape(-1, 313).mean(axis=1)
temp_train_scores = temp_train_errors.reshape(-1, 312).mean(axis=1)

def zscore(scores, reference):
    std = reference.std()
    if std < 1e-8:
        std = 1.0
    return (scores - reference.mean()) / std

# Score every test recording
rows = []
files = sorted(test_dir.glob("*.wav"))
assert files, f"No WAV files found in {test_dir}"

for i, path in enumerate(files, start=1):
    spec, temp = features_for_file(path)

    spec_score = frame_errors(spectral_model, spec).mean()
    temp_score = frame_errors(temporal_model, temp).mean()

    spec_z = zscore(np.array([spec_score]), spec_train_scores)[0]
    temp_z = zscore(np.array([temp_score]), temp_train_scores)[0]

    # Labels are parsed from the dataset filenames
    label = 1 if "_anomaly_" in path.name else 0

    rows.append({
        "filename": path.name,
        "label": label,
        "spectral_score": spec_score,
        "temporal_score": temp_score,
        "spectral_z": spec_z,
        "temporal_z": temp_z,
        "fusion_score": (spec_z + temp_z) / 2,
    })

    if i % 25 == 0 or i == len(files):
        print(f"Scored {i}/{len(files)} recordings")

results = pd.DataFrame(rows)
assert results["label"].nunique() == 2, "Expected normal and anomaly labels"

# Save without overwriting previous experiments
scores_path = exp / "aurix_specialized_test_scores_exploratory_seed13711.csv"
results.to_csv(scores_path, index=False)

print("\nTest label counts:")
print(results["label"].map({0: "normal", 1: "anomaly"}).value_counts())

print("\nExploratory metrics (higher is better):")
for name, column in [
    ("Spectral", "spectral_score"),
    ("Temporal", "temporal_score"),
    ("Fusion", "fusion_score"),
]:
    auc = roc_auc_score(results["label"], results[column])
    ap = average_precision_score(results["label"], results[column])
    print(f"{name:10s} ROC-AUC={auc:.4f} | Average Precision={ap:.4f}")

print("\nSaved scores:", scores_path)
print("All numeric scores finite:",
      np.isfinite(results.select_dtypes(include=[np.number]).to_numpy()).all())

Scored 25/200 recordings
Scored 50/200 recordings
Scored 75/200 recordings
Scored 100/200 recordings
Scored 125/200 recordings
Scored 150/200 recordings
Scored 175/200 recordings
Scored 200/200 recordings

Test label counts:
label
anomaly    100
normal     100
Name: count, dtype: int64

Exploratory metrics (higher is better):
Spectral   ROC-AUC=0.5517 | Average Precision=0.5795
Temporal   ROC-AUC=0.4506 | Average Precision=0.4796
Fusion     ROC-AUC=0.5600 | Average Precision=0.5595

Saved scores: /content/AURIX.V1/experiments/aurix_specialized_test_scores_exploratory_seed13711.csv
All numeric scores finite: True

In [130]:
from pathlib import Path
import pandas as pd
from sklearn.metrics import roc_auc_score, average_precision_score

path = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_specialized_test_scores_exploratory_seed13711.csv"
)
df = pd.read_csv(path)

df["domain"] = df["filename"].str.extract(r"_(source|target)_")

score_columns = {
    "Spectral": "spectral_score",
    "Temporal": "temporal_score",
    "Fusion": "fusion_score",
}

for domain in ["source", "target"]:
    subset = df[df["domain"] == domain]

    print(f"\n--- {domain.upper()} ---")
    print("Recordings:", len(subset))
    print("Normal:", (subset["label"] == 0).sum())
    print("Anomaly:", (subset["label"] == 1).sum())

    if subset["label"].nunique() < 2:
        print("Not enough label classes for AUC.")
        continue

    for name, col in score_columns.items():
        auc = roc_auc_score(subset["label"], subset[col])
        ap = average_precision_score(subset["label"], subset[col])

        normal_mean = subset.loc[
            subset["label"] == 0, col
        ].mean()
        anomaly_mean = subset.loc[
            subset["label"] == 1, col
        ].mean()

        print(
            f"{name}: AUC={auc:.4f}, AP={ap:.4f}, "
            f"mean normal={normal_mean:.4f}, "
            f"mean anomaly={anomaly_mean:.4f}"
        )

--- SOURCE ---
Recordings: 100
Normal: 50
Anomaly: 50
Spectral: AUC=0.5256, AP=0.5654, mean normal=0.6441, mean anomaly=0.7028
Temporal: AUC=0.4436, AP=0.4691, mean normal=0.8908, mean anomaly=0.8825
Fusion: AUC=0.5484, AP=0.5652, mean normal=0.6706, mean anomaly=0.9951

--- TARGET ---
Recordings: 100
Normal: 50
Anomaly: 50
Spectral: AUC=0.5768, AP=0.6051, mean normal=0.6419, mean anomaly=0.6740
Temporal: AUC=0.4604, AP=0.5032, mean normal=0.8923, mean anomaly=0.8846
Fusion: AUC=0.5676, AP=0.5623, mean normal=0.6828, mean anomaly=0.7953

In [131]:
from pathlib import Path
import pandas as pd

path = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_specialized_test_scores_exploratory_seed13711.csv"
)
df = pd.read_csv(path)
df["domain"] = df["filename"].str.extract(r"_(source|target)_")

score_columns = ["spectral_score", "temporal_score", "fusion_score"]

for domain in ["source", "target"]:
    print(f"\n========== {domain.upper()} ==========")

    subset = df[df["domain"] == domain]

    for label, label_name in [(0, "NORMAL"), (1, "ANOMALY")]:
        group = subset[subset["label"] == label]

        print(f"\n{label_name} (n={len(group)})")

        print(
            group[score_columns]
            .agg(["median", "std", "min", "max"])
            .round(4)
        )

========== SOURCE ==========

NORMAL (n=50)
        spectral_score  temporal_score  fusion_score
median          0.5920          0.8899        0.2478
std             0.2051          0.0266        1.9557
min             0.4807          0.8397       -1.3661
max             1.6640          0.9546        9.7778

ANOMALY (n=50)
        spectral_score  temporal_score  fusion_score
median          0.5781          0.8858        0.3844
std             0.2386          0.0309        1.8159
min             0.5090          0.8135       -1.5081
max             1.3854          0.9449        6.8248

========== TARGET ==========

NORMAL (n=50)
        spectral_score  temporal_score  fusion_score
median          0.5779          0.8887        0.1592
std             0.2191          0.0260        2.2040
min             0.4790          0.8402       -1.3152
max             1.9931          0.9793       13.9468

ANOMALY (n=50)
        spectral_score  temporal_score  fusion_score
median          0.6283          0.8861        0.3836
std             0.1593          0.0334        1.3081
min             0.4968          0.8168       -0.7923
max             1.1424          0.9451        4.5115

In [132]:
from pathlib import Path
import pandas as pd

path = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_specialized_test_scores_exploratory_seed13711.csv"
)

df = pd.read_csv(path)

cols = [
    "filename",
    "label",
    "spectral_score",
    "temporal_score",
    "fusion_score",
]

print("Largest fusion scores:")
print(
    df[cols]
    .sort_values("fusion_score", ascending=False)
    .head(10)
    .to_string(index=False)
)

Largest fusion scores:
                                           filename  label  spectral_score  temporal_score  fusion_score
 section_00_target_test_normal_0014_noAttribute.wav      0        1.993132        0.979348     13.946757
 section_00_source_test_normal_0029_noAttribute.wav      0        1.663979        0.913081      9.777767
 section_00_source_test_normal_0048_noAttribute.wav      0        1.282647        0.954633      7.411197
section_00_source_test_anomaly_0035_noAttribute.wav      1        1.343713        0.901606      6.824763
section_00_source_test_anomaly_0022_noAttribute.wav      1        1.385351        0.818758      5.452881
 section_00_source_test_normal_0037_noAttribute.wav      0        1.137855        0.898608      5.017806
section_00_target_test_anomaly_0024_noAttribute.wav      1        0.963894        0.945102      4.511490
section_00_source_test_anomaly_0026_noAttribute.wav      1        1.188105        0.839578      4.214742
 section_00_target_test_normal_0037_noAttribute.wav      0        0.939433        0.938321      4.163032
section_00_source_test_anomaly_0033_noAttribute.wav      1        1.091425        0.873574      4.103158

In [133]:
from pathlib import Path
import pandas as pd
import numpy as np

root = Path("/content/AURIX.V1/experiments")

files = [
    root / "aurix_specialized_test_scores_exploratory_seed13711.csv",
    root / "aurix_pathway_validation_scores_seed13711.csv",
]

for path in files:
    if not path.exists():
        continue

    df = pd.read_csv(path)
    print(f"\n--- {path.name} ---")
    print("Columns:", df.columns.tolist())

    cols = [
        c for c in [
            "spectral_score", "temporal_score",
            "spectral_z", "temporal_z", "fusion_score"
        ]
        if c in df.columns
    ]

    print(df[cols].describe().round(4).to_string())

print("\n--- Saved model artifacts ---")
for path in sorted(root.glob("aurix_*pilot_seed13711*")):
    print(path.name)

--- aurix_specialized_test_scores_exploratory_seed13711.csv ---
Columns: ['filename', 'label', 'spectral_score', 'temporal_score', 'spectral_z', 'temporal_z', 'fusion_score']
       spectral_score  temporal_score  spectral_z  temporal_z  fusion_score
count        200.0000        200.0000    200.0000    200.0000      200.0000
mean           0.6657          0.8875      1.7079     -0.1360        0.7859
std            0.2075          0.0294      3.5174      1.2255        1.8407
min            0.4790          0.8135     -1.4569     -3.2188       -1.5081
25%            0.5422          0.8720     -0.3854     -0.7827       -0.2706
50%            0.5932          0.8870      0.4801     -0.1571        0.2736
75%            0.7206          0.9064      2.6393      0.6498        1.1234
max            1.9931          0.9793     24.2071      3.6865       13.9468

--- aurix_pathway_validation_scores_seed13711.csv ---
Columns: ['filename', 'label', 'spectral_score', 'temporal_score', 'spectral_standardized', 'temporal_standardized', 'fusion_score_exploratory']
       spectral_score  temporal_score
count          5.0000          5.0000
mean           0.5613          0.9025
std            0.0393          0.0263
min            0.5119          0.8563
25%            0.5439          0.9064
50%            0.5477          0.9122
75%            0.5986          0.9183
max            0.6044          0.9191

--- Saved model artifacts ---
aurix_specialized_features_pilot_seed13711.npz
aurix_spectral_pilot_seed13711.pt
aurix_temporal_pilot_seed13711.pt

In [135]:
import json
from pathlib import Path

notebook = Path("/content/AURIX.V1/AURIX.ipynb")
data = json.loads(notebook.read_text(encoding="utf-8"))

terms = [
    "fusion_score",
    "spectral_z",
    "temporal_z",
    "spec_train_scores",
    "temp_train_scores",
    "standardized",
]

for i, cell in enumerate(data.get("cells", [])):
    source = "".join(cell.get("source", []))

    if cell.get("cell_type") == "code" and any(
        term in source for term in terms
    ):
        print(f"\n{'=' * 20} CELL {i} {'=' * 20}")
        print(source[:7000])

In [136]:
from pathlib import Path

root = Path("/content/AURIX.V1")

for folder in [root, root / "experiments"]:
    print(f"\n--- {folder} ---")
    if folder.exists():
        for p in sorted(folder.iterdir()):
            if p.is_file() and (
                p.suffix in [".py", ".ipynb"]
                or "specialized" in p.name.lower()
                or "pathway" in p.name.lower()
            ):
                print(p.name)
    else:
        print("Folder not found")

--- /content/AURIX.V1 ---
AURIX.ipynb

--- /content/AURIX.V1/experiments ---
aurix_pathway_validation_scores_seed13711.csv
aurix_specialized_features_pilot_seed13711.npz
aurix_specialized_test_scores_exploratory_seed13711.csv

In [137]:
import json
from pathlib import Path

p = Path("/content/AURIX.V1/AURIX.ipynb")
nb = json.loads(p.read_text(encoding="utf-8"))

for i, cell in enumerate(nb.get("cells", [])):
    if cell.get("cell_type") == "code":
        source = "".join(cell.get("source", []))
        if source.strip():
            print(f"\n--- CELL {i} ---")
            print(source[:900].replace("\n", "\n"))

--- CELL 1 ---
!nvidia-smi

--- CELL 2 ---
# AURIX — Project Configuration

PROJECT_NAME = "AURIX"
RANDOM_SEED = 42

print(f"{PROJECT_NAME} configuration loaded.")

In [138]:
from pathlib import Path
import torch

folder = Path("/content/AURIX.V1/experiments")

for name in [
    "aurix_spectral_pilot_seed13711.pt",
    "aurix_temporal_pilot_seed13711.pt",
]:
    path = folder / name
    print(f"\n{name}")
    print("Exists:", path.exists())

    if path.exists():
        checkpoint = torch.load(path, map_location="cpu", weights_only=True)
        print("Saved object type:", type(checkpoint).__name__)

        if isinstance(checkpoint, dict):
            print("Keys:", list(checkpoint.keys()))
            for key, value in checkpoint.items():
                if isinstance(value, dict):
                    print(f"  {key}: state-dict keys = {list(value.keys())[:8]}")
                elif hasattr(value, "shape"):
                    print(f"  {key}: shape = {tuple(value.shape)}")
                else:
                    print(f"  {key}: {type(value).__name__}")

aurix_spectral_pilot_seed13711.pt
Exists: True
Saved object type: OrderedDict
Keys: ['net.0.weight', 'net.0.bias', 'net.2.weight', 'net.2.bias', 'net.4.weight', 'net.4.bias', 'net.6.weight', 'net.6.bias']
  net.0.weight: shape = (32, 128)
  net.0.bias: shape = (32,)
  net.2.weight: shape = (8, 32)
  net.2.bias: shape = (8,)
  net.4.weight: shape = (32, 8)
  net.4.bias: shape = (32,)
  net.6.weight: shape = (128, 32)
  net.6.bias: shape = (128,)

aurix_temporal_pilot_seed13711.pt
Exists: True
Saved object type: OrderedDict
Keys: ['net.0.weight', 'net.0.bias', 'net.2.weight', 'net.2.bias', 'net.4.weight', 'net.4.bias', 'net.6.weight', 'net.6.bias']
  net.0.weight: shape = (32, 128)
  net.0.bias: shape = (32,)
  net.2.weight: shape = (8, 32)
  net.2.bias: shape = (8,)
  net.4.weight: shape = (32, 8)
  net.4.bias: shape = (32,)
  net.6.weight: shape = (128, 32)
  net.6.bias: shape = (128,)

In [139]:
import numpy as np
import torch
import torch.nn as nn
from pathlib import Path

root = Path("/content/AURIX.V1/experiments")

data = np.load(root / "aurix_specialized_features_pilot_seed13711.npz")

class SmallAutoencoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(128, 32),
            nn.ReLU(),
            nn.Linear(32, 8),
            nn.ReLU(),
            nn.Linear(8, 32),
            nn.ReLU(),
            nn.Linear(32, 128),
        )

    def forward(self, x):
        return self.net(x)

def recording_errors(features, model, frames_per_recording):
    model.eval()
    with torch.no_grad():
        x = torch.as_tensor(features, dtype=torch.float32)
        frame_errors = ((model(x) - x) ** 2).mean(dim=1).numpy()

    n = len(frame_errors) // frames_per_recording
    if n * frames_per_recording != len(frame_errors):
        raise ValueError("عدد الـ frames مش متوافق مع طول التسجيلات.")

    return frame_errors.reshape(n, frames_per_recording).mean(axis=1)

models = {
    "Spectral": (
        "aurix_spectral_pilot_seed13711.pt",
        "X_spec_train",
        313,
    ),
    "Temporal": (
        "aurix_temporal_pilot_seed13711.pt",
        "X_temp_train",
        312,
    ),
}

for name, (filename, feature_key, frames) in models.items():
    model = SmallAutoencoder()
    model.load_state_dict(
        torch.load(root / filename, map_location="cpu", weights_only=True)
    )

    scores = recording_errors(data[feature_key], model, frames)

    print(f"\n--- {name} training scores ---")
    print("Number of recordings:", len(scores))
    print("Mean:", round(float(scores.mean()), 6))
    print("Std (ddof=0):", round(float(scores.std()), 6))
    print("Std (ddof=1):", round(float(scores.std(ddof=1)), 6))
    print("Min:", round(float(scores.min()), 6))
    print("Median:", round(float(np.median(scores)), 6))
    print("Max:", round(float(scores.max()), 6))
    print("All finite:", bool(np.isfinite(scores).all()))

--- Spectral training scores ---
Number of recordings: 20
Mean: 0.564911
Std (ddof=0): 0.059
Std (ddof=1): 0.060533
Min: 0.482798
Median: 0.54067
Max: 0.706199
All finite: True

--- Temporal training scores ---
Number of recordings: 20
Mean: 0.890809
Std (ddof=0): 0.024017
Std (ddof=1): 0.024641
Min: 0.8509
Median: 0.896262
Max: 0.930245
All finite: True

In [140]:
import pandas as pd
import numpy as np
from pathlib import Path

p = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_specialized_test_scores_exploratory_seed13711.csv"
)
df = pd.read_csv(p)

# إعادة حساب الـ Fusion من درجات z المحفوظة
df["fusion_recomputed"] = (
    df["spectral_z"] + df["temporal_z"]
) / 2

print("Rows:", len(df))
print(
    "Max absolute difference:",
    float(np.max(np.abs(
        df["fusion_score"] - df["fusion_recomputed"]
    )))
)
print(
    "Correlation between saved and recomputed fusion:",
    float(df["fusion_score"].corr(df["fusion_recomputed"]))
)

print("\nLargest spectral z-scores:")
print(
    df.nlargest(5, "spectral_z")[
        ["filename", "label", "spectral_z",
         "temporal_z", "fusion_score", "fusion_recomputed"]
    ].to_string(index=False)
)

Rows: 200
Max absolute difference: 5.999999999062311e-07
Correlation between saved and recomputed fusion: 0.9999999999999992

Largest spectral z-scores:
                                           filename  label  spectral_z  temporal_z  fusion_score  fusion_recomputed
 section_00_target_test_normal_0014_noAttribute.wav      0   24.207054    3.686461     13.946757          13.946758
 section_00_source_test_normal_0029_noAttribute.wav      0   18.628206    0.927328      9.777767           9.777767
section_00_source_test_anomaly_0022_noAttribute.wav      1   13.905721   -2.999958      5.452881           5.452882
section_00_source_test_anomaly_0035_noAttribute.wav      1   13.199987    0.449539      6.824763           6.824763
 section_00_source_test_normal_0048_noAttribute.wav      0   12.164973    2.657421      7.411197           7.411197

In [141]:
import pandas as pd
from pathlib import Path
from sklearn.metrics import roc_auc_score, average_precision_score

p = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_specialized_test_scores_exploratory_seed13711.csv"
)
df = pd.read_csv(p)

def report(data, title):
    y = data["label"]
    print(f"\n{title} (n={len(data)})")
    for col in ["spectral_z", "fusion_score"]:
        print(
            f"{col}: "
            f"AUC={roc_auc_score(y, data[col]):.4f}, "
            f"AP={average_precision_score(y, data[col]):.4f}"
        )

report(df, "Original exploratory results")

# تشخيص فقط: إزالة أعلى خمس درجات Spectral، بغض النظر عن الفئة
top5_indices = df.nlargest(5, "spectral_z").index
diagnostic = df.drop(index=top5_indices)

print("\nRemoved recordings (diagnostic only):")
print(df.loc[top5_indices, ["filename", "label", "spectral_z"]].to_string(index=False))

report(diagnostic, "Diagnostic results after removing top 5 spectral scores")

Original exploratory results (n=200)
spectral_z: AUC=0.5517, AP=0.5795
fusion_score: AUC=0.5600, AP=0.5595

Removed recordings (diagnostic only):
                                           filename  label  spectral_z
 section_00_target_test_normal_0014_noAttribute.wav      0   24.207054
 section_00_source_test_normal_0029_noAttribute.wav      0   18.628206
section_00_source_test_anomaly_0022_noAttribute.wav      1   13.905721
section_00_source_test_anomaly_0035_noAttribute.wav      1   13.199987
 section_00_source_test_normal_0048_noAttribute.wav      0   12.164973

Diagnostic results after removing top 5 spectral scores (n=195)
spectral_z: AUC=0.5598, AP=0.6292
fusion_score: AUC=0.5687, AP=0.5921

In [142]:
import pandas as pd
from pathlib import Path
from sklearn.metrics import roc_auc_score, average_precision_score

p = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_specialized_test_scores_exploratory_seed13711.csv"
)
df = pd.read_csv(p)

for domain in ["source", "target"]:
    part = df[df["filename"].str.contains(f"_{domain}_test_")]

    print(f"\n--- {domain.upper()} ---")

    for label, name in [(0, "Normal"), (1, "Anomaly")]:
        scores = part.loc[part["label"] == label, "temporal_score"]
        print(
            f"{name}: n={len(scores)}, "
            f"mean={scores.mean():.5f}, "
            f"median={scores.median():.5f}, "
            f"std={scores.std():.5f}"
        )

    print(
        "Temporal ROC-AUC:",
        round(roc_auc_score(part["label"], part["temporal_score"]), 4)
    )
    print(
        "Temporal AP:",
        round(average_precision_score(part["label"], part["temporal_score"]), 4)
    )

--- SOURCE ---
Normal: n=50, mean=0.89079, median=0.88992, std=0.02657
Anomaly: n=50, mean=0.88247, median=0.88579, std=0.03094
Temporal ROC-AUC: 0.4436
Temporal AP: 0.4691

--- TARGET ---
Normal: n=50, mean=0.89228, median=0.88874, std=0.02596
Anomaly: n=50, mean=0.88462, median=0.88613, std=0.03335
Temporal ROC-AUC: 0.4604
Temporal AP: 0.5032

In [143]:
import pandas as pd
from pathlib import Path
from sklearn.metrics import roc_auc_score, average_precision_score

p = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_specialized_test_scores_exploratory_seed13711.csv"
)
df = pd.read_csv(p)

for domain in ["source", "target", "all"]:
    if domain == "all":
        part = df
    else:
        part = df[df["filename"].str.contains(f"_{domain}_test_")]

    y = part["label"]
    score = part["temporal_score"]

    print(f"\n--- {domain.upper()} ---")
    print(
        "Original:",
        f"AUC={roc_auc_score(y, score):.4f},",
        f"AP={average_precision_score(y, score):.4f}"
    )
    print(
        "Reversed:",
        f"AUC={roc_auc_score(y, -score):.4f},",
        f"AP={average_precision_score(y, -score):.4f}"
    )

--- SOURCE ---
Original: AUC=0.4436, AP=0.4691
Reversed: AUC=0.5564, AP=0.6134

--- TARGET ---
Original: AUC=0.4604, AP=0.5032
Reversed: AUC=0.5396, AP=0.6308

--- ALL ---
Original: AUC=0.4506, AP=0.4796
Reversed: AUC=0.5494, AP=0.6209

In [144]:
import pandas as pd
from pathlib import Path

p = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_pathway_validation_scores_seed13711.csv"
)
df = pd.read_csv(p)

print("Number of validation recordings:", len(df))
print("Columns:", df.columns.tolist())
print("\nValidation scores:")
print(df.to_string(index=False))
print("\nLabel counts:")
print(df["label"].value_counts(dropna=False).sort_index())

Number of validation recordings: 5
Columns: ['filename', 'label', 'spectral_score', 'temporal_score', 'spectral_standardized', 'temporal_standardized', 'fusion_score_exploratory']

Validation scores:
                                           filename  label  spectral_score  temporal_score  spectral_standardized  temporal_standardized  fusion_score_exploratory
section_00_source_train_normal_0006_noAttribute.wav normal        0.511855        0.918319              -0.899258               1.145416                  0.123079
section_00_source_train_normal_0012_noAttribute.wav normal        0.543947        0.912169              -0.355328               0.889375                  0.267024
section_00_source_train_normal_0017_noAttribute.wav normal        0.604358        0.856341               0.668594              -1.435124                 -0.383265
section_00_source_train_normal_0020_noAttribute.wav normal        0.547682        0.906420              -0.292015               0.649999                  0.178992
section_00_source_train_normal_0023_noAttribute.wav normal        0.598553        0.919102               0.570194               1.178023                  0.874108

Label counts:
label
normal    5
Name: count, dtype: int64

In [145]:
import pandas as pd
from pathlib import Path

p = Path(
    "/content/AURIX.V1/experiments/"
    "recording_split_seed13711.csv"
)
df = pd.read_csv(p)

print("Total recordings:", len(df))
print("\nSplit counts:")
print(df["split"].value_counts(dropna=False))

print("\nSplit × domain:")
print(pd.crosstab(df["split"], df["domain"]))

print("\nSplit × label:")
print(pd.crosstab(df["split"], df["label"]))

print("\nSplit × domain × label:")
print(
    df.groupby(["split", "domain", "label"], dropna=False)
      .size()
      .to_string()
)

Total recordings: 1000

Split counts:
split
train         899
validation    101
Name: count, dtype: int64

Split × domain:
domain      source  target
split
train          891       8
validation      99       2

Split × label:
label       normal
split
train          899
validation     101

Split × domain × label:
split       domain  label
train       source  normal    891
            target  normal      8
validation  source  normal     99
            target  normal      2

In [146]:
from pathlib import Path
from collections import Counter

root = Path("/content/AURIX_data/bearingEmu")

for split in ["train", "test"]:
    folder = root / split
    files = sorted(folder.glob("*.wav"))

    counts = Counter()
    for p in files:
        name = p.name.lower()
        if "_normal_" in name:
            counts["normal"] += 1
        elif "_anomaly_" in name:
            counts["anomaly"] += 1
        else:
            counts["unclassified"] += 1

    print(f"\n--- {split.upper()} ---")
    print("Total WAV files:", len(files))
    print("Filename-based counts:", dict(counts))
    print("Examples:")
    for p in files[:3]:
        print(" ", p.name)
    for p in files[-3:]:
        print(" ", p.name)

--- TRAIN ---
Total WAV files: 1000
Filename-based counts: {'normal': 1000}
Examples:
  section_00_source_train_normal_0000_noAttribute.wav
  section_00_source_train_normal_0001_noAttribute.wav
  section_00_source_train_normal_0002_noAttribute.wav
  section_00_target_train_normal_0007_noAttribute.wav
  section_00_target_train_normal_0008_noAttribute.wav
  section_00_target_train_normal_0009_noAttribute.wav

--- TEST ---
Total WAV files: 200
Filename-based counts: {'anomaly': 100, 'normal': 100}
Examples:
  section_00_source_test_anomaly_0000_noAttribute.wav
  section_00_source_test_anomaly_0001_noAttribute.wav
  section_00_source_test_anomaly_0002_noAttribute.wav
  section_00_target_test_normal_0047_noAttribute.wav
  section_00_target_test_normal_0048_noAttribute.wav
  section_00_target_test_normal_0049_noAttribute.wav

In [147]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

files_to_check = [
    root / "datasets" / "machine_type_2026_dev.yaml",
    root / "datasets" / "machine_type_2026_eval.yaml",
]

for path in files_to_check:
    print(f"\n{'=' * 60}")
    print(path)
    print("Exists:", path.exists())

    if path.exists():
        print(path.read_text(encoding="utf-8")[:12000])

============================================================
/content/dcase2026_baseline_ae/datasets/machine_type_2026_dev.yaml
Exists: True
DCASE2026T2:
  machine_type:
    ToyCarEmu:
      dev:
        - "00"
    ToyCar:
      dev:
        - "00"
    bearingEmu:
      dev:
        - "00"
    fan:
      dev:
        - "00"
    gearboxEmu:
      dev:
        - "00"
    sliderEmu:
      dev:
        - "00"
    valveEmu:
      dev:
        - "00"
  section_keyword: section

============================================================
/content/dcase2026_baseline_ae/datasets/machine_type_2026_eval.yaml
Exists: True
DCASE2026T2:
  machine_type:
    ToyDrone:
      eval:
        - "00"
    ToothBrush:
      eval:
        - "00"
    SewingMachine:
      eval:
        - "00"
    BlowerDustCollector:
      eval:
        - "00"
    Sander:
      eval:
        - "00"
  section_keyword: section

In [148]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

for path in sorted(root.rglob("*.py")):
    name = path.name.lower()
    if any(word in name for word in ["eval", "score", "decision", "metric"]):
        print(f"\n--- {path.relative_to(root)} ---")
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        for i, line in enumerate(lines, 1):
            print(f"{i:4}: {line}")

--- tools/plot_anm_score.py ---
   1: from tools.plot_common import Figdata, show_figs
   2:
   3: class AnmScoreFigData():
   4:     def __init__(self):
   5:         self.figdatas = []
   6:
   7:     def anm_score_to_figdata(self, scores, title=""):
   8:         nml_scores = [x[1] for x in scores if x[0]==0]
   9:         anm_scores = [x[1] for x in scores if x[0]==1]
  10:
  11:         figdata = Figdata(
  12:             data=nml_scores,
  13:             data2=anm_scores,
  14:             type="boxplot",
  15:             labels=["nml","anm"],
  16:             ylabel="score",
  17:             title=title
  18:         )
  19:
  20:         return figdata
  21:
  22:
  23:     def append_figdata(self, figdata):
  24:         self.figdatas.append(figdata)
  25:
  26:
  27:     def show_fig(self, title="anm_score", export_dir="results", is_display_console=False):
  28:         show_figs(
  29:             *self.figdatas,
  30:             fold_interval=len(self.figdatas),
  31:             sup_title=title,
  32:             export_path=f"{export_dir}/{title}.png",
  33:             is_display_console=is_display_console
  34:         )

--- tools/rename_eval_wav.py ---
   1: import os
   2: import sys
   3: import csv
   4: import shutil
   5: import argparse
   6: from pathlib import Path
   7:
   8: ROOT_DIR = f"{os.path.dirname(os.path.abspath(__file__))}/../"
   9: os.chdir(ROOT_DIR)
  10:
  11: # labeled data path
  12: EVAL_DATA_LIST_PATH = {
  13:     "DCASE2020T2":f"{ROOT_DIR}/datasets/eval_data_list_2020.csv",
  14:     "DCASE2021T2":f"{ROOT_DIR}/datasets/eval_data_list_2021.csv",
  15:     "DCASE2022T2":f"{ROOT_DIR}/datasets/eval_data_list_2022.csv",
  16:     "DCASE2023T2":f"{ROOT_DIR}/datasets/eval_data_list_2023.csv",
  17:     "DCASE2024T2":f"{ROOT_DIR}/datasets/eval_data_list_2024.csv",
  18:     "DCASE2025T2":f"{ROOT_DIR}/datasets/eval_data_list_2025.csv",
  19:     "DCASE2026T2":f"{ROOT_DIR}/datasets/eval_data_list_2026.csv",
  20: }
  21:
  22: FILENAME_COL = 0
  23: LABELING_FILENAME_COL = 1
  24: MACHINE_TYPE_COL = 0
  25:
  26: CHK_MACHINE_TYPE_LINE = 2
  27:
  28: def copy_wav(dataset_parent_dir, dataset_type):
  29:     dataset_dir = str(Path(f"{ROOT_DIR}/{dataset_parent_dir}/raw/").relative_to(ROOT_DIR))
  30:     eval_data_list_path = EVAL_DATA_LIST_PATH[dataset_type]
  31:     if not eval_data_list_path:
  32:         return None
  33:
  34:     if os.path.exists(eval_data_list_path):
  35:         with open(eval_data_list_path) as fp:
  36:             eval_data_list = list(csv.reader(fp))
  37:     else:
  38:         print(f"Err:eval_data_list.csv not found : {eval_data_list_path}")
  39:         sys.exit(1)
  40:
  41:     count = 0
  42:     print('copy... : test -> test_rename')
  43:     for eval_data in eval_data_list:
  44:         if len(eval_data) < CHK_MACHINE_TYPE_LINE:
  45:             machine_type = eval_data[MACHINE_TYPE_COL]
  46:             default_dir = dataset_dir.lower() + "/" + machine_type + "/test"
  47:             save_dir = dataset_dir.lower() + "/" + machine_type + "/test_rename"
  48:             if(not os.path.exists(save_dir)):
  49:                 Path(save_dir).mkdir(parents=True, exist_ok=True)
  50:             count = 0
  51:             sys.stdout.write('\n')
  52:             sys.stdout.flush()
  53:         else:
  54:             if os.path.exists(default_dir + "/" + eval_data[FILENAME_COL]):
  55:                 shutil.copy2(
  56:                     default_dir + "/" + eval_data[FILENAME_COL],
  57:                     save_dir + "/" + eval_data[LABELING_FILENAME_COL])
  58:                 count += 1
  59:             sys.stdout.write(f'\r\t{machine_type}: {str(count)} files\tsaved dir: {save_dir}')
  60:             sys.stdout.flush()
  61:     sys.stdout.write('\n')
  62:
  63: if __name__ == "__main__":
  64:     parser = argparse.ArgumentParser(
  65:             description='Main function to call training for different AutoEncoders')
  66:     parser.add_argument("--dataset_parent_dir", type=str, default="data",
  67:                         help="saving datasets directory name.")
  68:     parser.add_argument("--dataset_type", type=str, required=True,
  69:                         choices=[
  70:                             "DCASE2020T2",
  71:                             "DCASE2021T2",
  72:                             "DCASE2022T2",
  73:                             "DCASE2023T2",
  74:                             "DCASE2024T2",
  75:                             "DCASE2025T2",
  76:                             "DCASE2026T2",
  77:                         ],
  78:                         help="what Dataset name to renamed.")
  79:     args = parser.parse_args()
  80:
  81:     copy_wav(
  82:         dataset_parent_dir=f"{args.dataset_parent_dir}/{args.dataset_type}/eval_data",
  83:         dataset_type=args.dataset_type
  84:     )

In [149]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

for path in [root / "train.py", root / "test.py"]:
    print(f"\n--- {path} ---")

    if path.exists():
        lines = path.read_text(
            encoding="utf-8", errors="replace"
        ).splitlines()

        for i, line in enumerate(lines, 1):
            print(f"{i:4}: {line}")
    else:
        print("File not found")

--- /content/dcase2026_baseline_ae/train.py ---
   1: import random
   2: import numpy as np
   3: import torch
   4:
   5: # original lib
   6: import common as com
   7: from networks.models import Models
   8:
   9: ########################################################################
  10: # load parameter.yaml
  11: ########################################################################
  12: param = com.yaml_load()
  13: ########################################################################
  14:
  15: def main():
  16:     parser = com.get_argparse()
  17:     # read parameters from yaml
  18:     flat_param = com.param_to_args_list(params=param)
  19:     args = parser.parse_args(args=flat_param)
  20:     # read parameters from command line
  21:     args = parser.parse_args(namespace=args)
  22:     print(args)
  23:
  24:     if args.train_only and args.test_only:
  25:         raise ValueError("--train_only and --test_only cannot be used together.")
  26:     elif args.train_only:
  27:         train = True
  28:         test = False
  29:     elif args.test_only:
  30:         train = False
  31:         test = True
  32:     else:
  33:         train = True
  34:         test = True
  35:
  36:     args.cuda = args.use_cuda and torch.cuda.is_available()
  37:
  38:     # Python random
  39:     random.seed(args.seed)
  40:     # Numpy
  41:     np.random.seed(args.seed)
  42:     # Pytorch
  43:     torch.manual_seed(args.seed)
  44:     torch.cuda.manual_seed(args.seed)
  45:     torch.backends.cudnn.deterministic = True
  46:     torch.use_deterministic_algorithms = True
  47:
  48:     net = Models(args.model).net(
  49:         args=args,
  50:         train=train,
  51:         test=test
  52:     )
  53:
  54:
  55:     print(args.model)
  56:
  57:     print("============== BEGIN TRAIN ==============")
  58:     if train:
  59:         for epoch in range(1, args.epochs + 2):
  60:             net.train(epoch)
  61:     print("============ END OF TRAIN ============")
  62:
  63:     if test:
  64:         net.test()
  65:
  66: if __name__ == "__main__":
  67:     main()

--- /content/dcase2026_baseline_ae/test.py ---
File not found

In [150]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

for path in sorted((root / "networks").rglob("*.py")):
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    matches = [
        i for i, line in enumerate(lines)
        if "def test(" in line or "def train(" in line
    ]

    for i in matches:
        start = max(0, i - 3)
        end = min(len(lines), i + 45)

        print(f"\n--- {path.relative_to(root)}:{i+1} ---")
        for j in range(start, end):
            print(f"{j+1:4}: {lines[j]}")

--- networks/base_model.py:151 ---
 148:         # determine threshold for decision
 149:         return scipy.stats.gamma.ppf(q=self.args.decision_threshold, a=shape_hat, loc=loc_hat, scale=scale_hat)
 150:
 151:     def train(self, epoch):
 152:         pass
 153:
 154:     def test(self):
 155:         pass
 156:
 157:     def copy_eval_data_score(self, decision_result_csv_path, anomaly_score_csv_path):
 158:         eval_data_decision_result_csv_path = self.eval_data_result_dir / os.path.basename(decision_result_csv_path).replace(self.model_name_suffix, "")
 159:         print(f"copy decision result: {decision_result_csv_path}\n\t->{eval_data_decision_result_csv_path}")
 160:         shutil.copyfile(decision_result_csv_path, eval_data_decision_result_csv_path)
 161:
 162:         eval_data_anomaly_score_csv_path = self.eval_data_result_dir / os.path.basename(anomaly_score_csv_path).replace(self.model_name_suffix, "")
 163:         print(f"copy anomaly score: {anomaly_score_csv_path}\n\t->{eval_data_anomaly_score_csv_path}")
 164:         shutil.copyfile(anomaly_score_csv_path, eval_data_anomaly_score_csv_path)

--- networks/base_model.py:154 ---
 151:     def train(self, epoch):
 152:         pass
 153:
 154:     def test(self):
 155:         pass
 156:
 157:     def copy_eval_data_score(self, decision_result_csv_path, anomaly_score_csv_path):
 158:         eval_data_decision_result_csv_path = self.eval_data_result_dir / os.path.basename(decision_result_csv_path).replace(self.model_name_suffix, "")
 159:         print(f"copy decision result: {decision_result_csv_path}\n\t->{eval_data_decision_result_csv_path}")
 160:         shutil.copyfile(decision_result_csv_path, eval_data_decision_result_csv_path)
 161:
 162:         eval_data_anomaly_score_csv_path = self.eval_data_result_dir / os.path.basename(anomaly_score_csv_path).replace(self.model_name_suffix, "")
 163:         print(f"copy anomaly score: {anomaly_score_csv_path}\n\t->{eval_data_anomaly_score_csv_path}")
 164:         shutil.copyfile(anomaly_score_csv_path, eval_data_anomaly_score_csv_path)

--- networks/dcase2023t2_ae/dcase2023t2_ae.py:44 ---
  41:         ]
  42:         return "loss,val_loss,recon_loss,recon_loss_source,recon_loss_target"
  43:
  44:     def train(self, epoch):
  45:         if epoch <= self.epoch:
  46:             return
  47:         torch.autograd.set_detect_anomaly(True)
  48:         train_loss = 0
  49:         train_recon_loss = 0
  50:         train_recon_loss_source = 0
  51:         train_recon_loss_target = 0
  52:         y_pred = []
  53:
  54:         train_loader = self.train_loader
  55:
  56:         if epoch == self.args.epochs + 1:
  57:             print("\n============== CALCULATE COVARIANCE ==============")
  58:             is_calc_cov = True
  59:             self.model.eval()
  60:             torch.set_grad_enabled(False)
  61:             # initialize mahalanobis param
  62:             cov_x_source = np.zeros((self.block_size, self.block_size))
  63:             cov_x_source = torch.from_numpy(cov_x_source)
  64:             cov_x_source = cov_x_source.to(self.device).float()
  65:             cov_x_target = cov_x_source.clone().detach()
  66:             num_source = 0
  67:             num_target = 0
  68:             epoch = self.args.epochs
  69:         else:
  70:             self.model.train()
  71:             is_calc_cov = False
  72:
  73:         for batch_idx, batch in enumerate(tqdm(train_loader)):
  74:             data = batch[0]
  75:             data = data.to(self.device).float()
  76:             if data.shape[0] <= 1:
  77:                 continue
  78:             data_name_list = batch[3]
  79:             machine_id = torch.argmax(batch[2], dim=1).long()
  80:             machine_id = machine_id.to(self.device)
  81:
  82:             is_target_list = ["target" in data_name for data_name in data_name_list]
  83:             is_source_list = np.logical_not(is_target_list).tolist()
  84:             n_source = is_source_list.count(True)
  85:             n_target = is_target_list.count(True)
  86:
  87:             if not is_calc_cov:
  88:                 self.optimizer.zero_grad()

--- networks/dcase2023t2_ae/dcase2023t2_ae.py:275 ---
 272:         loss = F.mse_loss(recon_x, x.view(recon_x.shape), reduction="none")
 273:         return loss
 274:
 275:     def test(self):
 276:         anm_score_figdata = AnmScoreFigData()
 277:         # check mode
 278:         # "development": mode == True
 279:         # "evaluation": mode == False
 280:         mode = self.data.mode
 281:
 282:         # initialize lines in csv for AUC and pAUC
 283:         csv_lines = []
 284:
 285:         block_size = self.data.height
 286:         if mode:
 287:             performance_over_all = []
 288:             performance = []
 289:
 290:         print("============== MODEL LOAD ==============")
 291:         # load model file
 292:         if not os.path.exists(self.model_path):
 293:             print(f"model not found -> {self.model_path} ")
 294:         self.model.load_state_dict(torch.load(self.model_path))
 295:         self.model.eval()
 296:
 297:         if self.args.score == "MAHALA":
 298:             decision_threshold = self.calc_decision_threshold(score_distr_file_path=self.mahala_score_distr_file_path)
 299:         else:
 300:             decision_threshold = self.calc_decision_threshold(score_distr_file_path=self.mse_score_distr_file_path)
 301:
 302:         dir_name = "test"
 303:         inv_cov_source, inv_cov_target = calc_inv_cov(
 304:             model=self.model,
 305:             device=self.device
 306:         )
 307:         for idx, test_loader_tmp in enumerate(self.test_loader):
 308:             section_name = f"section_{self.data.section_id_list[idx]}"
 309:             result_dir = self.result_dir if self.args.dev else self.eval_data_result_dir
 310:
 311:             # setup anomaly score file path
 312:             anomaly_score_csv = result_dir/f"anomaly_score_{self.args.dataset}_{section_name}_{dir_name}_seed{self.args.seed}{self.model_name_suffix}{self.eval_suffix}.csv"
 313:             anomaly_score_list = []
 314:
 315:             # setup decision result file path
 316:             decision_result_csv = result_dir/f"decision_result_{self.args.dataset}_{section_name}_{dir_name}_seed{self.args.seed}{self.model_name_suffix}{self.eval_suffix}.csv"
 317:             decision_result_list = []
 318:
 319:             domain_list = None

In [151]:
from pathlib import Path

path = Path(
    "/content/dcase2026_baseline_ae/networks/"
    "dcase2023t2_ae/dcase2023t2_ae.py"
)

lines = path.read_text(encoding="utf-8").splitlines()

for i in range(275, min(len(lines), 440)):
    print(f"{i+1:4}: {lines[i]}")

 276:         anm_score_figdata = AnmScoreFigData()
 277:         # check mode
 278:         # "development": mode == True
 279:         # "evaluation": mode == False
 280:         mode = self.data.mode
 281:
 282:         # initialize lines in csv for AUC and pAUC
 283:         csv_lines = []
 284:
 285:         block_size = self.data.height
 286:         if mode:
 287:             performance_over_all = []
 288:             performance = []
 289:
 290:         print("============== MODEL LOAD ==============")
 291:         # load model file
 292:         if not os.path.exists(self.model_path):
 293:             print(f"model not found -> {self.model_path} ")
 294:         self.model.load_state_dict(torch.load(self.model_path))
 295:         self.model.eval()
 296:
 297:         if self.args.score == "MAHALA":
 298:             decision_threshold = self.calc_decision_threshold(score_distr_file_path=self.mahala_score_distr_file_path)
 299:         else:
 300:             decision_threshold = self.calc_decision_threshold(score_distr_file_path=self.mse_score_distr_file_path)
 301:
 302:         dir_name = "test"
 303:         inv_cov_source, inv_cov_target = calc_inv_cov(
 304:             model=self.model,
 305:             device=self.device
 306:         )
 307:         for idx, test_loader_tmp in enumerate(self.test_loader):
 308:             section_name = f"section_{self.data.section_id_list[idx]}"
 309:             result_dir = self.result_dir if self.args.dev else self.eval_data_result_dir
 310:
 311:             # setup anomaly score file path
 312:             anomaly_score_csv = result_dir/f"anomaly_score_{self.args.dataset}_{section_name}_{dir_name}_seed{self.args.seed}{self.model_name_suffix}{self.eval_suffix}.csv"
 313:             anomaly_score_list = []
 314:
 315:             # setup decision result file path
 316:             decision_result_csv = result_dir/f"decision_result_{self.args.dataset}_{section_name}_{dir_name}_seed{self.args.seed}{self.model_name_suffix}{self.eval_suffix}.csv"
 317:             decision_result_list = []
 318:
 319:             domain_list = None
 320:             if mode:
 321:                 domain_list = []
 322:
 323:             print("\n============== BEGIN TEST FOR A SECTION ==============")
 324:             y_pred = []
 325:             y_true = []
 326:             test_loader = test_loader_tmp
 327:
 328:             with torch.no_grad():
 329:                 y_pred, anomaly_score_list, decision_result_list, domain_list = self.eval(
 330:                     test_loader=test_loader,
 331:                     y_pred=y_pred,
 332:                     anomaly_score_list=anomaly_score_list,
 333:                     decision_result_list=decision_result_list,
 334:                     domain_list=domain_list,
 335:                     y_true=y_true,
 336:                     decision_threshold=decision_threshold,
 337:                     mode=mode,
 338:                     inv_cov_source=inv_cov_source,
 339:                     inv_cov_target=inv_cov_target,
 340:                 )
 341:
 342:             # output anomaly scores
 343:             save_csv(save_file_path=anomaly_score_csv, save_data=anomaly_score_list)
 344:             print("anomaly score result ->  {}".format(anomaly_score_csv))
 345:
 346:             # output decision results
 347:             save_csv(save_file_path=decision_result_csv, save_data=decision_result_list)
 348:             print("decision result ->  {}".format(decision_result_csv))
 349:
 350:             if mode:
 351:                 # extract scores for calculation of AUC (source) and AUC (target)
 352:                 y_true_s_auc = [y_true[idx] for idx in range(len(y_true)) if domain_list[idx]=="source" or y_true[idx]==1]
 353:                 y_pred_s_auc = [y_pred[idx] for idx in range(len(y_true)) if domain_list[idx]=="source" or y_true[idx]==1]
 354:                 y_true_t_auc = [y_true[idx] for idx in range(len(y_true)) if domain_list[idx]=="target" or y_true[idx]==1]
 355:                 y_pred_t_auc = [y_pred[idx] for idx in range(len(y_true)) if domain_list[idx]=="target" or y_true[idx]==1]
 356:
 357:                 # extract scores for calculation of precision, recall, F1 score for each domain
 358:                 y_true_s = [y_true[idx] for idx in range(len(y_true)) if domain_list[idx]=="source"]
 359:                 y_pred_s = [y_pred[idx] for idx in range(len(y_true)) if domain_list[idx]=="source"]
 360:                 y_true_t = [y_true[idx] for idx in range(len(y_true)) if domain_list[idx]=="target"]
 361:                 y_pred_t = [y_pred[idx] for idx in range(len(y_true)) if domain_list[idx]=="target"]
 362:
 363:
 364:                 # calculate AUC, pAUC, precision, recall, F1 score
 365:                 auc_s = metrics.roc_auc_score(y_true_s_auc, y_pred_s_auc)
 366:                 p_auc = metrics.roc_auc_score(y_true, y_pred, max_fpr=self.args.max_fpr)
 367:                 p_auc_s = metrics.roc_auc_score(y_true_s, y_pred_s, max_fpr=self.args.max_fpr)
 368:                 tn_s, fp_s, fn_s, tp_s = metrics.confusion_matrix(y_true_s, [1 if x > decision_threshold else 0 for x in y_pred_s]).ravel()
 369:                 prec_s = tp_s / np.maximum(tp_s + fp_s, sys.float_info.epsilon)
 370:                 recall_s = tp_s / np.maximum(tp_s + fn_s, sys.float_info.epsilon)
 371:                 f1_s = 2.0 * prec_s * recall_s / np.maximum(prec_s + recall_s, sys.float_info.epsilon)
 372:
 373:                 anm_score_figdata.append_figdata(anm_score_figdata.anm_score_to_figdata(
 374:                     scores=[[t, p] for t, p in zip(y_true_s, y_pred_s)],
 375:                     title=f"{section_name}_source_AUC{auc_s}"
 376:                 ))
 377:
 378:                 print("AUC (source) : {}".format(auc_s))
 379:                 print("pAUC : {}".format(p_auc))
 380:                 print("pAUC (source) : {}".format(p_auc_s))
 381:                 print("precision (source) : {}".format(prec_s))
 382:                 print("recall (source) : {}".format(recall_s))
 383:                 print("F1 score (source) : {}".format(f1_s))
 384:
 385:                 if len(y_true_t) > 0:
 386:                     auc_t = metrics.roc_auc_score(y_true_t_auc, y_pred_t_auc)
 387:                     p_auc_t = metrics.roc_auc_score(y_true_t, y_pred_t, max_fpr=self.args.max_fpr)
 388:                     tn_t, fp_t, fn_t, tp_t = metrics.confusion_matrix(y_true_t, [1 if x > decision_threshold else 0 for x in y_pred_t]).ravel()
 389:                     prec_t = tp_t / np.maximum(tp_t + fp_t, sys.float_info.epsilon)
 390:                     recall_t = tp_t / np.maximum(tp_t + fn_t, sys.float_info.epsilon)
 391:                     f1_t = 2.0 * prec_t * recall_t / np.maximum(prec_t + recall_t, sys.float_info.epsilon)
 392:                     if len(csv_lines) == 0:
 393:                         csv_lines.append(self.result_column_dict["source_target"])
 394:                     csv_lines.append([section_name.split("_", 1)[1],
 395:                                     auc_s, auc_t, p_auc, p_auc_s, p_auc_t, prec_s, prec_t, recall_s, recall_t, f1_s, f1_t])
 396:
 397:                     performance.append([auc_s, auc_t, p_auc, p_auc_s, p_auc_t, prec_s, prec_t, recall_s, recall_t, f1_s, f1_t])
 398:                     performance_over_all.append([auc_s, auc_t, p_auc, p_auc_s, p_auc_t, prec_s, prec_t, recall_s, recall_t, f1_s, f1_t])
 399:
 400:                     anm_score_figdata.append_figdata(anm_score_figdata.anm_score_to_figdata(
 401:                         scores=[[t, p] for t, p in zip(y_true_t, y_pred_t)],
 402:                         title=f"{section_name}_target_AUC{auc_t}"
 403:                     ))
 404:                     print("AUC (target) : {}".format(auc_t))
 405:                     print("pAUC (target) : {}".format(p_auc_t))
 406:                     print("precision (target) : {}".format(prec_t))
 407:                     print("recall (target) : {}".format(recall_t))
 408:                     print("F1 score (target) : {}".format(f1_t))
 409:                 else:
 410:                     if len(csv_lines) == 0:
 411:                         csv_lines.append(self.result_column_dict["single_domain"])
 412:                     csv_lines.append([section_name.split("_", 1)[1], auc_s, p_auc, prec_s, recall_s, f1_s])
 413:
 414:                     performance.append([auc_s, p_auc, prec_s, recall_s, f1_s])
 415:                     performance_over_all.append([auc_s, p_auc, prec_s, recall_s, f1_s])
 416:
 417:
 418:             print("\n============ END OF TEST FOR A SECTION ============")
 419:
 420:         if mode:
 421:             # calculate averages for AUCs and pAUCs
 422:             amean_performance = np.mean(np.array(performance, dtype=float), axis=0)
 423:             csv_lines.append(["arithmetic mean"] + list(amean_performance))
 424:             hmean_performance = scipy.stats.hmean(np.maximum(np.array(performance, dtype=float), sys.float_info.epsilon), axis=0)
 425:             csv_lines.append(["harmonic mean"] + list(hmean_performance))
 426:             csv_lines.append([])
 427:
 428:             # output results
 429:             anm_score_figdata.show_fig(
 430:                 title=self.args.model+"_"+self.args.dataset+self.model_name_suffix+self.eval_suffix+"_anm_score",
 431:                 export_dir=result_dir
 432:             )
 433:         else:
 434:             return
 435:
 436:         result_path = result_dir/f"result_{self.args.dataset}_{dir_name}_seed{self.args.seed}{self.model_name_suffix}{self.eval_suffix}_roc.csv"
 437:         print("results -> {}".format(result_path))
 438:         save_csv(save_file_path=result_path, save_data=csv_lines)
 439:
 440:     def eval(

In [152]:
from pathlib import Path

path = Path(
    "/content/dcase2026_baseline_ae/networks/"
    "dcase2023t2_ae/dcase2023t2_ae.py"
)

lines = path.read_text(encoding="utf-8").splitlines()

for i in range(439, min(len(lines), 540)):
    print(f"{i+1:4}: {lines[i]}")

 440:     def eval(
 441:         self,
 442:         test_loader,
 443:         y_pred,
 444:         anomaly_score_list,
 445:         decision_result_list,
 446:         domain_list,
 447:         y_true,
 448:         decision_threshold,
 449:         mode,
 450:         inv_cov_source,
 451:         inv_cov_target,
 452:     ):
 453:         for j, batch in enumerate(test_loader):
 454:             data = batch[0]
 455:             data = data.to(self.device).float()
 456:             y_true.append(batch[1][0].item())
 457:             basename = batch[3][0]
 458:
 459:             recon_data, _ = self.model(data)
 460:
 461:             if self.args.score == "MAHALA":
 462:                 loss_source, num = loss_function_mahala(
 463:                     recon_x=recon_data,
 464:                     x=data,
 465:                     block_size=self.block_size,
 466:                     cov=inv_cov_source,
 467:                     use_precision=True,
 468:                     reduction=False
 469:                 )
 470:                 loss_source = self.loss_reduction(score=self.loss_reduction_1d(loss_source), n_loss=num)
 471:
 472:                 loss_target, num = loss_function_mahala(
 473:                     recon_x=recon_data,
 474:                     x=data,
 475:                     block_size=self.block_size,
 476:                     cov=inv_cov_target,
 477:                     use_precision=True,
 478:                     reduction=False
 479:                 )
 480:                 loss_target = self.loss_reduction(score=self.loss_reduction_1d(loss_target), n_loss=num)
 481:                 y_pred.append(min(loss_target.item(), loss_source.item()))
 482:             else:
 483:                 y_pred.append(self.loss_fn(recon_x=recon_data, x=data).mean().item())
 484:
 485:             # store anomaly scores
 486:             anomaly_score_list.append([basename, y_pred[-1]])
 487:
 488:             # store decision results
 489:             if y_pred[-1] > decision_threshold:
 490:                 decision_result_list.append([basename, 1])
 491:             else:
 492:                 decision_result_list.append([basename, 0])
 493:
 494:             if mode:
 495:                 domain_list.append("target" if "target" in basename else "source")
 496:         return y_pred, anomaly_score_list, decision_result_list, domain_list
 497:
 498: def save_csv(save_file_path,
 499:              save_data):
 500:     with open(save_file_path, "w", newline="") as f:
 501:         writer = csv.writer(f, lineterminator='\n')
 502:         writer.writerows(save_data)

In [153]:
from pathlib import Path

path = Path("/content/dcase2026_baseline_ae/networks/base_model.py")
lines = path.read_text(encoding="utf-8").splitlines()

for i, line in enumerate(lines):
    if "def calc_decision_threshold" in line:
        start = max(0, i - 8)
        end = min(len(lines), i + 45)

        print(f"--- base_model.py:{i+1} ---")
        for j in range(start, end):
            print(f"{j+1:4}: {lines[j]}")
        break

--- base_model.py:141 ---
 133:     def fit_anomaly_score_distribution(self, y_pred, score_distr_file_path=None):
 134:         if not score_distr_file_path:
 135:             score_distr_file_path = self.score_distr_file_path
 136:         shape_hat, loc_hat, scale_hat = scipy.stats.gamma.fit(y_pred)
 137:         gamma_params = [shape_hat, loc_hat, scale_hat]
 138:         with open(score_distr_file_path, "wb") as f:
 139:             pickle.dump(gamma_params, f, protocol=pickle.HIGHEST_PROTOCOL)
 140:
 141:     def calc_decision_threshold(self, score_distr_file_path=None):
 142:         if not score_distr_file_path:
 143:             score_distr_file_path = self.score_distr_file_path
 144:         # load anomaly score distribution for determining threshold
 145:         with open(score_distr_file_path, "rb") as f:
 146:             shape_hat, loc_hat, scale_hat = pickle.load(f)
 147:
 148:         # determine threshold for decision
 149:         return scipy.stats.gamma.ppf(q=self.args.decision_threshold, a=shape_hat, loc=loc_hat, scale=scale_hat)
 150:
 151:     def train(self, epoch):
 152:         pass
 153:
 154:     def test(self):
 155:         pass
 156:
 157:     def copy_eval_data_score(self, decision_result_csv_path, anomaly_score_csv_path):
 158:         eval_data_decision_result_csv_path = self.eval_data_result_dir / os.path.basename(decision_result_csv_path).replace(self.model_name_suffix, "")
 159:         print(f"copy decision result: {decision_result_csv_path}\n\t->{eval_data_decision_result_csv_path}")
 160:         shutil.copyfile(decision_result_csv_path, eval_data_decision_result_csv_path)
 161:
 162:         eval_data_anomaly_score_csv_path = self.eval_data_result_dir / os.path.basename(anomaly_score_csv_path).replace(self.model_name_suffix, "")
 163:         print(f"copy anomaly score: {anomaly_score_csv_path}\n\t->{eval_data_anomaly_score_csv_path}")
 164:         shutil.copyfile(anomaly_score_csv_path, eval_data_anomaly_score_csv_path)

In [154]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

for path in sorted(root.rglob("*.py")):
    try:
        lines = path.read_text(
            encoding="utf-8", errors="replace"
        ).splitlines()
    except Exception:
        continue

    for i, line in enumerate(lines):
        if "fit_anomaly_score_distribution(" in line:
            if "def fit_anomaly_score_distribution" in line:
                continue

            print(f"\n--- {path.relative_to(root)}:{i+1} ---")
            start = max(0, i - 8)
            end = min(len(lines), i + 10)

            for j in range(start, end):
                print(f"{j+1:4}: {lines[j]}")

--- networks/dcase2023t2_ae/dcase2023t2_ae.py:179 ---
 171:                 )
 172:             for batch_idx, batch in enumerate(self.valid_loader):
 173:                 y_pred_mahala = self.calc_valid_mahala_score(
 174:                     data=batch[0],
 175:                     y_pred=y_pred_mahala,
 176:                     inv_cov_source=inv_cov_source,
 177:                     inv_cov_target=inv_cov_target,
 178:                 )
 179:             self.fit_anomaly_score_distribution(
 180:                 y_pred=y_pred_mahala,
 181:                 score_distr_file_path=self.mahala_score_distr_file_path
 182:             )
 183:
 184:         # validation test
 185:         val_loss = 0
 186:         with torch.no_grad():
 187:             self.model.eval()
 188:             for batch_idx, batch in enumerate(self.valid_loader):

--- networks/dcase2023t2_ae/dcase2023t2_ae.py:225 ---
 217:                     )],fmt="%s")
 218:             csv_to_figdata(
 219:                 file_path=self.log_path,
 220:                 column_heading_list=self.column_heading_list,
 221:                 ylabel="loss",
 222:                 fig_count=len(self.column_heading_list),
 223:                 cut_first_epoch=True
 224:             )
 225:             self.fit_anomaly_score_distribution(
 226:                 y_pred=y_pred,
 227:                 score_distr_file_path=self.mse_score_distr_file_path
 228:             )
 229:
 230:         # save model
 231:         torch.save(self.model.state_dict(), self.model_path)
 232:         torch.save({
 233:             'epoch':epoch,
 234:             'model_state_dict':self.model.state_dict(),

In [155]:
from pathlib import Path

path = Path(
    "/content/dcase2026_baseline_ae/networks/"
    "dcase2023t2_ae/dcase2023t2_ae.py"
)

lines = path.read_text(encoding="utf-8").splitlines()

for i in range(155, min(len(lines), 235)):
    print(f"{i+1:4}: {lines[i]}")

 156:                 cov_x_target /= num_target - 1
 157:             self.model.cov_source.data = cov_x_source
 158:             self.model.cov_target.data = cov_x_target
 159:
 160:             inv_cov_source, inv_cov_target = calc_inv_cov(
 161:                 model=self.model,
 162:                 device=self.device
 163:             )
 164:             y_pred_mahala = []
 165:             for batch_idx, batch in enumerate(tqdm(train_loader)):
 166:                 y_pred_mahala = self.calc_valid_mahala_score(
 167:                     data=batch[0],
 168:                     y_pred=y_pred_mahala,
 169:                     inv_cov_source=inv_cov_source,
 170:                     inv_cov_target=inv_cov_target,
 171:                 )
 172:             for batch_idx, batch in enumerate(self.valid_loader):
 173:                 y_pred_mahala = self.calc_valid_mahala_score(
 174:                     data=batch[0],
 175:                     y_pred=y_pred_mahala,
 176:                     inv_cov_source=inv_cov_source,
 177:                     inv_cov_target=inv_cov_target,
 178:                 )
 179:             self.fit_anomaly_score_distribution(
 180:                 y_pred=y_pred_mahala,
 181:                 score_distr_file_path=self.mahala_score_distr_file_path
 182:             )
 183:
 184:         # validation test
 185:         val_loss = 0
 186:         with torch.no_grad():
 187:             self.model.eval()
 188:             for batch_idx, batch in enumerate(self.valid_loader):
 189:                 data = batch[0]
 190:                 data = data.to(self.device).float()
 191:
 192:                 recon_batch, _ = self.model(data)
 193:                 score = self.loss_fn(
 194:                     recon_batch,
 195:                     data
 196:                 )
 197:                 loss = score.mean()
 198:
 199:                 val_loss += float(loss)
 200:
 201:                 # calculate y_pred for fitting anomaly score distribution
 202:                 y_pred.append(loss.item())
 203:
 204:         if not is_calc_cov:
 205:             # plot train log
 206:             print('====> Epoch: {} Average loss: {:.4f} Validation loss: {:.4f}'.format(
 207:                   epoch,
 208:                   train_loss / len(train_loader),
 209:                   val_loss / len(self.valid_loader)))
 210:             with open(self.log_path, 'a') as log:
 211:                 np.savetxt(log,["{0},{1},{2},{3},{4}".format(
 212:                     train_loss / len(train_loader),
 213:                     val_loss / len(self.valid_loader),
 214:                     train_recon_loss / len(train_loader),
 215:                     train_recon_loss_source / len(train_loader),
 216:                     train_recon_loss_target / len(train_loader),
 217:                     )],fmt="%s")
 218:             csv_to_figdata(
 219:                 file_path=self.log_path,
 220:                 column_heading_list=self.column_heading_list,
 221:                 ylabel="loss",
 222:                 fig_count=len(self.column_heading_list),
 223:                 cut_first_epoch=True
 224:             )
 225:             self.fit_anomaly_score_distribution(
 226:                 y_pred=y_pred,
 227:                 score_distr_file_path=self.mse_score_distr_file_path
 228:             )
 229:
 230:         # save model
 231:         torch.save(self.model.state_dict(), self.model_path)
 232:         torch.save({
 233:             'epoch':epoch,
 234:             'model_state_dict':self.model.state_dict(),
 235:             'optimizer_state_dict':self.optimizer.state_dict(),

In [156]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

terms = [
    "train_loader",
    "valid_loader",
    "validation_list",
    "train_data",
]

for path in sorted(root.rglob("*.py")):
    try:
        lines = path.read_text(
            encoding="utf-8", errors="replace"
        ).splitlines()
    except Exception:
        continue

    hits = [
        i for i, line in enumerate(lines)
        if any(term in line for term in terms)
    ]

    if hits:
        print(f"\n--- {path.relative_to(root)} ---")
        shown = set()
        for i in hits:
            start = max(0, i - 2)
            end = min(len(lines), i + 3)
            for j in range(start, end):
                if j not in shown:
                    print(f"{j+1:4}: {lines[j]}")
                    shown.add(j)

--- datasets/datasets.py ---
  37:         self.id_list = [int(machine_id) for machine_id in self.section_id_list]
  38:         section_keyword = get_machine_type_dict(dataset_name, mode=args.dev)["section_keyword"]
  39:         train_data = DCASE202XT2Loader(
  40:                 data_path,
  41:                 dataset_name=dataset_name,
  59:                 )
  60:
  61:         train_index, valid_index = train_test_split(range(len(train_data)), test_size=args.validation_split)
  62:         self.train_dataset = Subset(train_data, train_index)
  63:         self.train_loader = torch.utils.data.DataLoader(
  64:             self.train_dataset,
  65:             batch_size=batch_size, shuffle=shuffle, batch_sampler=batch_sampler,
  66:         )
  67:         self.valid_dataset   = Subset(train_data, valid_index)
  68:         self.valid_loader = torch.utils.data.DataLoader(
  69:             self.valid_dataset,
  70:             batch_size=batch_size, shuffle=False, batch_sampler=batch_sampler,

--- networks/base_model.py ---
  25:             print("please set another name \n{}".format(Datasets.show_list()))
  26:             raise e
  27:         self.train_loader = self.data.train_loader
  28:         self.valid_loader = self.data.valid_loader
  29:         self.test_loader = self.data.test_loader
  30:

--- networks/dcase2023t2_ae/dcase2023t2_ae.py ---
  52:         y_pred = []
  53:
  54:         train_loader = self.train_loader
  55:
  56:         if epoch == self.args.epochs + 1:
  71:             is_calc_cov = False
  72:
  73:         for batch_idx, batch in enumerate(tqdm(train_loader)):
  74:             data = batch[0]
  75:             data = data.to(self.device).float()
 144:             if batch_idx % self.args.log_interval == 0 and not is_calc_cov:
 145:                 print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
 146:                     epoch, batch_idx * len(data), len(train_loader.dataset),
 147:                     100. * batch_idx / len(train_loader),
 148:                     self.loss.item()))
 149:
 163:             )
 164:             y_pred_mahala = []
 165:             for batch_idx, batch in enumerate(tqdm(train_loader)):
 166:                 y_pred_mahala = self.calc_valid_mahala_score(
 167:                     data=batch[0],
 170:                     inv_cov_target=inv_cov_target,
 171:                 )
 172:             for batch_idx, batch in enumerate(self.valid_loader):
 173:                 y_pred_mahala = self.calc_valid_mahala_score(
 174:                     data=batch[0],
 186:         with torch.no_grad():
 187:             self.model.eval()
 188:             for batch_idx, batch in enumerate(self.valid_loader):
 189:                 data = batch[0]
 190:                 data = data.to(self.device).float()
 206:             print('====> Epoch: {} Average loss: {:.4f} Validation loss: {:.4f}'.format(
 207:                   epoch,
 208:                   train_loss / len(train_loader),
 209:                   val_loss / len(self.valid_loader)))
 210:             with open(self.log_path, 'a') as log:
 211:                 np.savetxt(log,["{0},{1},{2},{3},{4}".format(
 212:                     train_loss / len(train_loader),
 213:                     val_loss / len(self.valid_loader),
 214:                     train_recon_loss / len(train_loader),
 215:                     train_recon_loss_source / len(train_loader),
 216:                     train_recon_loss_target / len(train_loader),
 217:                     )],fmt="%s")
 218:             csv_to_figdata(

In [157]:
from pathlib import Path

root = Path("/content/dcase2026_baseline_ae")

for relative_path in [
    "datasets/datasets.py",
    "datasets/loader_common.py",
]:
    path = root / relative_path
    print(f"\n--- {relative_path} ---")

    if not path.exists():
        print("File not found")
        continue

    lines = path.read_text(
        encoding="utf-8", errors="replace"
    ).splitlines()

    limit = min(len(lines), 115)
    for i in range(limit):
        print(f"{i+1:4}: {lines[i]}")

--- datasets/datasets.py ---
   1: import torch
   2: from torch.utils.data.dataset import Subset
   3: from sklearn.model_selection import train_test_split
   4: import sys
   5:
   6: from datasets.loader_common import get_machine_type_dict
   7: from datasets.dcase_dcase202x_t2_loader import DCASE202XT2Loader
   8:
   9: class DCASE202XT2(object):
  10:     def __init__(self, args):
  11:         self.width   = args.frames
  12:         self.height  = args.n_mels
  13:         self.channel = 1
  14:         self.input_dim = self.width*self.height*self.channel
  15:         shuffle = args.shuffle
  16:         batch_sampler = None
  17:         batch_size = args.batch_size
  18:         print("input dim: %d" % (self.input_dim))
  19:
  20:         dataset_name = args.dataset[:11]
  21:         machine_type = args.dataset[11:]
  22:         if args.eval:
  23:             data_path = f'{args.dataset_directory}/{dataset_name.lower()}/eval_data/'
  24:             data_type = "eval"
  25:         elif args.dev:
  26:             data_path = f'{args.dataset_directory}/{dataset_name.lower()}/dev_data/'
  27:             data_type = "dev"
  28:         else:
  29:             print("incorrect argument")
  30:             print("please set option argument '--dev' or '--eval'")
  31:             sys.exit()
  32:
  33:         self.machine_type_dict = get_machine_type_dict(dataset_name, mode=args.dev)["machine_type"]
  34:         self.section_id_list = self.machine_type_dict[machine_type][data_type]
  35:         self.num_classes = len(self.section_id_list)
  36:         print("num classes: %d" % (self.num_classes))
  37:         self.id_list = [int(machine_id) for machine_id in self.section_id_list]
  38:         section_keyword = get_machine_type_dict(dataset_name, mode=args.dev)["section_keyword"]
  39:         train_data = DCASE202XT2Loader(
  40:                 data_path,
  41:                 dataset_name=dataset_name,
  42:                 section_keyword=section_keyword,
  43:                 machine_type=machine_type,
  44:                 train=True,
  45:                 section_ids=self.section_id_list,
  46:                 frames=args.frames,
  47:                 n_mels=args.n_mels,
  48:                 frame_hop_length=args.frame_hop_length,
  49:                 n_fft=args.n_fft,
  50:                 hop_length=args.hop_length,
  51:                 power=args.power,
  52:                 fmax=args.fmax,
  53:                 fmin=args.fmin,
  54:                 win_length=args.win_length,
  55:                 data_type=data_type,
  56:                 use_id=args.use_ids,
  57:                 is_auto_download=args.is_auto_download,
  58:                 mono=args.mono,
  59:                 )
  60:
  61:         train_index, valid_index = train_test_split(range(len(train_data)), test_size=args.validation_split)
  62:         self.train_dataset = Subset(train_data, train_index)
  63:         self.train_loader = torch.utils.data.DataLoader(
  64:             self.train_dataset,
  65:             batch_size=batch_size, shuffle=shuffle, batch_sampler=batch_sampler,
  66:         )
  67:         self.valid_dataset   = Subset(train_data, valid_index)
  68:         self.valid_loader = torch.utils.data.DataLoader(
  69:             self.valid_dataset,
  70:             batch_size=batch_size, shuffle=False, batch_sampler=batch_sampler,
  71:         )
  72:
  73:         self.test_loader = []
  74:         if args.train_only:
  75:             return
  76:         for id in self.section_id_list:
  77:            _test_loader = DCASE202XT2Loader(
  78:                 data_path,
  79:                 dataset_name=dataset_name,
  80:                 section_keyword=section_keyword,
  81:                 machine_type=machine_type,
  82:                 train=False,
  83:                 section_ids=[id],
  84:                 frames=args.frames,
  85:                 n_mels=args.n_mels,
  86:                 frame_hop_length=args.frame_hop_length,
  87:                 n_fft=args.n_fft,
  88:                 hop_length=args.hop_length,
  89:                 power=args.power,
  90:                 fmax=args.fmax,
  91:                 fmin=args.fmin,
  92:                 win_length=args.win_length,
  93:                 data_type=data_type,
  94:                 is_auto_download=args.is_auto_download,
  95:                 mono=args.mono,
  96:            )
  97:
  98:            self.test_loader.append(
  99:                 torch.utils.data.DataLoader(
 100:                     _test_loader,
 101:                     batch_size=_test_loader.n_vectors_ea_file, shuffle=False
 102:                 )
 103:            )
 104:            self.mode = args.dev or _test_loader.mode
 105:
 106:
 107: class Datasets:
 108:     DatasetsDic = {
 109:         'DCASE2026T2ToyDrone':DCASE202XT2,
 110:         'DCASE2026T2ToothBrush':DCASE202XT2,
 111:         'DCASE2026T2SewingMachine':DCASE202XT2,
 112:         'DCASE2026T2BlowerDustCollector':DCASE202XT2,
 113:         'DCASE2026T2Sander':DCASE202XT2,
 114:         'DCASE2026T2valveEmu':DCASE202XT2,
 115:         'DCASE2026T2sliderEmu':DCASE202XT2,

--- datasets/loader_common.py ---
   1: ########################################################################
   2: # import python-library
   3: ########################################################################
   4: # default
   5: import glob
   6: import argparse
   7: import random
   8: import sys
   9: import os
  10: import itertools
  11: import re
  12: import pathlib
  13:
  14: # additional
  15: import numpy as np
  16: import librosa
  17: import librosa.core
  18: import librosa.feature
  19: import yaml
  20: import urllib.request
  21: import urllib.error
  22: import zipfile
  23: import shutil
  24: import time
  25: import fasteners
  26: import pickle
  27: import pickletools
  28: import time
  29: import datetime
  30: from enum import Enum, auto
  31: import soundfile as sf
  32:
  33: from tools.rename_eval_wav import copy_wav as rename_wav
  34: ########################################################################
  35:
  36:
  37: ########################################################################
  38: # setup STD I/O
  39: ########################################################################
  40: """
  41: Standard output is logged in "baseline.log".
  42: """
  43: import logging
  44:
  45: logging.basicConfig(level=logging.DEBUG, filename="baseline.log")
  46: logger = logging.getLogger(' ')
  47: handler = logging.StreamHandler()
  48: formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
  49: handler.setFormatter(formatter)
  50: logger.addHandler(handler)
  51:
  52:
  53: ########################################################################
  54:
  55:
  56: ########################################################################
  57: # version
  58: ########################################################################
  59: __versions__ = "1.0.0"
  60: ########################################################################
  61:
  62:
  63: ########################################################################
  64: # download dataset parameter
  65: ########################################################################
  66: DOWNLOAD_PATH_YAML_DICT = {
  67:     "DCASE2026T2":"datasets/download_path_2026.yaml",
  68:     "DCASE2025T2":"datasets/download_path_2025.yaml",
  69:     "DCASE2024T2":"datasets/download_path_2024.yaml",
  70:     "DCASE2023T2":"datasets/download_path_2023.yaml",
  71:     "legacy":"datasets/download_path_legacy.yaml",
  72: }
  73: ########################################################################
  74:
  75:
  76: ########################################################################
  77: # load parameter.yaml
  78: ########################################################################
  79: # def yaml_load():
  80: #     with open("baseline.yaml") as stream:
  81: #         param = yaml.safe_load(stream)
  82: #     return param
  83:
  84: ########################################################################
  85:
  86:
  87: ########################################################################
  88: # file I/O
  89: ########################################################################
  90: # wav file input
  91: def file_load(wav_name, mono=False):
  92:     """
  93:     load .wav file.
  94:
  95:     wav_name : str
  96:         target .wav file
  97:     mono : boolean
  98:         When load a multi channels file and this param True, the returned data will be merged for mono data
  99:
 100:     return : numpy.array( float )
 101:     """
 102:     info = sf.info(wav_name)
 103:     ch = info.channels
 104:     assert any([
 105:         mono and ch == 1,
 106:         not mono and ch > 1,
 107:     ]), f"Channel mismatch: The file is {ch=}, but {mono=} is specified."
 108:
 109:     try:
 110:         if mono:
 111:             return librosa.load(wav_name, sr=None, mono=mono)
 112:         else:
 113:             y, sr = librosa.load(wav_name, sr=None, mono=mono)
 114:             return y[0], sr
 115:     except:

In [1]:
from pathlib import Path
import pandas as pd

out_dir = Path("/content/AURIX.V1/experiments")
out_dir.mkdir(parents=True, exist_ok=True)

rows = [
    {
        "domain": "all",
        "model": "Spectral-only",
        "ROC_AUC": 0.5517,
        "Average_Precision": 0.5795,
    },
    {
        "domain": "all",
        "model": "Temporal-only",
        "ROC_AUC": 0.4506,
        "Average_Precision": 0.4796,
    },
    {
        "domain": "all",
        "model": "Fusion",
        "ROC_AUC": 0.5600,
        "Average_Precision": 0.5595,
    },
    {
        "domain": "source",
        "model": "Spectral-only",
        "ROC_AUC": 0.5256,
        "Average_Precision": 0.5654,
    },
    {
        "domain": "source",
        "model": "Temporal-only",
        "ROC_AUC": 0.4436,
        "Average_Precision": 0.4691,
    },
    {
        "domain": "source",
        "model": "Fusion",
        "ROC_AUC": 0.5484,
        "Average_Precision": 0.5652,
    },
    {
        "domain": "target",
        "model": "Spectral-only",
        "ROC_AUC": 0.5768,
        "Average_Precision": 0.6051,
    },
    {
        "domain": "target",
        "model": "Temporal-only",
        "ROC_AUC": 0.4604,
        "Average_Precision": 0.5032,
    },
    {
        "domain": "target",
        "model": "Fusion",
        "ROC_AUC": 0.5676,
        "Average_Precision": 0.5623,
    },
]

df = pd.DataFrame(rows)
df["evaluation_status"] = "Exploratory; test data previously used"
df["independent_final_result"] = False

out_path = out_dir / "aurix_comparison_table_exploratory_seed13711.csv"
df.to_csv(out_path, index=False)

print(df.to_string(index=False))
print(f"\nSaved new file: {out_path}")
print(f"Rows: {len(df)}")

domain         model  ROC_AUC  Average_Precision                      evaluation_status  independent_final_result
   all Spectral-only   0.5517             0.5795 Exploratory; test data previously used                     False
   all Temporal-only   0.4506             0.4796 Exploratory; test data previously used                     False
   all        Fusion   0.5600             0.5595 Exploratory; test data previously used                     False
source Spectral-only   0.5256             0.5654 Exploratory; test data previously used                     False
source Temporal-only   0.4436             0.4691 Exploratory; test data previously used                     False
source        Fusion   0.5484             0.5652 Exploratory; test data previously used                     False
target Spectral-only   0.5768             0.6051 Exploratory; test data previously used                     False
target Temporal-only   0.4604             0.5032 Exploratory; test data previously used                     False
target        Fusion   0.5676             0.5623 Exploratory; test data previously used                     False

Saved new file: /content/AURIX.V1/experiments/aurix_comparison_table_exploratory_seed13711.csv
Rows: 9

In [12]:
from pathlib import Path
import pandas as pd

path = Path(
    "/content/AURIX.V1/experiments/"
    "aurix_pathway_validation_scores_seed13711.csv"
)

df = pd.read_csv(path)

print("Validation rows:", len(df))
print("Available columns:")
print(df.columns.tolist())
print("\nValidation scores:")
print(df.to_string(index=False))

FileNotFoundError: [Errno 2] No such file or directory: '/content/AURIX.V1/experiments/aurix_pathway_validation_scores_seed13711.csv'

In [4]:
from pathlib import Path

root = Path("/content/AURIX.V1/experiments")

print("Experiments folder exists:", root.exists())

if root.exists():
    print("\nFiles related to AURIX:")
    for p in sorted(root.glob("*")):
        if "validation" in p.name.lower() or "pathway" in p.name.lower():
            print(p.name)
else:
    print("Project folder not found at the expected path.")

Experiments folder exists: True

Files related to AURIX:

In [5]:
from pathlib import Path

root = Path("/content/AURIX.V1/experiments")

for p in sorted(root.iterdir()):
    print(("[DIR] " if p.is_dir() else "[FILE] ") + p.name)

[FILE] aurix_comparison_table_exploratory_seed13711.csv

In [6]:
from pathlib import Path

search_roots = [
    Path("/content/AURIX.V1"),
    Path("/content"),
]

seen = set()

for root in search_roots:
    if not root.exists():
        continue

    for p in root.rglob("aurix_pathway_validation_scores_seed13711.csv"):
        if str(p) not in seen:
            print(p)
            seen.add(str(p))

if not seen:
    print("Validation score file not found in /content.")

Validation score file not found in /content.

In [7]:
from pathlib import Path

root = Path("/content/AURIX.V1")

patterns = [
    "aurix_*pilot*",
    "aurix_specialized*",
    "aurix_pathway*",
]

found = set()

for pattern in patterns:
    for p in root.rglob(pattern):
        if p.is_file() and p not in found:
            print(p)
            found.add(p)

if not found:
    print("No matching experiment files found inside AURIX.V1.")

No matching experiment files found inside AURIX.V1.

In [8]:
from pathlib import Path

root = Path("/content")
extensions = {".pt", ".npz", ".csv", ".json"}

for p in sorted(root.rglob("*")):
    if p.is_file() and p.suffix.lower() in extensions:
        name = p.name.lower()
        if any(key in name for key in [
            "aurix", "pilot", "13711", "validation", "specialized"
        ]):
            print(p)

/content/AURIX.V1/experiments/aurix_comparison_table_exploratory_seed13711.csv

In [9]:
from pathlib import Path
import subprocess

root = Path("/content/AURIX.V1")

result = subprocess.run(
    ["git", "-C", str(root), "remote", "-v"],
    capture_output=True,
    text=True
)

print(result.stdout if result.stdout.strip() else
      "No Git remote found for the current project folder.")

No Git remote found for the current project folder.

In [10]:
from pathlib import Path

for path in [
    Path("/content"),
    Path("/content/AURIX.V1"),
    Path("/content/AURIX.V1/experiments"),
]:
    print(f"\n{path}")
    print("Exists:", path.exists())

    if path.exists():
        for item in sorted(path.iterdir()):
            kind = "DIR " if item.is_dir() else "FILE"
            print(f"  [{kind}] {item.name}")

/content
Exists: True
  [DIR ] .config
  [DIR ] AURIX.V1
  [DIR ] sample_data

/content/AURIX.V1
Exists: True
  [DIR ] experiments

/content/AURIX.V1/experiments
Exists: True
  [FILE] aurix_comparison_table_exploratory_seed13711.csv

In [11]:
import sys

print("Python session is running.")

for name in ["torch", "librosa", "numpy", "pandas"]:
    print(f"{name} loaded:", name in sys.modules)

Python session is running.
torch loaded: False
librosa loaded: False
numpy loaded: True
pandas loaded: True